from pathlib import Path
from typing import TYPE_CHECKING

import pytest

from sarj_python_lint.rule_base import RuleExample, Severity
from sarj_python_lint.rules.typed_error_reasons import TypedErrorReasons


if TYPE_CHECKING:
    from sarj_python_lint.rule_base import Diagnostic


def _check(source: str, path: str = "app/errors.py") -> list[Diagnostic]:
    return TypedErrorReasons().check(Path(path), source)


_PUBLIC_EXAMPLES = TypedErrorReasons.public_examples()


@pytest.mark.parametrize("example", _PUBLIC_EXAMPLES, ids=tuple(example.example_id for example in _PUBLIC_EXAMPLES))
def test_public_documentation_examples_are_executable(example: RuleExample) -> None:
    focus = example.focus_file
    assert len(_check(focus.source, str(focus.path))) == example.expected_count


def test_reports_the_join_expression_as_a_warning() -> None:
    source = """
class DomainError(Exception): ...

class IncompleteError(DomainError):
    def __init__(self, reasons: list[str]) -> None:
        super().__init__(f"Incomplete: {'; '.join(reasons)}")
"""
    [diagnostic] = _check(source)

    assert diagnostic.line == 6
    assert diagnostic.severity is Severity.WARNING
    assert "`reasons: list[str]`" in diagnostic.message


def test_reports_once_when_the_parameter_is_joined_twice() -> None:
    source = """
class BatchError(Exception):
    def __init__(self, messages: list[str]) -> None:
        super().__init__(f"{'; '.join(messages)} / {', '.join(messages)}")
"""
    assert len(_check(source)) == 1


@pytest.mark.parametrize(
    "source",
    [
        pytest.param(
            """
class IncompleteError(Exception):
    def __init__(self, reasons: list[Reason]) -> None:
        self.reasons = reasons
        super().__init__("Incomplete")
""",
            id="typed-reason-records",
        ),
        pytest.param(
            """
class EndpointInUseError(Exception):
    def __init__(self, endpoint: str, action_names: list[str]) -> None:
        super().__init__(f"{endpoint} is used by {', '.join(action_names)}")
""",
            id="contextual-display-list",
        ),
        pytest.param(
            """
class IncompleteError(Exception):
    def __init__(self, reasons: list[str]) -> None:
        self.reasons = reasons
        super().__init__("Incomplete")
""",
            id="stored-but-not-rendered",
        ),
        pytest.param(
            """
class IncompleteError(Exception):
    def __init__(self, reasons: list[str]) -> None:
        super().__init__(format_reasons(reasons))
""",
            id="separate-formatter",
        ),
        pytest.param(
            """
class ErrorReport(BaseModel):
    def __init__(self, reasons: list[str]) -> None:
        super().__init__(message='; '.join(reasons))
""",
            id="non-exception-class",
        ),
        pytest.param(
            """
class IncompleteError(Exception):
    def __init__(self, reasons: List[str]) -> None:
        super().__init__('; '.join(reasons))
""",
            id="legacy-list-annotation-fails-open",
        ),
        pytest.param(
            """
def validation_messages(payload: object) -> list[str]:
    messages: list[str] = []
    messages.append("A field is missing")
    messages.append("A field is invalid")
    return messages
""",
            id="ordinary-validation-helper",
        ),
    ],
)
def test_conservative_near_misses(source: str) -> None:
    assert _check(source) == []


def test_test_and_generated_paths_are_excluded() -> None:
    source = """
class BatchError(Exception):
    def __init__(self, messages: list[str]) -> None:
        super().__init__('; '.join(messages))
"""
    assert _check(source, "tests/test_errors.py") == []
    assert _check(f"# Generated by tool\n{source}") == []


def test_malformed_source_fails_open() -> None:
    assert _check("class BrokenError(Exception):\n  def __init__(") == []


def test_nested_join_does_not_leak_into_the_constructor() -> None:
    source = """
class BatchError(Exception):
    def __init__(self, messages: list[str]) -> None:
        def render() -> str:
            return '; '.join(messages)
        super().__init__(render())
"""
    assert _check(source) == []
