from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

import pytest

from sarj_python_lint.rules.no_gen_random_uuid_in_sql import NoGenRandomUuidInSql


if TYPE_CHECKING:
    from sarj_python_lint.rule_base import Diagnostic


def _check(source: str, path: Path = Path("svc/app/store.py")) -> list[Diagnostic]:
    return NoGenRandomUuidInSql().check(path, source)


@pytest.mark.parametrize(
    "source",
    [
        pytest.param(
            'SQL = "CREATE TABLE call (id UUID PRIMARY KEY DEFAULT gen_random_uuid())"\n',
            id="create-table-default",
        ),
        pytest.param(
            'SQL = "ALTER TABLE call ALTER COLUMN id SET DEFAULT gen_random_uuid()"\n',
            id="alter-table-default",
        ),
        pytest.param(
            'SQL = "INSERT INTO call (id) VALUES (gen_random_uuid())"\n',
            id="insert-values",
        ),
        pytest.param(
            'SQL = "SELECT gen_random_uuid() AS id"\n',
            id="select",
        ),
        pytest.param(
            'SQL = "UPDATE call SET id = gen_random_uuid()"\n',
            id="update",
        ),
        pytest.param(
            'SQL = "create table t (id uuid default GEN_RANDOM_UUID())"\n',
            id="case-insensitive",
        ),
        pytest.param(
            'SQL = "CREATE TABLE t (id UUID DEFAULT gen_random_uuid ())"\n',
            id="space-before-paren",
        ),
        pytest.param(
            'SQL = """\nCREATE TABLE t (\n  id UUID DEFAULT gen_random_uuid()\n)\n"""\n',
            id="triple-quoted",
        ),
        pytest.param(
            'SQL = ("CREATE TABLE t (id UUID DEFAULT "\n       "gen_random_uuid())")\n',
            id="implicitly-concatenated",
        ),
    ],
)
def test_flags_embedded_sql(source: str):
    assert len(_check(source)) == 1


def test_message_names_uuidv7():
    diags = _check('SQL = "CREATE TABLE t (id UUID DEFAULT gen_random_uuid())"\n')
    assert "uuidv7()" in diags[0].message
    assert diags[0].code == "SARJ053"


@pytest.mark.parametrize(
    "source",
    [
        pytest.param(
            'SQL = "CREATE TABLE t (id UUID PRIMARY KEY DEFAULT uuidv7())"\n',
            id="already-uuidv7",
        ),
        pytest.param(
            'MSG = "gen_random_uuid() is banned; use uuidv7()"\n',
            id="prose-naming-the-function",
        ),
        pytest.param(
            'def f():\n    """Do not use gen_random_uuid() here."""\n',
            id="docstring-naming-the-function",
        ),
        pytest.param(
            'SQL = "SELECT id FROM t -- was DEFAULT gen_random_uuid()"\n',
            id="inside-a-sql-comment",
        ),
        pytest.param(
            "SQL = \"SELECT * FROM t WHERE note = 'DEFAULT gen_random_uuid()'\"\n",
            id="inside-a-quoted-sql-value",
        ),
        pytest.param(
            'SQL = "SELECT id FROM t /* DEFAULT gen_random_uuid() */"\n',
            id="inside-a-block-comment",
        ),
        pytest.param(
            'NAME = "gen_random_uuid_helper"\n',
            id="identifier-prefix-only",
        ),
    ],
)
def test_allows(source: str):
    assert _check(source) == []


def test_flags_once_per_literal_not_once_per_occurrence():
    src = 'SQL = "CREATE TABLE t (a UUID DEFAULT gen_random_uuid(), b UUID DEFAULT gen_random_uuid())"\n'
    assert len(_check(src)) == 1


def test_flags_each_offending_literal():
    src = 'A = "CREATE TABLE a (id UUID DEFAULT gen_random_uuid())"\nB = "CREATE TABLE b (id UUID DEFAULT gen_random_uuid())"\n'
    assert [d.line for d in _check(src)] == [1, 2]


def test_exempts_generated_files():
    src = '# @generated by protoc. DO NOT EDIT.\nSQL = "CREATE TABLE t (id UUID DEFAULT gen_random_uuid())"\n'
    assert _check(src) == []


def test_unparsable_source_yields_no_diagnostics():
    assert _check('SQL = "CREATE TABLE t (id UUID DEFAULT gen_random_uuid())"\ndef (:\n') == []


def test_applies_to_test_files_too():
    src = 'SQL = "CREATE TABLE t (id UUID DEFAULT gen_random_uuid())"\n'
    assert len(_check(src, Path("svc/tests/test_store.py"))) == 1
