from pathlib import Path
from textwrap import dedent

import pytest

from sarj_python_lint.rule_base import Severity
from sarj_python_lint.rules.prefer_immutable_module_constant import PreferImmutableModuleConstant


@pytest.mark.parametrize(
    ("source", "replacement"),
    [
        pytest.param("VALUES = [1, 2, 3]", "tuple", id="list"),
        pytest.param("KINDS = {'a', 'b'}", "frozenset", id="set"),
        pytest.param("LABELS = {'a': 'A'}", "immutable mapping", id="dict"),
        pytest.param("CACHE = dict()", "immutable mapping", id="empty-dict"),
        pytest.param("VALUES = list(runtime_values)", "tuple", id="populated-list-constructor"),
        pytest.param("KINDS = set(runtime_values)", "frozenset", id="populated-set-constructor"),
        pytest.param("LABELS = dict(runtime_items)", "immutable mapping", id="populated-dict-constructor"),
        pytest.param("_VALUES = [1, 2, 3]", "tuple", id="private-constant"),
        pytest.param("X = [1, 2, 3]", "tuple", id="single-letter-constant"),
        pytest.param("VALUES = [runtime_value]", "tuple", id="dynamic-list-element"),
        pytest.param("LABELS = {'value': runtime_value}", "immutable mapping", id="dynamic-dict-value"),
        pytest.param("VALUES = [*runtime_values]", "tuple", id="dynamic-list-spread"),
    ],
)
def test_warns_for_literal_mutable_module_constants(source: str, replacement: str) -> None:
    findings = PreferImmutableModuleConstant().check(Path("service.py"), source)

    assert len(findings) == 1
    assert findings[0].code == "SARJ096"
    assert findings[0].severity is Severity.WARNING
    assert replacement in findings[0].message


@pytest.mark.parametrize(
    "source",
    [
        "VALUES = (1, 2, 3)",
        "KINDS = frozenset({'a', 'b'})",
        "LABELS = MappingProxyType({'a': 'A'})",
        "labels = {'a': 'A'}",
        "__all__ = ['public']",
        "VALUES = {'a'}\nVALUES.add('b')",
        "VALUES = {'a'}\nVALUES.difference_update({'b'})",
        "VALUES = [1]\nVALUES += [2]",
        "VALUES = [1]\nVALUES = [2]",
        "LABELS = {}\nLABELS['a'] = 'A'",
        "LABELS = {'a': []}\nLABELS['a'].append('A')",
        "LABELS = {'a': {'b': 'B'}}\nLABELS['a']['b'] = 'C'",
    ],
)
def test_ignores_immutable_dynamic_nonconstant_and_intentionally_mutated_values(source: str) -> None:
    assert PreferImmutableModuleConstant().check(Path("service.py"), source) == []


def test_ignores_test_and_generated_files() -> None:
    source = dedent("""\
        # generated by schema compiler
        VALUES = [1, 2, 3]
        """)

    rule = PreferImmutableModuleConstant()
    assert rule.check(Path("tests/test_service.py"), "VALUES = [1, 2, 3]") == []
    assert rule.check(Path("generated.py"), source) == []
