from __future__ import annotations

from pathlib import Path

from sarj_python_lint.rules.no_report_call_issue_ignore import NoReportCallIssueIgnore


RULE = NoReportCallIssueIgnore()


def run(source: str, path: str = "service.py"):
    return RULE.check(Path(path), source)


def test_flags_type_ignore_report_call_issue() -> None:
    diags = run('say("oops")  # type: ignore[reportCallIssue]\n')

    assert len(diags) == 1
    assert diags[0].code == "SARJ055"
    assert diags[0].line == 1


def test_allows_pyright_ignore_report_call_issue() -> None:
    diags = run("client.bad(arg)  # pyright: ignore[reportUnknownArgumentType, reportCallIssue]\n")

    assert diags == []


def test_allows_other_type_suppressions() -> None:
    assert run('value = data["x"]  # pyright: ignore[reportAny]\n') == []
    assert run('value = data["x"]  # type: ignore[arg-type]\n') == []
    assert run("Model()  # type: ignore[call-arg]  # pyright: ignore[reportCallIssue]\n") == []


def test_generated_sources_are_ignored() -> None:
    assert run(
        "# Generated by OpenAPI Generator\n"
        "client.bad(arg)  # type: ignore[reportCallIssue]\n",
    ) == []
