from pathlib import Path
from typing import TYPE_CHECKING

import pytest

from sarj_python_lint.rule_base import Severity
from sarj_python_lint.rules.prefer_namedtuple_over_tuple_return import PreferNamedtupleOverTupleReturn


if TYPE_CHECKING:
    from sarj_python_lint.rule_base import Diagnostic, RuleExample


def _check(source: str, path: str = "python/app/profile.py") -> list[Diagnostic]:
    return PreferNamedtupleOverTupleReturn().check(Path(path), source)


@pytest.mark.parametrize(
    "example",
    PreferNamedtupleOverTupleReturn.public_examples(),
    ids=[example.example_id for example in PreferNamedtupleOverTupleReturn.public_examples()],
)
def test_public_documentation_examples_are_executable(example: RuleExample) -> None:
    assert len(_check(example.focus_file.source, str(example.focus_file.path))) == example.expected_count


def test_rule_identity_keeps_compatibility_alias() -> None:
    rule = PreferNamedtupleOverTupleReturn()

    assert rule.code == "SARJ026"
    assert rule.id == "no-positional-tuple-record"
    assert rule.documentation is not None
    assert rule.documentation.aliases == ("prefer-namedtuple-over-tuple-return",)


@pytest.mark.parametrize(
    "source",
    [
        "def classify() -> tuple[FlowKind, str | None]: ...\n",
        "def totals() -> tuple[float, float]: ...\n",
        "class Service:\n    def _pair(self) -> tuple[int, str]: ...\n",
        "@app.get('/')\ndef pair() -> tuple[int, str]: ...\n",
        "def outer():\n    def pair() -> tuple[int, str]: ...\n",
        "def pair() -> 'tuple[int, str]': ...\n",
        "from typing import Tuple\ndef pair() -> Tuple[int, str]: ...\n",
    ],
)
def test_flags_fixed_tuple_returns_everywhere(source: str) -> None:
    findings = _check(source, "tests/test_profile.py")

    assert len(findings) == 1
    assert findings[0].severity is Severity.ERROR
    assert "dataclass or validation model" in findings[0].message


@pytest.mark.parametrize(
    "source",
    [
        "def values() -> tuple[int, ...]: ...\n",
        "def values() -> tuple[int]: ...\n",
        "def values() -> list[tuple[int, str]]: ...\n",
        "def values() -> Profile: ...\n",
        "class tuple: ...\ndef values() -> tuple[int, str]: ...\n",
        "from fake import Tuple\ndef values() -> Tuple[int, str]: ...\n",
        "from fake import *\ndef values() -> tuple[int, str]: ...\n",
    ],
)
def test_allows_collections_named_records_and_unproven_bindings(source: str) -> None:
    assert _check(source) == []


@pytest.mark.parametrize("path", ["docs/example.py", "docs_src/example.py"])
def test_skips_documentation_examples(path: str) -> None:
    assert _check("def pair() -> tuple[int, str]: ...\n", path) == []


def test_skips_generated_source() -> None:
    assert _check("# Generated by protoc. Do not edit.\ndef pair() -> tuple[int, str]: ...\n") == []


def test_invalid_source_is_ignored() -> None:
    assert _check("def broken( -> tuple[int, str]:\n") == []
