from pathlib import Path
from textwrap import dedent
from typing import TYPE_CHECKING

import pytest

from sarj_python_lint.rule_base import Severity
from sarj_python_lint.rules.phase_label_comment import TestPhaseLabelComment


if TYPE_CHECKING:
    from sarj_python_lint.rule_base import Diagnostic, RuleExample


def _check(source: str, path: str = "tests/test_thing.py") -> list[Diagnostic]:
    return TestPhaseLabelComment().check(Path(path), dedent(source))


LABELS = [
    "given",
    "when",
    "then",
    "Arrange",
    "Act",
    "Assert",
    "Asserts",
    "Assertions",
    "ASSERTION",
    "Arrange phase",
    "Act phase",
    "Assert phase",
    "Arrange / Act",
    "Arrange & Act",
    "Act/Assert",
    "Act + Assert",
    "given / when",
    "Given&When",
    "When/Then",
    "When + Then",
    "Then:",
    "act.",
    "Assert -",
    "---- Arrange ----",
    "=== given ===",
    "****Assert****",
    "Arrange / Act / Assert",
    "Given / When / Then",
    "Arrange and Act and Assert",
    "Act -> Assert",
    "Given - When - Then",
    "Given → When → Then",
    "1. Arrange",
    "2) Act",
]

_PUBLIC_EXAMPLES = TestPhaseLabelComment.public_examples()


@pytest.mark.parametrize("example", _PUBLIC_EXAMPLES, ids=tuple(e.example_id for e in _PUBLIC_EXAMPLES))
def test_public_documentation_examples_are_executable(example: RuleExample) -> None:
    focus = example.focus_file
    assert len(TestPhaseLabelComment().check(Path(focus.path), focus.source)) == example.expected_count


@pytest.mark.parametrize("label", LABELS)
def test_flags_a_bare_phase_label(label: str) -> None:
    diags = _check(f"""
        def test_it():
            # {label}
            assert works()
        """)
    assert len(diags) == 1
    assert diags[0].code == "SARJ089"
    assert diags[0].severity is Severity.WARNING
    assert label in diags[0].message


def test_a_phase_word_carrying_a_sentence_is_left_alone() -> None:
    diags = _check("""
        def test_it():
            # then the retry loop would spin forever
            assert works()
        """)
    assert diags == []


def test_setup_and_teardown_belong_to_sarj016() -> None:
    diags = _check("""
        def test_it():
            # Setup
            client = make()
            # Teardown
            client.close()
        """)
    assert diags == []


@pytest.mark.parametrize(
    "comment", ["Execute", "Exercise", "Verify", "Verification", "Cleanup", "Prepare", "Sanity check"]
)
def test_generic_domain_or_lifecycle_words_are_left_alone(comment: str) -> None:
    diags = _check(f"""
        def test_it():
            # {comment}
            assert works()
        """)
    assert diags == []


def test_a_trailing_comment_is_not_a_phase_label() -> None:
    diags = _check("""
        def test_it():
            result = act()  # act
            assert result
        """)
    assert diags == []


def test_a_label_inside_a_bracketed_expression_is_left_alone() -> None:
    diags = _check("""
        def test_it():
            cases = [
                # given
                ("a", 1),
            ]
            assert cases
        """)
    assert diags == []


def test_a_non_test_file_is_left_alone() -> None:
    diags = _check(
        """
        def run():
            # then
            return 1
        """,
        path="src/app/pipeline.py",
    )
    assert diags == []


def test_generated_files_are_exempt() -> None:
    diags = _check("""
        # Code generated by a tool. DO NOT EDIT.
        def test_it():
            # given
            assert works()
        """)
    assert diags == []


def test_a_word_merely_starting_with_a_phase_word_is_left_alone() -> None:
    diags = _check("""
        def test_it():
            # actor
            assert works()
        """)
    assert diags == []


@pytest.mark.parametrize(
    "comment",
    [
        "----",
        "then?",
        "Act II",
        "Arrange / Act / Assert the result",
        "Given / When / Therefore",
        f"{'-' * 41} Arrange",
        "-*- coding: utf-8 -*-",
    ],
)
def test_decoration_and_joins_do_not_hide_non_phase_content(comment: str) -> None:
    diags = _check(f"""
        def test_it():
            # {comment}
            assert works()
        """)

    assert diags == []


def test_reports_every_label_in_source_order() -> None:
    diags = _check("""
        def test_it():
            # given
            a = 1
            # when
            b = f(a)
            # then
            assert b
        """)
    assert [d.line for d in diags] == [3, 5, 7]
    assert {d.col for d in diags} == {5}


def test_an_unparseable_file_reports_nothing() -> None:
    assert _check("def test_it(:\n    # given\n") == []


@pytest.mark.parametrize("source", ["def test_it()\n    # Arrange\n    pass\n", "x = (1 2)\n# Arrange\n"])
def test_tokenizable_but_invalid_python_reports_nothing(source: str) -> None:
    assert _check(source) == []
