from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

import pytest

from sarj_python_lint.rules.no_stdlib_logging import NoStdlibLogging


if TYPE_CHECKING:
    from sarj_python_lint.rule_base import Diagnostic


_PROD = Path("svc/app/service.py")


def _check(source: str, path: Path = _PROD) -> list[Diagnostic]:
    return NoStdlibLogging().check(path, source)


@pytest.mark.parametrize(
    "source",
    [
        pytest.param("import logging\n", id="plain-import"),
        pytest.param("import logging as stdlib_logging\n", id="aliased-import"),
        pytest.param("import logging.config\n", id="submodule-import"),
        pytest.param("from logging import getLogger\n", id="from-import"),
        pytest.param("from logging.handlers import RotatingFileHandler\n", id="from-submodule-import"),
        pytest.param("import os, logging\n", id="multi-name-import"),
        pytest.param("def wire():\n    import logging\n", id="function-local-import"),
        pytest.param("class C:\n    import logging\n", id="class-body-import"),
    ],
)
def test_flags_runtime_stdlib_logging_imports(source: str):
    assert len(_check(source)) == 1


def test_message_names_loguru():
    diags = _check("import logging\n")
    assert "loguru" in diags[0].message
    assert diags[0].code == "SARJ052"


def test_reports_each_import_statement_once():
    src = "import logging\nfrom logging import getLogger\n"
    assert [d.line for d in _check(src)] == [1, 2]


@pytest.mark.parametrize(
    "source",
    [
        pytest.param(
            "import logging\n\nfrom loguru import logger\n\nlogging.basicConfig(handlers=[Intercept()], level=0)\n",
            id="bridge-from-loguru",
        ),
        pytest.param(
            "import logging\nimport loguru\n\n\nclass Intercept(logging.Handler):\n    pass\n",
            id="bridge-import-loguru",
        ),
        pytest.param("import logging\nfrom loguru._logger import Logger\n", id="bridge-loguru-submodule"),
        pytest.param(
            "import logging as stdlib_logging\nfrom loguru import logger\n\nroot = stdlib_logging.getLogger()\n",
            id="bridge-repoints-the-root-logger",
        ),
        pytest.param(
            "import logging\nfrom loguru import logger\n\nlogging.getLogger('httpx').setLevel(logging.WARNING)\n",
            id="bridge-quiets-a-dependency",
        ),
        pytest.param("from loguru import logger\n", id="no-stdlib-import"),
        pytest.param("from structlog import get_logger\n", id="other-logging-library"),
        pytest.param("from myapp.logging import setup\n", id="first-party-logging-module"),
        pytest.param("from .logging import setup\n", id="relative-sibling-import"),
        pytest.param("import logging_tree\n", id="name-merely-prefixed"),
    ],
)
def test_allows(source: str):
    assert _check(source) == []


def test_naming_loguru_is_not_on_its_own_a_bridge():
    # The exemption's premise is that the module *configures* stdlib logging.
    # A module that merely emits through both has opened the second hierarchy the
    # rule exists to prevent, and it is the likeliest place for one to appear.
    src = "import logging\n\nfrom loguru import logger\n\nlog = logging.getLogger(__name__)\nlog.info('hi')\n"
    assert [d.line for d in _check(src)] == [1]


def test_allows_type_checking_only_import():
    src = "from typing import TYPE_CHECKING\n\nif TYPE_CHECKING:\n    import logging\n"
    assert _check(src) == []


def test_allows_qualified_type_checking_guard():
    src = "import typing\n\nif typing.TYPE_CHECKING:\n    from logging import Logger\n"
    assert _check(src) == []


def test_flags_runtime_import_alongside_an_unrelated_type_checking_block():
    src = (
        "from typing import TYPE_CHECKING\n\n"
        "if TYPE_CHECKING:\n    from collections.abc import Iterator\n\n"
        "import logging\n"
    )
    assert len(_check(src)) == 1


@pytest.mark.parametrize(
    "path",
    [
        pytest.param(Path("svc/tests/test_thing.py"), id="test-module"),
        pytest.param(Path("svc/tests/conftest.py"), id="conftest"),
        pytest.param(Path("svc/thing_test.py"), id="test-suffix"),
        pytest.param(Path("scripts/backfill.py"), id="scripts-dir"),
        pytest.param(Path("python/scripts/backfill.py"), id="nested-scripts-dir"),
        pytest.param(Path("notebooks/explore.py"), id="notebooks-dir"),
    ],
)
def test_exempt_paths(path: Path):
    assert _check("import logging\n", path) == []


def test_exempts_generated_files():
    src = "# Code generated by openapi-generator. DO NOT EDIT.\nimport logging\n"
    assert _check(src) == []


def test_unparsable_source_yields_no_diagnostics():
    assert _check("import logging\ndef (:\n") == []


def test_diagnostic_points_at_the_import_column():
    diags = _check("def wire():\n    import logging\n")
    assert (diags[0].line, diags[0].col) == (2, 5)
