from pathlib import Path

import pytest

from sarj_python_lint.rule_base import Diagnostic, RuleExample, Severity
from sarj_python_lint.rules.no_analytical_aggregation_in_postgres_store import (
    NoAnalyticalAggregationInPostgresStore,
)


def _check(source: str, filename: str = "event_store.py") -> list[Diagnostic]:
    return NoAnalyticalAggregationInPostgresStore().check(Path(filename), source)


_PUBLIC_EXAMPLES = NoAnalyticalAggregationInPostgresStore.public_examples()


@pytest.mark.parametrize(
    "example",
    _PUBLIC_EXAMPLES,
    ids=tuple(example.example_id for example in _PUBLIC_EXAMPLES),
)
def test_public_documentation_examples_are_executable(example: RuleExample) -> None:
    focus = example.focus_file
    assert len(_check(focus.source, str(focus.path))) == example.expected_count


@pytest.mark.parametrize(
    "function",
    [
        "STDDEV_POP(latency_ms)",
        "VAR_SAMP(latency_ms)",
        "CORR(duration_ms, cost)",
        "COVAR_POP(duration_ms, cost)",
        "REGR_SLOPE(cost, duration_ms)",
        "PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY latency_ms)",
    ],
)
def test_flags_strong_statistical_postgres_aggregates(function: str) -> None:
    source = f'import psycopg\nQUERY = "SELECT {function} FROM event"\n'  # ruff:ignore[hardcoded-sql-expression] -- synthetic lint-rule fixture
    diagnostics = _check(source)
    assert len(diagnostics) == 1
    assert diagnostics[0].severity is Severity.WARNING


def test_flags_postgres_time_bucketed_rollup() -> None:
    source = """import asyncpg
QUERY = \"SELECT DATE_TRUNC('hour', occurred_at), COUNT(*), AVG(latency_ms) FROM event GROUP BY 1\"
"""
    diagnostics = _check(source)
    assert len(diagnostics) == 1
    assert "time-bucketed GROUP BY" in diagnostics[0].message


@pytest.mark.parametrize(
    "source",
    [
        'import psycopg\nq = "SELECT SUM(amount) FROM ledger WHERE account_id = %s FOR UPDATE"\n',
        'import psycopg\nq = "SELECT MIN(run_at) FROM job WHERE queue = %s"\n',
        'import psycopg\nq = "SELECT MAX(version) FROM migration FOR UPDATE"\n',
        'import psycopg\nq = "SELECT DISTINCT user_id FROM member WHERE org_id = %s"\n',
        'import psycopg\nq = "SELECT JSONB_AGG(child) FROM child WHERE parent_id = %s"\n',
        'import psycopg\nq = "SELECT status, COUNT(*) FROM task GROUP BY status"\n',
        'import psycopg\nq = "UPDATE cache SET count = (SELECT COUNT(*) FROM item)"\n',
    ],
)
def test_allows_operational_or_ambiguous_aggregates(source: str) -> None:
    assert _check(source) == []


@pytest.mark.parametrize(
    "source",
    [
        'import sqlite3\nq = "SELECT PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY x) FROM event"\n',
        'import mysql.connector\nq = "SELECT STDDEV(x) FROM event"\n',
        "q = \"SELECT DATE_TRUNC('day', ts), COUNT(*) FROM event GROUP BY 1\"\n",
    ],
)
def test_requires_positive_postgres_ownership(source: str) -> None:
    assert _check(source) == []


def test_sql_in_docstrings_is_not_executable() -> None:
    source = '''import psycopg

def report() -> None:
    """Never run SELECT STDDEV(latency) FROM event in PostgreSQL."""
'''
    assert _check(source) == []


def test_generated_module_is_excluded() -> None:
    source = """# Code generated by sqlc. DO NOT EDIT.
import psycopg
q = "SELECT STDDEV(latency) FROM event"
"""
    assert _check(source) == []


def test_mixed_backend_module_classifies_each_query() -> None:
    source = """import psycopg
import clickhouse_connect

postgres_query = "SELECT STDDEV(latency) FROM event"
clickhouse_query = "SELECT quantile(0.95)(latency) FROM event"
"""
    diagnostics = _check(source)
    assert len(diagnostics) == 1
    assert diagnostics[0].line == 4


def test_bigquery_query_in_mixed_module_is_excluded() -> None:
    source = """import psycopg
from google.cloud import bigquery
q = "SELECT PERCENTILE_CONT(duration, 0.9) FROM `project.dataset.event`"
"""
    assert _check(source) == []


def test_concatenated_cte_is_detected_once() -> None:
    source = """import psycopg
q = "WITH samples AS (SELECT latency FROM event) " + "SELECT STDDEV(latency) FROM samples"
"""
    assert len(_check(source)) == 1


@pytest.mark.parametrize("filename", ["service.py", "test_event_store.py", "tests/stores/event.py"])
def test_non_store_modules_are_excluded(filename: str) -> None:
    source = 'import psycopg\nq = "SELECT STDDEV(latency) FROM event"\n'
    assert _check(source, filename) == []


def test_parse_failure_returns_no_diagnostics() -> None:
    source = 'import psycopg\nq = "SELECT STDDEV(latency) FROM event"\ndef (:\n'
    assert _check(source) == []


def test_diagnostic_metadata() -> None:
    diagnostics = _check('import psycopg\nq = "SELECT STDDEV(latency) FROM event"\n')
    assert len(diagnostics) == 1
    diagnostic = diagnostics[0]
    assert diagnostic.code == "SARJ020"
    assert diagnostic.path == Path("event_store.py")
    assert (diagnostic.line, diagnostic.col) == (2, 5)
    assert "review its bounds and execution plan" in diagnostic.message
