from __future__ import annotations

from pathlib import Path
import time
from typing import TYPE_CHECKING

import pytest

import sarj_python_lint.__main__ as cli
from sarj_python_lint.rule_base import RuleExample, Severity
from sarj_python_lint.rules.no_duplicate_dunder_all_entry import NoDuplicateDunderAllEntry


if TYPE_CHECKING:
    from sarj_python_lint.rule_base import Diagnostic


_PUBLIC_EXAMPLES = NoDuplicateDunderAllEntry.public_examples()


def _check(source: str, path: str = "diagnostics/__init__.py") -> list[Diagnostic]:
    return NoDuplicateDunderAllEntry().check(Path(path), source)


@pytest.mark.parametrize(
    "declaration",
    [
        '__all__ = ["Diagnostic", "Diagnostic"]',
        '__all__ = ("Diagnostic", "Diagnostic")',
        '__all__: list[str] = ["Diagnostic", "Diagnostic"]',
    ],
)
def test_reports_the_later_exact_duplicate_in_static_export_literals(declaration: str) -> None:
    findings = _check(declaration)

    assert len(findings) == 1
    assert findings[0].code == "SARJ098"
    assert findings[0].severity is Severity.WARNING
    assert findings[0].col > 1
    assert "line 1" in findings[0].message


def test_reports_duplicate_in_regular_module() -> None:
    findings = _check('__all__ = ["parse", "parse"]\n', "src/parsing.py")

    assert len(findings) == 1


def test_later_extension_does_not_erase_literal_duplicate() -> None:
    findings = _check('__all__ = ["A", "A"]\n__all__.append("B")\n')

    assert len(findings) == 1


@pytest.mark.parametrize(
    "example",
    _PUBLIC_EXAMPLES,
    ids=tuple(example.example_id for example in _PUBLIC_EXAMPLES),
)
def test_public_documentation_examples_are_executable(example: RuleExample) -> None:
    focus = example.focus_file

    findings = NoDuplicateDunderAllEntry().check(Path(focus.path), focus.source)

    assert len(findings) == example.expected_count


def test_reports_every_later_duplicate_and_cites_the_first_line() -> None:
    source = """
from .models import AnalysisReport, Diagnostic

__all__ = [
    "AnalysisReport",
    "Diagnostic",
    "AnalysisReport",
    "AnalysisReport",
]
"""

    findings = _check(source)

    assert [finding.line for finding in findings] == [7, 8]
    assert all("line 5" in finding.message for finding in findings)


def test_exact_matching_is_case_sensitive() -> None:
    assert _check('__all__ = ["Diagnostic", "diagnostic"]') == []


def test_pr304_unique_imports_mirrored_in_dunder_all_are_clean() -> None:
    names = [
        "AnalysisReport",
        "CanonicalDiagnostic",
        "DiagnosticCode",
        "DiagnosticLocation",
        "DiagnosticSeverity",
        "JsonDiagnostic",
        "RuleDiagnostic",
        "RuleMetadata",
        "SarifArtifact",
        "SarifDriver",
        "SarifLocation",
        "SarifLog",
        "SarifMessage",
        "SarifPhysicalLocation",
        "SarifRegion",
        "SarifResult",
        "SarifRun",
    ]
    imports = "\n".join(f"from .{name.casefold()} import {name}" for name in names)
    exports = ",\n    ".join(repr(name) for name in names)
    source = f'"""Canonical diagnostics exports."""\n{imports}\n\n__all__ = [\n    {exports},\n]\n'

    assert _check(source) == []


@pytest.mark.parametrize(
    "source",
    [
        "__all__ = exports",
        '__all__ = ["A"] + extras',
        '__all__ = ["A", *extras, "A"]',
        '__all__ = ["A", 1, "A"]',
        '__all__ = ["A"]\n__all__ = ["A"]',
        '__all__ = ["A"]\n__all__ += ["A"]',
        '__all__ = ["A"]\n__all__.append("A")',
        'if enabled:\n    __all__ = ["A", "A"]',
        'def exports():\n    __all__ = ["A", "A"]',
        'class Facade:\n    __all__ = ["A", "A"]',
    ],
)
def test_skips_dynamic_conditional_reassigned_and_mutated_exports(source: str) -> None:
    assert _check(source) == []


def test_lazy_facade_still_reports_a_duplicate_inside_its_static_export_list() -> None:
    source = """
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .service import Controller

_LAZY_IMPORTS = {"Controller": ("service", "Controller")}

__all__ = ["Controller", "Tools", "Controller"]

def __getattr__(name: str):
    return _LAZY_IMPORTS[name]
"""

    findings = _check(source)

    assert len(findings) == 1
    assert "Controller" in findings[0].message


def test_unrelated_module_members_do_not_hide_a_static_duplicate() -> None:
    source = '__all__ = ["A", "A"]\nVERSION = "1"\n\ndef __dir__(): ...\n'

    assert len(_check(source)) == 1


def test_regular_modules_are_checked() -> None:
    source = '__all__ = ["A", "A"]'

    assert len(_check(source, "diagnostics/exports.py")) == 1


def test_generated_and_malformed_sources_are_ignored() -> None:
    generated = '# Generated by schema compiler. Do not edit.\n__all__ = ["A", "A"]\n'

    assert _check(generated) == []
    assert _check('__all__ = ["A",') == []


def test_repeated_checks_are_deterministic() -> None:
    source = '__all__ = ["A", "B", "A", "A"]'
    rule = NoDuplicateDunderAllEntry()

    first = rule.check(Path("pkg/__init__.py"), source)
    second = rule.check(Path("pkg/__init__.py"), source)

    assert first == second
    assert len(second) == 2


def test_large_static_export_surface_remains_linear_enough() -> None:
    entries = [f'"Export{index}"' for index in range(5_000)]
    entries.append('"Export0"')
    source = f"__all__ = [{','.join(entries)}]"

    started = time.perf_counter()
    findings = _check(source)
    elapsed = time.perf_counter() - started

    assert len(findings) == 1
    assert elapsed < 1.0


def test_cli_honors_exact_code_suppression_on_the_duplicate_literal(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    target = tmp_path / "__init__.py"
    target.write_text(
        '__all__ = [\n    "Diagnostic",\n    "Diagnostic",  # sarj-noqa: SARJ098 — compatibility\n]\n',
        encoding="utf-8",
    )
    assert cli.main(["check", "--rule", NoDuplicateDunderAllEntry.id, str(target)]) == 0
    assert not capsys.readouterr().out
