from pathlib import Path
import textwrap
from typing import TYPE_CHECKING

from sarj_python_lint.rules.prefer_match_type_dispatch import PreferMatchTypeDispatch


if TYPE_CHECKING:
    from sarj_python_lint.rule_base import Diagnostic


SRC_PATH = "python/bulbul/models/call_detail.py"


def _check(source: str, path: str = SRC_PATH) -> list[Diagnostic]:
    return PreferMatchTypeDispatch().check(Path(path), textwrap.dedent(source))


# --------------------------------------------------------------------------- #
# Core detection: Hideous parser helper / raise-in-try idiom                 #
# --------------------------------------------------------------------------- #


_HIDEOUS_PARSER_IDIOM = """
def _parse_transferred_at(data: object) -> datetime | None | Unset:
    if data is None:
        return data
    if isinstance(data, Unset):
        return data
    try:
        if not isinstance(data, str):
            raise TypeError()
        transferred_at_type_0 = datetime.fromisoformat(data)
        return transferred_at_type_0
    except (TypeError, ValueError, AttributeError, KeyError):
        pass
    return cast(datetime | None | Unset, data)
"""


def test_flags_hideous_parser_helper():
    diags = _check(_HIDEOUS_PARSER_IDIOM)
    assert len(diags) >= 1
    codes = {d.code for d in diags}
    assert "SARJ080" in codes


def test_flags_control_flow_raise_inside_try():
    source = """
    def parse_item(val):
        try:
            if not isinstance(val, int):
                raise ValueError()
            return val * 2
        except ValueError:
            return 0
    """
    diags = _check(source)
    assert len(diags) == 1
    assert diags[0].code == "SARJ080"
    assert "Control-flow raise in try block" in diags[0].message
    assert diags[0].line == 5


def test_flags_sequential_sentinel_guards():
    source = """
    def _parse_field(val: object):
        if val is None:
            return val
        if isinstance(val, Unset):
            return val
        if isinstance(val, int):
            return str(val)
        return None
    """
    diags = _check(source)
    assert len(diags) == 1
    assert diags[0].code == "SARJ080"
    assert "Sequential sentinel/type guards" in diags[0].message


def test_flags_qualified_attribute_exceptions():
    source = """
    def parse_mod_exc(val):
        try:
            if not isinstance(val, str):
                raise my_module.CustomTypeError()
            return val
        except my_module.CustomTypeError:
            return None
    """
    diags = _check(source)
    assert len(diags) == 1
    assert "raise CustomTypeError()" in diags[0].message


def test_flags_bare_except_block():
    source = """
    def parse_bare(val):
        try:
            if not isinstance(val, str):
                raise Exception()
            return val
        except:
            return None
    """
    diags = _check(source)
    assert len(diags) == 1


def test_skips_inner_function_try_block_from_outer_scope():
    source = """
    def outer():
        try:
            def inner():
                raise ValueError()
            inner()
        except ValueError:
            pass
    """
    assert _check(source) == []


def test_skips_legitimate_raise_not_caught_by_local_try():
    source = """
    def validate(val):
        try:
            if val < 0:
                raise ValueError("Negative value")
            process(val)
        except TypeError:
            pass
    """
    assert _check(source) == []


def test_skips_match_case_idiom():
    source = """
    def parse_clean(data: object):
        match data:
            case None | Unset():
                return data
            case str():
                try:
                    return datetime.fromisoformat(data)
                except ValueError:
                    pass
        return cast(data)
    """
    assert _check(source) == []


def test_skips_generated_source():
    source = """
    # Automatically generated by openapi generator. DO NOT EDIT!
    def _parse_transferred_at(data: object):
        if data is None:
            return data
        if isinstance(data, Unset):
            return data
        try:
            if not isinstance(data, str):
                raise TypeError()
            return datetime.fromisoformat(data)
        except TypeError:
            pass
        return data
    """
    assert _check(source) == []


def test_flags_raised_exception_attribute_no_call():
    source = """
    def parse_item(val):
        try:
            raise builtins.ValueError
        except builtins.ValueError:
            pass
    """
    diags = _check(source)
    assert len(diags) == 1


def test_flags_tuple_exception_handlers():
    source = """
    def parse_item(val):
        try:
            raise TypeError()
        except (ValueError, builtins.TypeError):
            pass
    """
    diags = _check(source)
    assert len(diags) == 1


def test_try_star():
    source = """
    def parse_item(val):
        try:
            raise ValueError()
        except* ValueError:
            pass
    """
    diags = _check(source)
    assert len(diags) == 1


def test_issubclass_and_eq_sequential_guards():
    source = """
    def _parse_field(val: type):
        if issubclass(val, int):
            return val
        if val == float:
            return val
        return None
    """
    diags = _check(source)
    assert len(diags) == 1
    assert "Sequential sentinel" in diags[0].message


def test_nested_try_blocks():
    source = """
    def foo():
        try:
            try:
                raise ValueError()
            except ValueError:
                pass
        except TypeError:
            pass
    """
    diags = _check(source)
    assert len(diags) == 1
