from pathlib import Path
from typing import TYPE_CHECKING

import pytest

from sarj_python_lint.rules.no_generic_single_export_module import NoGenericSingleExportModule


if TYPE_CHECKING:
    from sarj_python_lint.rule_base import Diagnostic, RuleExample


def _check(source: str, path: str) -> list[Diagnostic]:
    return NoGenericSingleExportModule().check(Path(path), source)


_PUBLIC_EXAMPLES = NoGenericSingleExportModule.public_examples()


@pytest.mark.parametrize("example", _PUBLIC_EXAMPLES, ids=tuple(e.example_id for e in _PUBLIC_EXAMPLES))
def test_public_documentation_examples_are_executable(example: RuleExample) -> None:
    focus = example.focus_file
    assert len(_check(focus.source, str(focus.path))) == example.expected_count


def test_role_category_single_class_is_not_a_junk_drawer():
    src = """
class IntegrationProvider: ...
"""
    assert _check(src, path="enums.py") == []


def test_junk_drawer_single_function_flagged():
    src = """
def snake_case_text(value: str) -> str: ...
"""
    diags = _check(src, path="utils.py")
    assert len(diags) == 1
    assert "snake_case_text" in diags[0].message
    assert "responsibility-bearing" in diags[0].message


def test_informative_stem_not_flagged():
    src = """
class InvalidPaginationCursorError(Exception): ...
"""
    assert _check(src, path="pagination.py") == []


def test_informative_stem_predicate_not_flagged():
    src = """
def is_rate_limit_error(exc: Exception) -> bool: ...
"""
    assert _check(src, path="retry_wrapper.py") == []


def test_junk_drawer_multiple_public_defs_out_of_scope():
    src = """
class A: ...

def gc_once() -> None: ...
"""
    assert _check(src, path="utils.py") == []


def test_generic_definition_name_does_not_make_a_junk_drawer_informative():
    src = """
class Utils: ...
"""
    assert len(_check(src, path="utils.py")) == 1


def test_junk_drawer_private_helpers_and_constants_ignored():
    src = """
class Language: ...

def _normalize(x: str) -> str: ...

_CACHE: dict[int, bool] = {}
"""
    diags = _check(src, path="utils.py")
    assert len(diags) == 1
    assert "Language" in diags[0].message


# FP-hardening (famous-repo sweep): a public constant is a public export too.  #


@pytest.mark.parametrize(
    "constant",
    [
        "REPO = 'example/repository'",
        "MAX_RETRIES: int = 3",
        "HISTORY_FILE = 'HISTORY.md'",
        "REPO, TAG = 'example/repository', 'latest'",
    ],
)
def test_public_constant_blocks_the_rename(constant: str):
    src = f"""
{constant}

def run_command(*args: str) -> str: ...
"""
    assert _check(src, path="shared.py") == []


@pytest.mark.parametrize(
    "assignment",
    [
        "logger = get_logger(__name__)",  # lowercase: infrastructure, not API
        "_CACHE: dict[str, int] = {}",  # private
        "__all__ = ['run_command']",  # describes the surface, is not part of it
        "_registry = {}",
    ],
)
def test_non_public_constants_do_not_block_the_rename(assignment: str):
    src = f"""
{assignment}

def run_command(*args: str) -> str: ...
"""
    diags = _check(src, path="shared.py")
    assert len(diags) == 1
    assert "run_command" in diags[0].message


def test_imported_names_do_not_count_as_public_exports():
    src = """
from app.settings import PUBLIC_SETTING

def run_command(*args: str) -> str: ...
"""
    diags = _check(src, path="shared.py")
    assert len(diags) == 1
    assert "run_command" in diags[0].message


@pytest.mark.parametrize(
    ("path", "header"),
    [
        ("utils.py", "# Code generated by protoc. DO NOT EDIT.\n"),
        ("src/generated/utils.py", ""),
    ],
)
def test_generated_modules_are_not_flagged(path: str, header: str):
    assert _check(f"{header}class PublicExport: ...\n", path=path) == []


def test_junk_drawer_zero_public_defs_not_flagged():
    src = """
THRESHOLD = 300
_PATTERN = "x"
"""
    assert _check(src, path="constants.py") == []


def test_init_conftest_and_tests_skipped():
    src = """
class OnlyExport: ...
"""
    assert _check(src, path="__init__.py") == []
    assert _check(src, path="conftest.py") == []
    assert _check(src, path="test_things.py") == []
    assert _check(src, path="pkg/tests/utils.py") == []


@pytest.mark.parametrize(
    "name",
    [
        "HTTPServer",
        "JWTHandler",
        "IVRNavigationTool",
        "OAuthService",
        "SalesforceOAuthService",
        "MultiprocJanitor",
        "SalesforceTokenResponse",
        "MessagingProviderClient",
        "HTTPServerProbe",
        "APIKey",
    ],
)
def test_diagnostic_names_the_definition_without_prescribing_a_filename(name: str):
    src = f"""
class {name}: ...
"""
    diags = _check(src, path="utils.py")
    assert len(diags) == 1
    assert f"`{name}`" in diags[0].message
    assert "rename the file to" not in diags[0].message


def test_oauth_stem_matching_accepted_form_not_flagged():
    src = """
class SalesforceOAuthService: ...
"""
    assert _check(src, path="salesforce_oauth_service.py") == []


@pytest.mark.parametrize(
    "stem",
    [
        "common",
        "helper",
        "helpers",
        "misc",
        "shared",
        "stuff",
        "util",
        "utilities",
        "utility",
        "utils",
    ],
)
def test_every_denylist_stem_fires(stem: str):
    src = """
class DataPipelineRunner: ...
"""
    diags = _check(src, path=f"{stem}.py")
    assert len(diags) == 1
    assert "DataPipelineRunner" in diags[0].message


@pytest.mark.parametrize(
    "stem",
    ["base", "constant", "constants", "core", "enum", "enums", "model", "models", "type", "types"],
)
def test_role_and_category_stems_are_not_junk_drawers(stem: str):
    assert _check("class DataPipelineRunner: ...\n", path=f"{stem}.py") == []


@pytest.mark.parametrize(
    "stem",
    ["typing", "modeling", "baseline", "corelib", "sharing", "commons", "enumerations"],
)
def test_near_miss_non_denylist_stems_not_flagged(stem: str):
    src = """
class DataPipelineRunner: ...
"""
    assert _check(src, path=f"{stem}.py") == []


def test_exactly_two_public_defs_boundary_not_flagged():
    src = """
def first_thing() -> None: ...

def second_thing() -> None: ...
"""
    assert _check(src, path="helpers.py") == []


def test_overloads_are_one_exported_responsibility():
    src = """
from typing import overload

@overload
def parse(value: str) -> str: ...

@overload
def parse(value: bytes) -> bytes: ...

def parse(value: str | bytes) -> str | bytes: ...
"""
    diags = _check(src, path="utilities.py")
    assert len(diags) == 1
    assert "`parse`" in diags[0].message


def test_public_class_and_public_function_mix_not_flagged():
    src = """
class Widget: ...

def build_widget() -> Widget: ...
"""
    assert _check(src, path="models.py") == []


def test_private_only_module_not_flagged():
    src = """
def _internal() -> None: ...

class _Hidden: ...
"""
    assert _check(src, path="util.py") == []


def test_all_declaration_does_not_suppress_fire():
    src = """
__all__ = ["Widget"]


class Widget: ...
"""
    diags = _check(src, path="common.py")
    assert len(diags) == 1
    assert "Widget" in diags[0].message


def test_multi_name_all_blocks_sole_export_advice() -> None:
    src = """
__all__ = ["Widget", "build_widget"]


class Widget: ...
"""
    assert _check(src, path="common.py") == []


@pytest.mark.parametrize(
    "declaration",
    [
        "__all__ = exports()",
        "__all__ = EXPORTED_NAMES",
        "__all__ = ['PublicAlias']",
        "__all__ = []",
        "__all__ = ['Widget']\n__all__.append('Alias')",
        "__all__ = ['Widget']\n__all__ += ['Alias']",
        "if enabled:\n    __all__ = ['Widget']",
        "from exports import names as __all__",
        "def configure(__all__):\n    return __all__",
        "__all__ = ['Widget']\nconsume(__all__)",
        "__all__ = {'Widget'}",
    ],
)
def test_ambiguous_or_mismatched_dunder_all_blocks_surface_advice(declaration: str) -> None:
    source = f"{declaration}\n\nclass Widget: ...\n"
    assert _check(source, path="common.py") == []


@pytest.mark.parametrize(
    "alias",
    [
        "type WidgetId = str",
        "WidgetId: TypeAlias = str",
        "WidgetId: typing.TypeAlias = str",
    ],
)
def test_public_type_alias_blocks_sole_export_advice(alias: str) -> None:
    src = f"{alias}\n\nclass Widget: ...\n"
    assert _check(src, path="helpers.py") == []


def test_private_type_alias_does_not_block_sole_export_advice() -> None:
    src = "type _WidgetId = str\n\nclass Widget: ...\n"
    assert len(_check(src, path="helpers.py")) == 1


def test_async_def_sole_export_flagged():
    src = """
async def fetch_records() -> None: ...
"""
    diags = _check(src, path="helpers.py")
    assert len(diags) == 1
    assert "fetch_records" in diags[0].message


def test_decorated_class_flagged():
    src = """
import functools


@functools.total_ordering
class OrderedWidget: ...
"""
    diags = _check(src, path="utils.py")
    assert len(diags) == 1
    assert "OrderedWidget" in diags[0].message


def test_type_checking_only_export_not_counted():
    src = """
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    class OnlyUnderTypeChecking: ...
"""
    assert _check(src, path="helpers.py") == []


def test_type_checking_plus_one_toplevel_still_single():
    src = """
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    class Shadow: ...


class RealExport: ...
"""
    diags = _check(src, path="helpers.py")
    assert len(diags) == 1
    assert "RealExport" in diags[0].message


@pytest.mark.parametrize("name", ["APIClient", "IOError", "OAuth2Provider", "MyABC", "XMLParser", "SHA256Hash"])
def test_additional_definition_name_shapes(name: str):
    src = f"""
class {name}: ...
"""
    diags = _check(src, path="utils.py")
    assert len(diags) == 1
    assert f"`{name}`" in diags[0].message


def test_graphql_acronym_should_be_single_token():
    src = """
class GraphQLSchema: ...
"""
    diags = _check(src, path="utils.py")
    assert len(diags) == 1
    assert "`GraphQLSchema`" in diags[0].message


def test_grpc_acronym_should_be_single_token():
    src = """
class gRPCServer: ...
"""
    diags = _check(src, path="utils.py")
    assert len(diags) == 1
    assert "`gRPCServer`" in diags[0].message


def test_capitalized_junk_drawer_stem_is_owned_by_filename_case_lint():
    src = """
class DataPipelineRunner: ...
"""
    assert _check(src, path="Utils.py") == []


@pytest.mark.parametrize("path", ["utils.pyi", "utils.txt"])
def test_non_runtime_python_files_are_not_checked(path: str) -> None:
    assert _check("class DataPipelineRunner: ...\n", path=path) == []


@pytest.mark.parametrize(
    "filename",
    [
        "models.py",
        "admin.py",
        "apps.py",
        "views.py",
        "urls.py",
        "forms.py",
        "serializers.py",
        "base.py",
        "settings.py",
        "middleware.py",
        "tasks.py",
        "signals.py",
        "routing.py",
        "__main__.py",
    ],
)
def test_framework_convention_filenames_not_flagged(filename: str):
    src = """
class DataPipelineRunner: ...
"""
    assert _check(src, path=filename) == []


def test_django_models_module_with_single_model_not_flagged():
    src = """
class FlatPage: ...
"""
    assert _check(src, path="contrib/flatpages/models.py") == []


def test_genuine_junk_drawer_still_fires_alongside_allowlist():
    assert len(_check("def do_thing() -> None: ...\n", path="utils.py")) == 1
    assert len(_check("class HelperThing: ...\n", path="helpers.py")) == 1
