from pathlib import Path
from typing import TYPE_CHECKING

import pytest

from sarj_python_lint.rules.prefer_non_nullable_collection import (
    PreferNonNullableCollection,
)


if TYPE_CHECKING:
    from sarj_python_lint.rule_base import Diagnostic


PATH = Path("app/models.py")


def _check(source: str, path: Path = PATH) -> list[Diagnostic]:
    return PreferNonNullableCollection().check(path, source)


@pytest.mark.parametrize(
    "annotation",
    [
        "list[OrganizationId] | None",
        "None | list[OrganizationId]",
        "typing.Optional[list[OrganizationId]]",
        "Optional[List[OrganizationId]]",
        "Union[list[OrganizationId], None]",
        "list[One] | list[Two] | None",
    ],
)
@pytest.mark.parametrize("default", [" = None", "", " = Field(default=None)"])
def test_flags_nullable_list_fields_on_any_class(annotation: str, default: str) -> None:
    source = f"class AnyModel:\n    organization_ids: {annotation}{default}\n"
    diagnostics = _check(source)
    assert len(diagnostics) == 1
    assert diagnostics[0].code == "SARJ082"
    assert diagnostics[0].line == 2

    assert "default_factory=list" in diagnostics[0].message


@pytest.mark.parametrize(
    "declaration",
    [
        "class Response(BaseModel):",
        "class UpdateInput(BaseModel):",
        "@dataclass\nclass Settings:",
        "@define\nclass DomainState:",
        "class PlainTypedClass:",
    ],
)
def test_is_general_across_data_shape_names_and_frameworks(declaration: str) -> None:
    source = f"{declaration}\n    items: list[str] | None = None\n"
    assert len(_check(source)) == 1


@pytest.mark.parametrize(
    "source",
    [
        "class Model:\n    items: list[str] = field(default_factory=list)\n",
        "class Model:\n    items: list[str] = Field(default_factory=list)\n",
        "class Model:\n    items: list[str]\n",
        "class Model:\n    item: str | None = None\n",
        "class Model:\n    value: str | list[str] | None = None\n",
        "def build(items: list[str] | None = None):\n    return items or []\n",
        "items: list[str] | None = None\n",
    ],
)
def test_ignores_non_target_shapes(source: str) -> None:
    assert _check(source) == []


def test_ignores_tests_and_generated_files() -> None:
    source = "class Model:\n    items: list[str] | None = None\n"
    assert _check(source, Path("tests/test_models.py")) == []
    assert _check(source, Path("src/generated/models.py")) == []
    assert _check(source, Path("src/vendor/models.py")) == []
    assert _check("# Generated by tool\n" + source) == []
