from pathlib import Path
from typing import TYPE_CHECKING

import pytest

from sarj_python_lint.rule_base import Severity
from sarj_python_lint.rules.no_apirouter_root_trailing_slash import NoApirouterRootTrailingSlash


if TYPE_CHECKING:
    from sarj_python_lint.rule_base import Diagnostic, RuleExample


def _check(source: str, path: str = "app/api.py") -> list[Diagnostic]:
    return NoApirouterRootTrailingSlash().check(Path(path), source)


_PUBLIC_EXAMPLES = NoApirouterRootTrailingSlash.public_examples()


@pytest.mark.parametrize("example", _PUBLIC_EXAMPLES, ids=tuple(e.example_id for e in _PUBLIC_EXAMPLES))
def test_public_documentation_examples_are_executable(example: RuleExample) -> None:
    focus = example.focus_file
    assert len(_check(focus.source, str(focus.path))) == example.expected_count


@pytest.mark.parametrize(
    "source",
    [
        "from fastapi import APIRouter\nrouter = APIRouter()\n@router.get('/')\ndef f(): ...\n",
        "from fastapi import APIRouter as Router\nr = Router()\n@r.post(path='/')\ndef f(): ...\n",
        "import fastapi as fa\nr = fa.APIRouter()\n@r.put('/')\ndef f(): ...\n",
        "from fastapi import APIRouter\nr = APIRouter()\nalias = r\n@alias.patch('/')\ndef f(): ...\n",
        "from fastapi import APIRouter\nr = APIRouter()\nget = r.get\n@get('/')\ndef f(): ...\n",
        "from fastapi import APIRouter\nr = APIRouter(include_in_schema=False)\n@r.delete('/')\ndef f(): ...\n",
        "from fastapi import APIRouter\nr = APIRouter()\n@r.api_route('/', methods=['GET', 'POST'])\ndef f(): ...\n",
        "from fastapi import APIRouter\nclass Routes:\n def build(self):\n  self.router = APIRouter()\n  @self.router.get('/')\n  def f(): ...\n  return self.router\n",
    ],
)
def test_flags_resolved_apirouter_root_paths(source: str) -> None:
    findings = _check(source)

    assert len(findings) == 1
    assert findings[0].code == "SARJ405"
    assert findings[0].severity is Severity.WARNING
    assert "empty string" in findings[0].message


@pytest.mark.parametrize(
    "source",
    [
        "from fastapi import FastAPI\napp = FastAPI()\n@app.get('/')\ndef f(): ...\n",
        "import fastapi as fa\napp = fa.FastAPI()\n@app.post('/')\ndef f(): ...\n",
        "from fastapi import FastAPI\napp = FastAPI()\nalias = app\n@alias.get('/')\ndef f(): ...\n",
        "from fastapi import APIRouter\nr = APIRouter()\n@r.get('')\ndef f(): ...\n",
        "from fastapi import APIRouter\nr = APIRouter()\n@r.get('/items')\ndef f(): ...\n",
        "from fastapi import APIRouter\nr = APIRouter()\npath = '/'\n@r.get(path)\ndef f(): ...\n",
        "class Router:\n def get(self, path): return lambda f: f\nr = Router()\n@r.get('/')\ndef f(): ...\n",
        "from fastapi import APIRouter\nr = APIRouter()\nr = object()\n@r.get('/')\ndef f(): ...\n",
    ],
)
def test_keeps_application_roots_and_unproven_or_canonical_router_paths(source: str) -> None:
    assert _check(source) == []


def test_stacked_root_decorators_report_each_declared_operation() -> None:
    source = "from fastapi import APIRouter\nrouter = APIRouter()\n@router.get('/')\n@router.post('/')\ndef f(): ...\n"

    findings = _check(source)

    assert [(finding.line, finding.col) for finding in findings] == [(3, 2), (4, 2)]


def test_api_route_with_multiple_methods_reports_once() -> None:
    source = (
        "from fastapi import APIRouter\nrouter = APIRouter()\n"
        "@router.api_route('/', methods=['GET', 'POST'])\ndef f(): ...\n"
    )

    assert len(_check(source)) == 1


def test_generated_tests_and_malformed_sources_are_ignored() -> None:
    source = "from fastapi import APIRouter\nr = APIRouter()\n@r.get('/')\ndef f(): ...\n"
    generated = f"# Code generated by schema compiler. DO NOT EDIT.\n{source}"

    assert _check(source, "tests/api.py") == []
    assert _check(source, "app/test_api.py") == []
    assert _check(source, "docs_src/tutorial/api.py") == []
    assert _check(generated) == []
    assert _check("from fastapi import APIRouter\nr = (") == []
