from pathlib import Path

import pytest

from sarj_python_lint.rule_base import Diagnostic, RuleExample, Severity, is_suppressed
from sarj_python_lint.rules.no_offset_pagination import NoOffsetPagination


def _check(source: str, path: str = "call_store.py") -> list[Diagnostic]:
    return NoOffsetPagination().check(Path(path), source)


_PUBLIC_EXAMPLES = NoOffsetPagination.public_examples()


@pytest.mark.parametrize("example", _PUBLIC_EXAMPLES, ids=tuple(e.example_id for e in _PUBLIC_EXAMPLES))
def test_public_documentation_examples_are_executable(example: RuleExample) -> None:
    focus = example.focus_file
    assert len(_check(focus.source, str(focus.path))) == example.expected_count


@pytest.mark.parametrize(
    "marker",
    ["%s", "%(offset)s", "?", "?2", ":offset", "@offset", "$2"],
)
def test_flags_dynamic_offset_markers_in_full_select(marker: str) -> None:
    source = f'q = "SELECT id FROM call ORDER BY id LIMIT 50 OFFSET {marker}"\n'  # ruff:ignore[hardcoded-sql-expression] -- synthetic lint-rule fixture
    diagnostics = _check(source)
    assert len(diagnostics) == 1
    assert diagnostics[0].severity is Severity.WARNING


def test_flags_dynamic_fstring_offset() -> None:
    source = 'q = f"SELECT id FROM call ORDER BY id LIMIT {limit} OFFSET {offset}"\n'
    assert len(_check(source)) == 1


def test_flags_mysql_comma_offset() -> None:
    source = 'q = "SELECT id FROM call ORDER BY id LIMIT %s, %s"\n'
    assert len(_check(source)) == 1


def test_flags_sql_standard_offset_fetch() -> None:
    source = 'q = "SELECT id FROM call ORDER BY id OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY"\n'
    assert len(_check(source)) == 1


def test_concatenated_full_query_is_detected_once() -> None:
    source = 'q = "SELECT id FROM call ORDER BY id " + "LIMIT %s OFFSET %s"\n'
    assert len(_check(source)) == 1


@pytest.mark.parametrize(
    "source",
    [
        'q = "SELECT id FROM call ORDER BY id LIMIT 10 OFFSET 0"\n',
        'q = "SELECT id FROM call ORDER BY id LIMIT 1 OFFSET 1"\n',
        'q = "SELECT id FROM call ORDER BY id LIMIT 50 OFFSET 1000"\n',
        'fragment = "LIMIT %s OFFSET %s"\n',
        'message = "retry operation at OFFSET %s"\n',
        "q = \"SELECT note FROM call WHERE note = 'OFFSET %s'\"\n",
        'q = "SELECT `OFFSET %s` FROM call"\n',
        'q = "SELECT [OFFSET %s] FROM call"\n',
        'q = "SELECT id FROM call # LIMIT %s OFFSET %s"\n',
        'q = "SELECT id FROM call -- LIMIT %s OFFSET %s"\n',
        'q = "SELECT id FROM call /* OFFSET %s */"\n',
        'q = "SELECT item FROM UNNEST(items) WITH OFFSET AS item_offset"\n',
    ],
)
def test_avoids_nonpagination_and_fixed_ordinal_shapes(source: str) -> None:
    assert _check(source) == []


def test_sql_bearing_function_docstring_is_ignored() -> None:
    source = '''def paginate() -> None:
    """Run SELECT id FROM call LIMIT %s OFFSET %s for old clients."""
'''
    assert _check(source) == []


@pytest.mark.parametrize(
    ("path", "source"),
    [
        ("generated/call_store.py", 'q = "SELECT id FROM call LIMIT %s OFFSET %s"\n'),
        (
            "call_store.py",
            '# Generated by sqlc. DO NOT EDIT.\nq = "SELECT id FROM call LIMIT %s OFFSET %s"\n',
        ),
        ("migrations/backfill_store.py", 'q = "SELECT id FROM call LIMIT %s OFFSET %s"\n'),
        ("tests/stores/call.py", 'q = "SELECT id FROM call LIMIT %s OFFSET %s"\n'),
        ("service.py", 'q = "SELECT id FROM call LIMIT %s OFFSET %s"\n'),
    ],
)
def test_excluded_paths(path: str, source: str) -> None:
    assert _check(source, path) == []


def test_bounded_static_catalog_can_be_suppressed_with_a_reason() -> None:
    source = (
        'q = "SELECT code FROM country ORDER BY code LIMIT %s OFFSET %s" '
        "# sarj-noqa: SARJ025 -- bounded ISO country catalog\n"
    )
    lines = source.splitlines()
    kept = [item for item in _check(source) if not is_suppressed(lines, item.line, item.code)]
    assert kept == []


def test_unrelated_offset_method_is_not_an_embedded_sql_finding() -> None:
    assert _check("canvas.offset(distance)\n") == []


def test_multiple_queries_are_sorted_by_location() -> None:
    source = 'a = "SELECT id FROM call LIMIT %s OFFSET %s"\nb = "SELECT id FROM task LIMIT :limit OFFSET :offset"\n'
    diagnostics = _check(source)
    assert [(item.line, item.col) for item in diagnostics] == [(1, 5), (2, 5)]


def test_diagnostic_metadata() -> None:
    diagnostics = _check('q = "SELECT id FROM call LIMIT %s OFFSET %s"\n')
    assert len(diagnostics) == 1
    diagnostic = diagnostics[0]
    assert diagnostic.code == "SARJ025"
    assert diagnostic.path == Path("call_store.py")
    assert "stable unique keyset cursor" in diagnostic.message


@pytest.mark.parametrize("source", ["", "# comment\n", "def (:\n"])
def test_boundary_inputs_return_no_diagnostics(source: str) -> None:
    assert _check(source) == []
