from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

import pytest

from sarj_python_lint.rule_base import is_suppressed
from sarj_python_lint.rules.no_gen_random_uuid_in_sql import NoGenRandomUuidInSql


if TYPE_CHECKING:
    from sarj_python_lint.rule_base import Diagnostic


def _check(source: str, path: Path = Path("svc/app/store.py")) -> list[Diagnostic]:
    return NoGenRandomUuidInSql().check(path, source)


@pytest.mark.parametrize(
    "source",
    [
        pytest.param(
            'SQL = "CREATE TABLE call (id UUID PRIMARY KEY DEFAULT gen_random_uuid())"\n',
            id="create-table-default",
        ),
        pytest.param(
            'SQL = "ALTER TABLE call ALTER COLUMN id SET DEFAULT gen_random_uuid()"\n',
            id="alter-table-default",
        ),
        pytest.param(
            'SQL = "INSERT INTO call (id) VALUES (gen_random_uuid())"\n',
            id="insert-values",
        ),
        pytest.param(
            'SQL = "SELECT gen_random_uuid() AS id"\n',
            id="select",
        ),
        pytest.param(
            'SQL = "UPDATE call SET id = gen_random_uuid()"\n',
            id="update",
        ),
        pytest.param(
            'SQL = "create table t (id uuid default GEN_RANDOM_UUID())"\n',
            id="case-insensitive",
        ),
        pytest.param(
            'SQL = "CREATE TABLE t (id UUID DEFAULT gen_random_uuid ())"\n',
            id="space-before-paren",
        ),
        pytest.param(
            'SQL = """\nCREATE TABLE t (\n  id UUID DEFAULT gen_random_uuid()\n)\n"""\n',
            id="triple-quoted",
        ),
        pytest.param(
            'SQL = ("CREATE TABLE t (id UUID DEFAULT "\n       "gen_random_uuid())")\n',
            id="implicitly-concatenated",
        ),
    ],
)
def test_flags_embedded_sql(source: str):
    assert len(_check(source)) == 1


def test_message_names_uuidv7():
    diags = _check('SQL = "CREATE TABLE t (id UUID DEFAULT gen_random_uuid())"\n')
    assert "uuidv7()" in diags[0].message
    assert diags[0].code == "SARJ053"


@pytest.mark.parametrize(
    "source",
    [
        pytest.param(
            'SQL = "CREATE TABLE t (id UUID PRIMARY KEY DEFAULT uuidv7())"\n',
            id="already-uuidv7",
        ),
        pytest.param(
            'MSG = "gen_random_uuid() is banned; use uuidv7()"\n',
            id="prose-naming-the-function",
        ),
        pytest.param(
            'def f():\n    """Do not use gen_random_uuid() here."""\n',
            id="docstring-naming-the-function",
        ),
        pytest.param(
            'SQL = "SELECT id FROM t -- was DEFAULT gen_random_uuid()"\n',
            id="inside-a-sql-comment",
        ),
        pytest.param(
            "SQL = \"SELECT * FROM t WHERE note = 'DEFAULT gen_random_uuid()'\"\n",
            id="inside-a-quoted-sql-value",
        ),
        pytest.param(
            'SQL = "SELECT id FROM t /* DEFAULT gen_random_uuid() */"\n',
            id="inside-a-block-comment",
        ),
        pytest.param(
            'NAME = "gen_random_uuid_helper"\n',
            id="identifier-prefix-only",
        ),
    ],
)
def test_allows(source: str):
    assert _check(source) == []


def test_flags_once_per_literal_not_once_per_occurrence():
    src = 'SQL = "CREATE TABLE t (a UUID DEFAULT gen_random_uuid(), b UUID DEFAULT gen_random_uuid())"\n'
    assert len(_check(src)) == 1


def test_flags_each_offending_literal():
    src = 'A = "CREATE TABLE a (id UUID DEFAULT gen_random_uuid())"\nB = "CREATE TABLE b (id UUID DEFAULT gen_random_uuid())"\n'
    assert [d.line for d in _check(src)] == [1, 2]


def test_exempts_generated_files():
    src = '# @generated by protoc. DO NOT EDIT.\nSQL = "CREATE TABLE t (id UUID DEFAULT gen_random_uuid())"\n'
    assert _check(src) == []


def test_unparsable_source_yields_no_diagnostics():
    assert _check('SQL = "CREATE TABLE t (id UUID DEFAULT gen_random_uuid())"\ndef (:\n') == []


UUIDV7_CONSTRUCTIONS = [
    (
        'SQL = """\n'
        "CREATE OR REPLACE FUNCTION uuid_generate_v7(p_timestamp timestamptz)\n"
        "RETURNS uuid AS $$ BEGIN\n"
        "  buffer := unix_time_ms || substring(uuid_send(gen_random_uuid()) FROM 1 FOR 5);\n"
        "  RETURN encode(buffer, 'hex')::uuid;\n"
        'END $$;\n"""\n'
    ),
    'SQL = "SELECT set_byte(uuid_send(gen_random_uuid()), 6, 112)"\n',
    'SQL = "CREATE TABLE t (id uuid DEFAULT uuidv7())"\n',
]


@pytest.mark.parametrize("source", UUIDV7_CONSTRUCTIONS)
def test_sql_building_a_uuidv7_is_not_the_defect(source: str):
    assert _check(source) == []


@pytest.mark.parametrize(
    "source",
    [
        'SQL = "CREATE FUNCTION uuid_generate_v7() RETURNS uuid AS $$ SELECT gen_random_uuid() $$"\n',
        'SQL = "CREATE FUNCTION uuidv7() RETURNS uuid AS $$ SELECT gen_random_uuid() $$"\n',
        'SQL = "CREATE FUNCTION uuid_v7() RETURNS uuid AS $$ SELECT gen_random_uuid() $$"\n',
        'SQL = "CREATE FUNCTION uuid7() RETURNS uuid AS $$ SELECT gen_random_uuid() $$"\n',
    ],
)
def test_allows_common_names_for_a_uuidv7_definition(source: str):
    assert _check(source) == []


@pytest.mark.parametrize(
    "expression",
    [
        "uuid_send(gen_random_uuid())",
        "substring(gen_random_uuid()::text FROM 1 FOR 12)",
        "set_byte(gen_random_uuid()::bytea, 6, 112)",
        "get_byte(gen_random_uuid()::bytea, 0)",
        "int8send(gen_random_uuid()::text::bigint)",
        "encode(gen_random_uuid()::bytea, 'hex')",
        "overlay(gen_random_uuid()::text PLACING '7' FROM 13)",
    ],
)
def test_allows_uuidv7_building_blocks(expression: str):
    assert _check(f'SQL = "SELECT {expression}"\n') == []


def test_a_plain_v4_default_still_fires_in_a_migration():
    src = 'op.execute("ALTER TABLE t ALTER COLUMN id SET DEFAULT gen_random_uuid()")\n'
    assert len(_check(src)) == 1


def test_applies_to_test_files_too():
    src = 'SQL = "CREATE TABLE t (id UUID DEFAULT gen_random_uuid())"\n'
    assert len(_check(src, Path("svc/tests/test_store.py"))) == 1


def test_sarj053_noqa_suppresses_a_deliberate_legacy_default():
    src = 'SQL = "ALTER TABLE t ALTER id SET DEFAULT gen_random_uuid()"  # sarj-noqa: SARJ053 — legacy\n'
    diags = _check(src)
    assert len(diags) == 1
    assert is_suppressed(src.splitlines(), diags[0].line, diags[0].code)


def test_noqa_for_another_rule_does_not_suppress_sarj053():
    src = 'SQL = "ALTER TABLE t ALTER id SET DEFAULT gen_random_uuid()"  # sarj-noqa: SARJ052\n'
    diags = _check(src)
    assert len(diags) == 1
    assert not is_suppressed(src.splitlines(), diags[0].line, diags[0].code)


@pytest.mark.parametrize(
    "source",
    [
        pytest.param(
            'SQL = "CREATE TABLE t (id uuid DEFAULT gen_random_\\x75uid())"\n',
            id="hex-escape-inside-the-identifier",
        ),
        pytest.param(
            'SQL = "CREATE TABLE t (id uuid DEFAULT gen_random_\\u0075uid())"\n',
            id="unicode-escape",
        ),
        pytest.param(
            'SQL = "CREATE TABLE t (id uuid DEFAULT gen_random_\\165uid())"\n',
            id="octal-escape",
        ),
        pytest.param(
            'SQL = ("CREATE TABLE t (id uuid DEFAULT gen_ran" "dom_uuid())")\n',
            id="implicit-concat-SPLITTING-the-identifier",
        ),
    ],
)
def test_escaped_and_split_identifiers_still_fire(source: str):
    assert len(_check(source)) == 1


@pytest.mark.parametrize(
    "source",
    [
        pytest.param(
            'SQL = "CREATE TABLE t (id uuid DEFAULT GEN_RANDOM_UUID())"\n',
            id="upper-case-sql",
        ),
        pytest.param(
            'SQL = "CREATE TABLE t (id uuid DEFAULT Gen_Random_UUID())"\n',
            id="mixed-case-sql",
        ),
        pytest.param(
            'SQL = "CREATE TABLE t (id uuid DEFAULT gen_random_uuid /* c */ ())"\n',
            id="comment-between-name-and-paren",
        ),
        pytest.param(
            'SQL = ("CREATE TABLE t (id uuid DEFAULT " "gen_random_uuid())")\n',
            id="implicit-concat-identifier-intact",
        ),
    ],
)
def test_matchable_shapes_fire(source: str):
    assert len(_check(source)) == 1


def test_file_that_never_names_the_function_is_silent():
    assert _check('SQL = "CREATE TABLE t (id uuid DEFAULT uuidv7())"\n') == []
