from pathlib import Path
from textwrap import dedent

import pytest

from sarj_python_lint.rule_base import RuleExample, Severity
from sarj_python_lint.rules.prefer_immutable_module_constant import PreferImmutableModuleConstant
from tests.illustrative_examples import illustrative_examples


@pytest.mark.parametrize(
    ("source", "replacement"),
    [
        pytest.param("VALUES = [1, 2, 3]", "tuple", id="list"),
        pytest.param("KINDS = {'a', 'b'}", "frozenset", id="set"),
        pytest.param("VALUES = list(runtime_values)", "tuple", id="populated-list-constructor"),
        pytest.param("KINDS = set(runtime_values)", "frozenset", id="populated-set-constructor"),
        pytest.param("LABELS = dict(runtime_items)", "immutable mapping", id="populated-dict-constructor"),
        pytest.param("_VALUES = [1, 2, 3]", "tuple", id="private-constant"),
        pytest.param("X = [1, 2, 3]", "tuple", id="single-letter-constant"),
        pytest.param("VALUES = [runtime_value]", "tuple", id="dynamic-list-element"),
        pytest.param("LABELS = {'value': runtime_value}", "immutable mapping", id="dynamic-dict-value"),
        pytest.param("VALUES = [value for value in runtime_values]", "tuple", id="list-comprehension"),
        pytest.param("KINDS = {value for value in runtime_values}", "frozenset", id="set-comprehension"),
        pytest.param(
            "LABELS = {value.code: value for value in runtime_values}",
            "immutable mapping",
            id="dict-comprehension",
        ),
        pytest.param("VALUES = [*runtime_values]", "tuple", id="dynamic-list-spread"),
        pytest.param("VALUES = [1]\ndef mutate(VALUES):\n    VALUES.append(1)", "tuple", id="parameter-shadow"),
        pytest.param("VALUES = [1]\ndef mutate():\n    VALUES = []\n    VALUES.append(1)", "tuple", id="local-shadow"),
        pytest.param("VALUES = [1]\ntuple({'values': VALUES})", "tuple", id="nested-inside-safe-call"),
        pytest.param(
            "VALUES = [1]\nconsume([value for value in VALUES])",
            "tuple",
            id="comprehension-copies-elements",
        ),
        pytest.param("VALUES = [1]\nconsume({'first': VALUES[0]})", "tuple", id="element-only-escapes"),
        pytest.param("KINDS = {'a'}\nconsume(*KINDS)", "frozenset", id="star-expands-elements"),
    ],
)
def test_warns_for_literal_mutable_module_constants(source: str, replacement: str) -> None:
    findings = PreferImmutableModuleConstant().check(Path("service.py"), source)

    assert len(findings) == 1
    assert findings[0].code == "SARJ096"
    assert findings[0].severity is Severity.ERROR
    assert replacement in findings[0].message


@illustrative_examples(PreferImmutableModuleConstant)
def test_public_documentation_examples_are_executable(example: RuleExample) -> None:
    focus = example.focus_file

    findings = PreferImmutableModuleConstant().check(Path(focus.path), focus.source)

    assert len(findings) == example.expected_count


@pytest.mark.parametrize(
    "source",
    [
        "VALUES = (1, 2, 3)",
        "KINDS = frozenset({'a', 'b'})",
        "VALUES = []",
        "LABELS: dict = {}",
        "VALUES = list()",
        "LABELS = dict()",
        "KINDS = set()",
        "labels = {'a': 'A'}",
        "__all__ = ['public']",
        "VALUES = {'a'}\nVALUES.add('b')",
        "VALUES = {'a'}\nVALUES.difference_update({'b'})",
        "VALUES = [1]\nVALUES += [2]",
        "VALUES = [1]\nVALUES = [2]",
        "LABELS = {}\nLABELS['a'] = 'A'",
        "VALUES = [1]\ndef reset():\n    global VALUES\n    VALUES = []",
        "LABELS = {'a': []}\nLABELS['a'].append('A')",
        "LABELS = {'a': {'b': 'B'}}\nLABELS['a']['b'] = 'C'",
        "BG_TASKS = set()\nservice = Service(bg_tasks=BG_TASKS)",
        "BG_TASKS = {'task'}\ndef install(task):\n    task.add_done_callback(BG_TASKS.discard)",
        "VALUES = (value for value in runtime_values)",
        "VALUES = [value for value in runtime_values]\nVALUES.append(extra)",
        "KINDS = {value for value in runtime_values}\nKINDS.update(extra)",
        "LABELS = {value.code: value for value in runtime_values}\nconsume(LABELS)",
    ],
)
def test_ignores_immutable_dynamic_nonconstant_and_intentionally_mutated_values(source: str) -> None:
    assert PreferImmutableModuleConstant().check(Path("service.py"), source) == []


def test_ignores_test_and_generated_files() -> None:
    source = dedent("""\
        # generated by schema compiler
        VALUES = [1, 2, 3]
        """)

    rule = PreferImmutableModuleConstant()
    assert rule.check(Path("tests/test_service.py"), "VALUES = [1, 2, 3]") == []
    assert rule.check(Path("generated.py"), source) == []


@pytest.mark.parametrize("source", ["A = B = []\nA.append(1)", "A = B = {}\nconsume(B)", "A = B = set()"])
def test_chained_mutable_assignments_are_conservatively_exempt(source: str) -> None:
    assert PreferImmutableModuleConstant().check(Path("service.py"), source) == []


@pytest.mark.parametrize(
    "source",
    [
        "OPTIONS = {'enabled': True}\nService(config={'options': OPTIONS})",
        "OPTIONS = {'enabled': True}\n@route(config={'options': OPTIONS})\ndef handler(): pass",
        "OPTIONS = {'enabled': True}\n@register(config={'options': OPTIONS})\nclass Handler: pass",
        "OPTIONS = {'enabled': True}\ndef handler(config=Factory({'options': OPTIONS})): pass",
        "OPTIONS = {'enabled': True}\nhandler = lambda config=Factory({'options': OPTIONS}): config",
        "VALUES = [1]\nconsume({'outer': [{'values': VALUES}]})",
        "KINDS = {'a'}\nconsume(*(KINDS,))",
        (
            "OPTIONS = {'enabled': True}\n"
            "def build():\n"
            "    turn_handling = {'preemptive': OPTIONS}\n"
            "    kwargs = {'turn_handling': turn_handling}\n"
            "    return Service(**kwargs)"
        ),
    ],
)
def test_ignores_constants_nested_in_literal_containers_passed_to_unknown_calls(source: str) -> None:
    assert PreferImmutableModuleConstant().check(Path("service.py"), source) == []


def test_ignores_mapping_embedded_in_a_module_document_passed_to_an_unknown_call() -> None:
    source = "TOOL_SCHEMA = {'type': 'object'}\nSCENARIO = {'tools': [TOOL_SCHEMA]}\njson.dump(SCENARIO, stream)\n"

    assert PreferImmutableModuleConstant().check(Path("service.py"), source) == []


def test_local_shadow_inside_escaping_container_does_not_hide_module_finding() -> None:
    source = "OPTIONS = {'module': True}\ndef build():\n    OPTIONS = {'local': True}\n    consume({'x': OPTIONS})"

    findings = PreferImmutableModuleConstant().check(Path("service.py"), source)

    assert len(findings) == 1
    assert findings[0].line == 1


@pytest.mark.parametrize(
    "compound",
    [
        "if enabled:\n        VALUES = []",
        "for _ in items:\n        VALUES = []",
        "try:\n        VALUES = []\n    except RuntimeError:\n        pass",
        "match value:\n        case 1:\n            VALUES = []",
        "with manager():\n        VALUES = []",
    ],
)
def test_nested_local_shadow_does_not_hide_module_finding(compound: str) -> None:
    source = f"VALUES = [1]\ndef mutate(enabled, items, value):\n    {compound}\n    VALUES.append(2)"

    findings = PreferImmutableModuleConstant().check(Path("service.py"), source)

    assert len(findings) == 1
    assert findings[0].line == 1


@pytest.mark.parametrize(
    "source",
    [
        "list = factory\nVALUES = list(runtime_values)",
        "from custom import dict\nVALUES = dict(runtime_values)",
        "def set(*values): return values\nVALUES = set(runtime_values)",
    ],
)
def test_ignores_constructor_calls_when_builtin_name_is_shadowed(source: str) -> None:
    assert PreferImmutableModuleConstant().check(Path("service.py"), source) == []
