from pathlib import Path
from typing import TYPE_CHECKING

import pytest

from sarj_python_lint.rules.duplicate_test_body import DuplicateTestBody


if TYPE_CHECKING:
    from sarj_python_lint.rule_base import Diagnostic


TEST_PATH = "python/bulbul/tests/unit/test_permissions.py"


def _check(source: str, path: str = TEST_PATH) -> list[Diagnostic]:
    return DuplicateTestBody().check(Path(path), source)


# The canonical shape: same three statements, different locals, one literal
# apart. `u`/`allowed` vs `user`/`ok` is the naming difference the local-name
# canonicalization exists to see through.
_COPY_PASTED_PAIR = """
def test_admin_can_delete():
    u = make_user(role="admin")
    allowed = can_delete(u)
    assert allowed is True


def test_editor_can_delete():
    user = make_user(role="editor")
    ok = can_delete(user)
    assert ok is True
"""


# --------------------------------------------------------------------------- #
# Path gating and generated sources.                                           #
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("path", ["test_x.py", "x_test.py", "a/tests/thing.py", "conftest.py"])
def test_fires_in_test_paths(path: str):
    assert len(_check(_COPY_PASTED_PAIR, path)) == 1


@pytest.mark.parametrize("path", ["src/service.py", "a/testing/thing.py", "app/models.py"])
def test_skips_non_test_paths(path: str):
    assert _check(_COPY_PASTED_PAIR, path) == []


def test_generated_module_is_exempt():
    src = "# Code generated by protoc. DO NOT EDIT.\n" + _COPY_PASTED_PAIR
    assert _check(src) == []


def test_the_same_module_without_the_generated_header_still_fires():
    assert len(_check("# Hand-written table-driven checks.\n" + _COPY_PASTED_PAIR)) == 1


# --------------------------------------------------------------------------- #
# Positive: what the rule is for.                                              #
# --------------------------------------------------------------------------- #


def test_flags_the_copy_and_not_the_original():
    [diag] = _check(_COPY_PASTED_PAIR)
    assert diag.line == 8
    assert diag.col == 1
    assert diag.code == "SARJ058"


def test_flags_every_member_after_the_first():
    src = """
def test_one():
    x = build("a")
    y = run(x)
    assert y is True


def test_two():
    x = build("b")
    y = run(x)
    assert y is True


def test_three():
    x = build("c")
    y = run(x)
    assert y is True
"""
    assert [d.line for d in _check(src)] == [8, 14]


def test_flags_byte_for_byte_duplicates():
    src = """
def test_one():
    thing = build()
    thing.run()
    assert thing.done


def test_two():
    thing = build()
    thing.run()
    assert thing.done
"""
    [diag] = _check(src)
    assert "byte-for-byte identical body" in diag.message


def test_flags_methods_of_a_pytest_style_class():
    src = """
class TestDeletion:
    def test_admin(self):
        u = make_user(role="admin")
        allowed = can_delete(u)
        assert allowed is True

    def test_editor(self):
        u = make_user(role="editor")
        allowed = can_delete(u)
        assert allowed is True
"""
    assert len(_check(src)) == 1


def test_flags_async_pairs():
    src = """
async def test_one():
    store = await open_store("a")
    got = await store.get(1)
    assert got is None


async def test_two():
    store = await open_store("b")
    got = await store.get(1)
    assert got is None
"""
    assert len(_check(src)) == 1


def test_docstrings_do_not_hide_a_duplicate():
    # Different prose, identical behaviour — still one test run twice.
    src = '''
def test_one():
    """Admins may delete."""
    u = make_user(role="admin")
    allowed = can_delete(u)
    assert allowed is True


def test_two():
    """Editors may delete, which is a different scenario entirely."""
    u = make_user(role="editor")
    allowed = can_delete(u)
    assert allowed is True
'''
    assert len(_check(src)) == 1


# --------------------------------------------------------------------------- #
# The message: it must name the original and the literals that differ.         #
# --------------------------------------------------------------------------- #


def test_message_names_both_tests_and_the_originals_line():
    [diag] = _check(_COPY_PASTED_PAIR)
    assert "`test_editor_can_delete`" in diag.message
    assert "`test_admin_can_delete`" in diag.message
    assert f"{TEST_PATH}:2" in diag.message


def test_message_names_the_differing_literal():
    [diag] = _check(_COPY_PASTED_PAIR)
    assert "'admin' -> 'editor'" in diag.message


def test_message_offers_parametrize_with_ids_and_cross_references_sarj042():
    [diag] = _check(_COPY_PASTED_PAIR)
    assert "parametrize" in diag.message
    assert "ids=" in diag.message
    assert "SARJ042" in diag.message


def test_message_summarizes_when_many_literals_differ():
    src = """
def test_one():
    payload = build(1, 2, 3, 4)
    result = run(payload)
    assert result == 5


def test_two():
    payload = build(6, 7, 8, 9)
    result = run(payload)
    assert result == 10
"""
    [diag] = _check(src)
    assert "and 2 more literals" in diag.message


def test_message_elides_a_very_long_literal():
    long_a = "a" * 80
    long_b = "b" * 80
    src = f"""
def test_one():
    payload = build("{long_a}")
    result = run(payload)
    assert result


def test_two():
    payload = build("{long_b}")
    result = run(payload)
    assert result
"""
    [diag] = _check(src)
    assert long_a not in diag.message
    assert "..." in diag.message


# --------------------------------------------------------------------------- #
# FP guard: unittest.TestCase. pytest cannot parametrize those, so the fix the  #
# message asks for does not exist there. 458 of django's 458 hits.              #
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    "base",
    ["TestCase", "SimpleTestCase", "TransactionTestCase", "unittest.TestCase", "ChoiceWidgetTest", "WidgetTests"],
)
def test_methods_of_a_test_case_subclass_are_exempt(base: str):
    src = f"""
class DeletionTests({base}):
    def test_admin(self):
        u = make_user(role="admin")
        allowed = can_delete(u)
        assert allowed is True

    def test_editor(self):
        u = make_user(role="editor")
        allowed = can_delete(u)
        assert allowed is True
"""
    assert _check(src) == []


def test_the_same_class_without_a_test_case_base_still_fires():
    src = """
class TestDeletion(DeletionFixtures):
    def test_admin(self):
        u = make_user(role="admin")
        allowed = can_delete(u)
        assert allowed is True

    def test_editor(self):
        u = make_user(role="editor")
        allowed = can_delete(u)
        assert allowed is True
"""
    assert len(_check(src)) == 1


def test_a_nested_class_inherits_the_test_case_exemption():
    src = """
class OuterTests(TestCase):
    class Inner:
        def test_admin(self):
            u = make_user(role="admin")
            allowed = can_delete(u)
            assert allowed is True

        def test_editor(self):
            u = make_user(role="editor")
            allowed = can_delete(u)
            assert allowed is True
"""
    assert _check(src) == []


@pytest.mark.parametrize(
    "call",
    ["self.assertEqual(result, 2)", "self.subTest(result)", "self.skipTest('nope')", "self.fail('boom')"],
)
def test_bodies_calling_a_test_case_only_api_are_exempt(call: str):
    # django's mixin classes carry test methods with no TestCase base at all;
    # the `self.` API is what identifies them.
    src = f"""
class TestHashedFiles:
    def test_one(self):
        value = compute(1)
        result = normalize(value)
        {call}

    def test_two(self):
        value = compute(2)
        result = normalize(value)
        {call}
"""
    assert _check(src) == []


def test_the_same_mixin_using_a_plain_assert_still_fires():
    src = """
class TestHashedFiles:
    def test_one(self):
        value = compute(1)
        result = normalize(value)
        assert result == 2

    def test_two(self):
        value = compute(2)
        result = normalize(value)
        assert result == 2
"""
    assert len(_check(src)) == 1


def test_a_plain_helper_attribute_on_self_is_not_a_unittest_api():
    src = """
class TestDeletion:
    def test_one(self):
        value = self.compute(1)
        result = normalize(value)
        assert result == 2

    def test_two(self):
        value = self.compute(2)
        result = normalize(value)
        assert result == 2
"""
    assert len(_check(src)) == 1


# --------------------------------------------------------------------------- #
# FP guard: identity lives outside the body — container, decorators,            #
# async-ness, and the parameter list.                                          #
# --------------------------------------------------------------------------- #


def test_identical_bodies_in_different_classes_are_exempt():
    src = """
class TestSqlite:
    def test_roundtrip(self):
        row = store.insert({"a": 1})
        got = store.get(row.id)
        assert got == row


class TestPostgres:
    def test_roundtrip(self):
        row = store.insert({"a": 1})
        got = store.get(row.id)
        assert got == row
"""
    assert _check(src) == []


def test_a_module_level_test_and_a_method_are_not_compared():
    src = """
def test_roundtrip():
    row = store.insert({"a": 1})
    got = store.get(row.id)
    assert got == row


class TestThing:
    def test_roundtrip(self):
        row = store.insert({"a": 1})
        got = store.get(row.id)
        assert got == row
"""
    assert _check(src) == []


def test_moving_both_copies_into_one_class_fires():
    src = """
class TestThing:
    def test_roundtrip_a(self):
        row = store.insert({"a": 1})
        got = store.get(row.id)
        assert got == row

    def test_roundtrip_b(self):
        row = store.insert({"a": 2})
        got = store.get(row.id)
        assert got == row
"""
    assert len(_check(src)) == 1


@pytest.mark.parametrize(
    ("first", "second"),
    [
        ('@pytest.mark.xfail(reason="ipv6 unsupported")', '@pytest.mark.xfail(reason="ipv4 only")'),
        ('@pytest.mark.skipif(sys.platform == "win32")', '@pytest.mark.skipif(sys.platform == "darwin")'),
        ("@override_settings(USE_TZ=True)", "@override_settings(USE_TZ=False)"),
        ("@pytest.mark.asyncio", "@pytest.mark.trio"),
        ("@pytest.mark.slow", ""),
    ],
    ids=["xfail-reason", "skipif-condition", "settings-value", "different-marker", "marker-vs-none"],
)
def test_tests_whose_decorators_differ_are_exempt(first: str, second: str):
    src = f"""
import pytest

{first}
def test_one():
    value = compute(1)
    result = normalize(value)
    assert result == 2

{second}
def test_two():
    value = compute(1)
    result = normalize(value)
    assert result == 2
"""
    assert _check(src) == []


def test_the_same_decorator_on_both_still_fires():
    src = """
import pytest

@pytest.mark.xfail(reason="ipv6 unsupported")
def test_one():
    value = compute(1)
    result = normalize(value)
    assert result == 2

@pytest.mark.xfail(reason="ipv6 unsupported")
def test_two():
    value = compute(2)
    result = normalize(value)
    assert result == 2
"""
    assert len(_check(src)) == 1


def test_a_sync_and_async_parity_pair_is_exempt():
    src = """
def test_get():
    client = make_client()
    response = client.get("/x")
    assert response.ok


async def test_get_async():
    client = make_client()
    response = client.get("/x")
    assert response.ok
"""
    assert _check(src) == []


def test_two_async_tests_still_fire():
    src = """
async def test_get_a():
    client = make_client()
    response = client.get("/a")
    assert response.ok


async def test_get_b():
    client = make_client()
    response = client.get("/b")
    assert response.ok
"""
    assert len(_check(src)) == 1


def test_tests_taking_different_fixtures_are_exempt():
    src = """
def test_one(client):
    response = client.get("/x")
    body = response.json()
    assert body == {}


def test_two(async_client):
    response = async_client.get("/x")
    body = response.json()
    assert body == {}
"""
    assert _check(src) == []


def test_a_fixture_renamed_only_in_the_body_still_differs():
    # The parameter names are identity, so declaring the same fixture and using
    # it identically is what re-groups the two.
    src = """
def test_one(client):
    response = client.get("/x")
    body = response.json()
    assert body == {}


def test_two(client):
    response = client.get("/y")
    body = response.json()
    assert body == {}
"""
    assert len(_check(src)) == 1


def test_a_method_taking_an_extra_fixture_is_a_different_test():
    src = """
class TestThing:
    def test_one(self):
        value = compute(1)
        result = normalize(value)
        assert result

    def test_two(self, freezer):
        value = compute(2)
        result = normalize(value)
        assert result
"""
    assert _check(src) == []


# --------------------------------------------------------------------------- #
# FP guard: only literals and locally-bound names are erased. Everything that   #
# names *what* is under test survives normalization.                            #
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    ("first", "second"),
    [
        ("normalize_phone(value)", "normalize_email(value)"),
        ("value.status_code", "value.status"),
        ("build(role=value)", "build(kind=value)"),
        ("build(CANONICAL, value)", "build(LEGACY, value)"),
        ("value + 1", "value - 1"),
        ("Phone(value)", "Email(value)"),
    ],
    ids=["called-function", "attribute", "keyword-name", "module-constant", "operator", "class"],
)
def test_a_difference_that_is_not_a_literal_is_not_a_duplicate(first: str, second: str):
    src = f"""
def test_one():
    value = load(1)
    result = {first}
    assert result


def test_two():
    value = load(1)
    result = {second}
    assert result
"""
    assert _check(src) == []


def test_a_pure_literal_difference_is_a_duplicate():
    src = """
def test_one():
    value = load(1)
    result = normalize_phone(value)
    assert result


def test_two():
    value = load(2)
    result = normalize_phone(value)
    assert result
"""
    assert len(_check(src)) == 1


def test_renaming_locals_does_not_hide_a_duplicate():
    src = """
def test_one():
    escaped = escape(["a", "b"])
    embedded = loads(escaped)
    assert embedded == ["a", "b"]


def test_two():
    result = escape(["a", "b"])
    reconstructed = loads(result)
    assert reconstructed == ["a", "b"]
"""
    assert len(_check(src)) == 1


def test_locals_bound_in_a_different_order_are_a_different_shape():
    src = """
def test_one():
    first = load(1)
    second = load(2)
    assert combine(first, second)


def test_two():
    first = load(1)
    second = load(2)
    assert combine(second, first)
"""
    assert _check(src) == []


@pytest.mark.parametrize(
    "binding",
    ["for item in rows:\n        assert item", "with open_file() as item:\n        assert item"],
    ids=["for-target", "with-as"],
)
def test_names_bound_by_a_statement_are_canonicalized_too(binding: str):
    src = f"""
def test_one():
    rows = load(1)
    {binding}


def test_two():
    rows = load(2)
    {binding.replace("item", "row")}
"""
    assert len(_check(src)) == 1


# --------------------------------------------------------------------------- #
# FP guard: short bodies. Two three-line tests of the same helper are alike by  #
# construction, and grouping them measures nothing.                            #
# --------------------------------------------------------------------------- #


def test_a_two_statement_body_is_not_evidence():
    src = """
def test_one():
    result = normalize("a")
    assert result == "A"


def test_two():
    result = normalize("b")
    assert result == "B"
"""
    assert _check(src) == []


def test_a_three_statement_body_is():
    src = """
def test_one():
    value = load("a")
    result = normalize(value)
    assert result == "A"


def test_two():
    value = load("b")
    result = normalize(value)
    assert result == "B"
"""
    assert len(_check(src)) == 1


def test_statements_nested_in_a_block_count_toward_the_floor():
    src = """
def test_one():
    with client("a") as c:
        result = c.get("/x")
        assert result.ok


def test_two():
    with client("b") as c:
        result = c.get("/x")
        assert result.ok
"""
    assert len(_check(src)) == 1


def test_the_docstring_does_not_count_toward_the_floor():
    src = '''
def test_one():
    """Explain at length what is going on here."""
    result = normalize("a")
    assert result == "A"


def test_two():
    """Explain at length what is going on there."""
    result = normalize("b")
    assert result == "B"
'''
    assert _check(src) == []


# --------------------------------------------------------------------------- #
# Collection: pytest only collects module-level functions and class methods.    #
# --------------------------------------------------------------------------- #


def test_a_test_named_function_nested_in_a_helper_is_not_collected():
    src = """
def test_alpha():
    value = setup(1)
    result = run(value)
    assert result


def make_callback():
    def test_alpha():
        value = setup(1)
        result = run(value)
        assert result

    return test_alpha
"""
    assert _check(src) == []


def test_helpers_that_are_not_named_test_are_ignored():
    src = """
def check_one():
    value = setup(1)
    result = run(value)
    assert result


def check_two():
    value = setup(2)
    result = run(value)
    assert result
"""
    assert _check(src) == []


def test_a_fixture_sharing_a_body_with_a_test_is_ignored():
    src = """
import pytest

@pytest.fixture
def prepared():
    value = setup(1)
    result = run(value)
    return result


def test_alpha():
    value = setup(1)
    result = run(value)
    assert result
"""
    assert _check(src) == []


# --------------------------------------------------------------------------- #
# Edge cases.                                                                  #
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize("source", ["", "  \n\n ", "# comment\n"])
def test_empty_source_is_clean(source: str):
    assert _check(source) == []


def test_syntax_error_returns_no_diagnostics():
    assert _check("def test_x(:\n    thing()\n") == []


def test_a_module_with_one_test_is_clean():
    src = """
def test_only():
    value = load(1)
    result = normalize(value)
    assert result
"""
    assert _check(src) == []


def test_diagnostics_are_sorted_by_position():
    src = """
class TestB:
    def test_one(self):
        value = load(1)
        result = normalize(value)
        assert result

    def test_two(self):
        value = load(2)
        result = normalize(value)
        assert result


def test_alpha():
    row = fetch(1)
    parsed = parse(row)
    assert parsed


def test_beta():
    row = fetch(2)
    parsed = parse(row)
    assert parsed
"""
    diags = _check(src)
    assert len(diags) == 2
    assert [d.line for d in diags] == sorted(d.line for d in diags)


def test_two_independent_groups_in_one_module():
    src = """
def test_a_one():
    value = load(1)
    result = normalize(value)
    assert result


def test_a_two():
    value = load(2)
    result = normalize(value)
    assert result


def test_b_one():
    row = fetch(1)
    parsed = parse(row)
    assert parsed


def test_b_two():
    row = fetch(2)
    parsed = parse(row)
    assert parsed
"""
    assert len(_check(src)) == 2


def test_a_literal_of_a_different_type_counts_as_a_difference():
    src = """
def test_one():
    value = load(1)
    result = normalize(value, True)
    assert result


def test_two():
    value = load(1)
    result = normalize(value, 1)
    assert result
"""
    [diag] = _check(src)
    assert "True -> 1" in diag.message
