from pathlib import Path
import textwrap
from typing import TYPE_CHECKING

import pytest

from sarj_python_lint.rules.prefer_match_type_dispatch import PreferMatchTypeDispatch


if TYPE_CHECKING:
    from sarj_python_lint.rule_base import Diagnostic


SRC_PATH = "python/bulbul/models/call_detail.py"


def _check(source: str, path: str = SRC_PATH) -> list[Diagnostic]:
    return PreferMatchTypeDispatch().check(Path(path), textwrap.dedent(source))


# --------------------------------------------------------------------------- #
# Core detection: Hideous parser helper / raise-in-try idiom                 #
# --------------------------------------------------------------------------- #


_HIDEOUS_PARSER_IDIOM = """
def _parse_transferred_at(data: object) -> datetime | None | Unset:
    if data is None:
        return data
    if isinstance(data, Unset):
        return data
    try:
        if not isinstance(data, str):
            raise TypeError()
        transferred_at_type_0 = datetime.fromisoformat(data)
        return transferred_at_type_0
    except (TypeError, ValueError, AttributeError, KeyError):
        pass
    return cast(datetime | None | Unset, data)
"""


def test_flags_hideous_parser_helper():
    diags = _check(_HIDEOUS_PARSER_IDIOM)
    assert len(diags) >= 1
    codes = {d.code for d in diags}
    assert "SARJ080" in codes


def test_flags_sequential_sentinel_guards():
    source = """
    def _parse_field(val: object):
        if val is None:
            return val
        if isinstance(val, Unset):
            return val
        if isinstance(val, int):
            return str(val)
        return None
    """
    diags = _check(source)
    assert len(diags) == 1
    assert diags[0].code == "SARJ080"
    assert "Sequential sentinel/type guards" in diags[0].message


def test_skips_match_case_idiom():
    source = """
    def parse_clean(data: object):
        match data:
            case None | Unset():
                return data
            case str():
                try:
                    return datetime.fromisoformat(data)
                except ValueError:
                    pass
        return cast(data)
    """
    assert _check(source) == []


def test_skips_generated_source():
    source = """
    # Automatically generated by openapi generator. DO NOT EDIT!
    def _parse_transferred_at(data: object):
        if data is None:
            return data
        if isinstance(data, Unset):
            return data
        try:
            if not isinstance(data, str):
                raise TypeError()
            return datetime.fromisoformat(data)
        except TypeError:
            pass
        return data
    """
    assert _check(source) == []


def test_issubclass_and_eq_sequential_guards():
    source = """
    def _parse_field(val: type):
        if issubclass(val, int):
            return val
        if val == float:
            return val
        return None
    """
    diags = _check(source)
    assert len(diags) == 1
    assert "Sequential sentinel" in diags[0].message


# --------------------------------------------------------------------------- #
# Deliberately NOT flagged: raise-as-goto inside a try                        #
# --------------------------------------------------------------------------- #
#
# This rule used to carry a second detector for `raise` inside a `try` whose own
# `except` catches it. It was removed: ruff's TRY301 (`raise-within-try`) reports
# the same defect at the same line AND column, and `ruff.strict.toml` selects
# `ALL` without ignoring `TRY`, so it is live in every consumer. Across 21
# corpora the arm produced 1,756 findings, 1,649 of them (93.9%) already flagged
# by TRY301.
#
# These are the exact shapes the deleted tests asserted. They must now stay
# silent HERE while remaining ruff's job; if a future change re-adds the
# detector, these fail and the double-reporting is caught before it ships.


@pytest.mark.parametrize(
    "source",
    [
        pytest.param(
            """
            def parse_item(val):
                try:
                    if not isinstance(val, int):
                        raise ValueError()
                    return val * 2
                except ValueError:
                    return 0
            """,
            id="plain-raise-caught-locally",
        ),
        pytest.param(
            """
            def parse_item(val):
                try:
                    raise errors.ValidationError()
                except errors.ValidationError:
                    return 0
            """,
            id="qualified-attribute-exception",
        ),
        pytest.param(
            """
            def parse_item(val):
                try:
                    raise ValueError()
                except:
                    return 0
            """,
            id="bare-except",
        ),
        pytest.param(
            """
            def parse_item(val):
                try:
                    raise ValueError
                except (TypeError, ValueError):
                    return 0
            """,
            id="tuple-handler-no-call",
        ),
        pytest.param(
            """
            def parse_item(val):
                try:
                    raise ValueError()
                except* ValueError:
                    return 0
            """,
            id="try-star",
        ),
    ],
)
def test_raise_within_try_is_left_to_ruff_try301(source: str):
    assert _check(source) == []
