from pathlib import Path
from typing import TYPE_CHECKING

import pytest

from sarj_python_lint.rules.redundant_docstring import RedundantDocstring


if TYPE_CHECKING:
    from sarj_python_lint.rule_base import Diagnostic


def _check(source: str) -> list[Diagnostic]:
    return RedundantDocstring().check(Path("<t>.py"), source)


def _fn(signature: str, docstring: str) -> list[Diagnostic]:
    """Wrap a signature and docstring in a function with a real body.

    Returns:
        The diagnostics from checking the wrapped source.

    """
    return _check(f'def {signature}:\n    """{docstring}"""\n    return None\n')


RESTATEMENTS = [
    ("get_profile_by_national_id(national_id: str)", "Get profile by national ID."),
    ("create_version_tag(rl_version: str)", "Create a version tag."),
    ("update_message(task_id: str, message: Message)", "Update task message."),
    ("list_by_organization(org_id: str)", "List by organization."),
    ("_refresh_ttl(key: str)", "Refresh TTL on a key."),
    ("log_tts_generation(text: str)", "Log TTS generation."),
    ("test_verify_otp_invalid_token(client: TestClient)", "Test verifying OTP with invalid token."),
]


@pytest.mark.parametrize(("signature", "docstring"), RESTATEMENTS)
def test_flags_name_restating_docstring(signature: str, docstring: str):
    diags = _fn(signature, docstring)
    assert len(diags) == 1
    assert diags[0].code == "SARJ050"
    assert (diags[0].line, diags[0].col) == (2, 5)


def test_one_novel_word_keeps_the_docstring():
    assert _fn("update_message(task_id: str)", "Update the task message, clobbering any draft.") == []


def test_negation_counts_as_content():
    # `not` is a stopword for the comment rules and deliberately NOT one here:
    # contradicting the obvious reading of a name is the most useful thing a
    # docstring can do.
    assert _fn("close_stream(stream: Stream)", "Close the stream. Does NOT close the socket.") == []


def test_class_name_counts_towards_the_signature():
    src = 'class TaskStore:\n    def create(self, task: Task):\n        """Create a task."""\n        return None\n'
    assert len(_check(src)) == 1


def test_annotation_tokens_count_towards_the_signature():
    assert len(_fn("build(spec: InstructionSpec) -> Instructions", "Build instructions from the spec.")) == 1


# --- exemptions ---------------------------------------------------------------


@pytest.mark.parametrize(
    "docstring",
    [
        "Get a task by ID.\\n\\n    Raises:\\n        KeyError: when absent.",
        "Get a task by ID. See https://example.com/tasks.",
        "Get a task by ID within 30 seconds.",
        "Get a task by ID. Should return 401 with an invalid token.",
        "Get a task by ID (RFC 7231).",
        "Get a task by ID.\\n\\n    >>> get_task('a')",
        "Get a task by ID — never on the write path.",
        "Get a task by ID, because the cache is authoritative.",
    ],
)
def test_docstrings_carrying_value_are_kept(docstring: str):
    body = docstring.replace("\\n", "\n")
    assert _check(f'def get_task(task_id: str):\n    """{body}"""\n    return None\n') == []


def test_function_tool_docstring_is_a_prompt():
    # The docstring is shipped to the model as the tool description; deleting it
    # changes what the agent does at runtime.
    src = 'from x import function_tool\n\n@function_tool\ndef get_balance(account_id: str):\n    """Get the balance for an account."""\n    return None\n'
    assert _check(src) == []


@pytest.mark.parametrize("decorator", ["@click.command()", "@app.command()", "@cli.group()", "@mcp.tool()"])
def test_cli_and_tool_decorators_are_exempt(decorator: str):
    src = f'{decorator}\ndef create_tag(tag: str):\n    """Create a tag."""\n    return None\n'
    assert _check(src) == []


def test_stub_whose_body_is_the_docstring_is_exempt():
    # "Delete the whole docstring" would leave an empty suite.
    src = 'class Guard(Protocol):\n    def check(self, content: str) -> bool:\n        """Check the content."""\n'
    assert _check(src) == []


def test_generated_file_is_skipped():
    src = '# Code generated by openapi-generator. DO NOT EDIT.\ndef get_task(task_id: str):\n    """Get a task."""\n    return None\n'
    assert _check(src) == []


def test_function_without_a_docstring_is_ignored():
    assert _check("def get_task(task_id: str):\n    return None\n") == []


def test_module_and_class_docstrings_are_out_of_scope():
    src = '"""Task store."""\n\n\nclass TaskStore:\n    """Task store."""\n\n    x = 1\n'
    assert _check(src) == []


def test_unparseable_source_returns_nothing():
    assert _check("def (:\n") == []


def test_nested_function_is_checked():
    src = 'def outer():\n    def get_task(task_id: str):\n        """Get a task."""\n        return None\n    return get_task\n'
    assert len(_check(src)) == 1


def test_fastapi_route_docstring_is_the_openapi_description():
    # A first-party `@router.post("/desk/create-ticket")` handler — the text is what
    # an API consumer reads in the generated schema.
    src = (
        '@router.post("/desk/create-ticket")\n'
        "async def create_ticket(request: CreateTicketRequest):\n"
        '    """Create a ticket."""\n'
        "    return None\n"
    )
    assert _check(src) == []
