from pathlib import Path

import pytest

from sarj_python_lint.rules._paths import (
    is_generated,
    is_generated_path,
    is_generated_source,
    is_test_path,
    is_test_support_path,
)
from sarj_python_lint.rules.prefer_match_type_dispatch import PreferMatchTypeDispatch


# A synthetic model in the shape openapi-python-client emits for a nullable field: sentinel guards, then a `raise` inside a `try` whose handler catches it.
_UNMARKED_GENERATED_SDK_SOURCE = '''\
from typing import Any, TypeVar, Union, cast

from attrs import define as _attrs_define

from ..types import UNSET, Unset

T = TypeVar("T", bound="WidgetRow")


@_attrs_define
class WidgetRow:
    """
    Attributes:
        created_at (Union[None, Unset, datetime.datetime]):
    """

    def _parse_created_at(data: object) -> Union[None, Unset, str]:
        if data is None:
            return data
        if isinstance(data, Unset):
            return data
        try:
            if not isinstance(data, str):
                raise TypeError()
            return data
        except:  # noqa: E722
            pass
        return cast(Union[None, Unset, str], data)
'''


@pytest.mark.parametrize(
    "header",
    [
        "# Code generated by protoc-gen-go. DO NOT EDIT.",
        "# @generated",
        "# This file was automatically generated.",
        "# autogenerated",
    ],
)
def test_is_generated_source_reads_the_header(header: str) -> None:
    assert is_generated_source(f"{header}\nx = 1\n")


def test_is_generated_source_misses_a_banner_less_generator() -> None:
    # The gap this module's path half exists to close, pinned so a future
    # widening of the header regex does not quietly make the path check dead
    # code without anyone noticing the coverage moved.
    assert not is_generated_source(_UNMARKED_GENERATED_SDK_SOURCE)


@pytest.mark.parametrize(
    "source",
    [
        'warning = "do not edit this value in place"\nx = 1\n',
        'message = "responses are generated by the model"\nx = 1\n',
        '"""Responses are generated by the model at runtime."""\nx = 1\n',
        "# This token is generated by the API at runtime.\nx = 1\n",
        "# Generated by Claude\n# old = build()\nx = 1\n",
        "# Generated by ChatGPT\n# old = build()\nx = 1\n",
        "# Generated with ChatGPT\n# old = build()\nx = 1\n",
        "# @generated with Claude\n# old = build()\nx = 1\n",
        "# Generated by OpenAI\n# old = build()\nx = 1\n",
        "# Generated by GitHub Copilot\n# old = build()\nx = 1\n",
        "# Generated by GPT-4o\n# old = build()\nx = 1\n",
        "# Generated using ChatGPT\n# DO NOT EDIT\nx = 1\n",
        "# Generated via GPT4\n# DO NOT EDIT\nx = 1\n",
        "# Generated using Chat-GPT 4\n# DO NOT EDIT\nx = 1\n",
        "# Generated by Claude\n# DO NOT EDIT\n# old = build()\nx = 1\n",
        "# Autogenerated IDs must remain stable.\nx = 1\n",
        'FIXTURE = """\n# Code generated by protoc. DO NOT EDIT.\n"""\nx = 1\n',
    ],
)
def test_is_generated_source_rejects_authored_prose_and_ai_attribution(source: str) -> None:
    assert not is_generated_source(source)


def test_deterministic_generator_evidence_wins_over_separate_ai_documentation() -> None:
    source = "# Code generated by protoc. DO NOT EDIT.\n# Documentation authored with Claude.\nx = 1\n"
    assert is_generated_source(source)


def test_late_malformed_token_does_not_erase_a_generated_header() -> None:
    assert is_generated_source('# @generated\nx = """unterminated\n')


@pytest.mark.parametrize(
    "path",
    [
        "src/generated/models.py",
        "src/vendor/httpx_shim.py",
        "src/vendored/httpx_shim.py",
        "src/GENERATED/models.py",
        ".venv/lib/python3.14/site-packages/httpx/client.py",
        "venv/lib/python3.14/site-packages/pydantic/main.py",
        "build/lib/python3.14/site-packages/vendorlib/client.py",
    ],
)
def test_is_generated_path_flags_generated_directory_names(path: str) -> None:
    assert is_generated_path(Path(path))


@pytest.mark.parametrize(
    "path",
    ["app/services/billing.py", "generator.py", "src/generators/registry.py"],
)
def test_is_generated_path_leaves_hand_written_trees_alone(path: str) -> None:
    assert not is_generated_path(Path(path))


@pytest.mark.parametrize(
    "marker",
    [
        ".openapi-generator-ignore",
        ".swagger-codegen-ignore",
        "codegen.config.yml",
        "openapi-python-client.yaml",
        "buf.gen.yaml",
    ],
)
def test_a_codegen_marker_makes_the_subtree_generated(tmp_path: Path, marker: str) -> None:
    root = tmp_path / "api-client"
    emitted = root / "api_client" / "models"
    emitted.mkdir(parents=True)
    (root / marker).write_text("")
    target = emitted / "widget_row.py"
    target.write_text("")

    assert is_generated_path(target)


def test_the_generator_script_next_to_its_config_stays_linted(tmp_path: Path) -> None:
    # A generator's driver script is hand-written and sits beside its config;
    # exempting the whole tree would drop its findings (12, in the corpus this
    # was measured on) along with the generated package's noise.
    root = tmp_path / "api-client"
    (root / "api_client").mkdir(parents=True)
    (root / "codegen.config.yml").write_text("")
    generator = root / "generate.py"
    generator.write_text("")

    assert not is_generated_path(generator)


def test_the_ancestor_walk_stops_at_the_repository_root(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    (repo / ".git").mkdir(parents=True)
    (tmp_path / "codegen.config.yml").write_text("")
    target = repo / "app" / "service.py"
    target.parent.mkdir(parents=True)
    target.write_text("")

    assert not is_generated_path(target)


def test_a_codegen_config_at_the_repository_root_does_not_exempt_the_repository(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    (repo / ".git").mkdir(parents=True)
    (repo / "codegen.yml").write_text("")
    target = repo / "app" / "service.py"
    target.parent.mkdir(parents=True)
    target.write_text("")

    assert not is_generated_path(target)


def test_is_generated_unions_both_halves() -> None:
    assert is_generated(Path("app/service.py"), "# @generated\n")
    assert is_generated(Path("src/generated/models.py"), "x = 1\n")
    assert not is_generated(Path("app/service.py"), "x = 1\n")


def test_generated_sdk_output_is_exempt_from_match_dispatch(tmp_path: Path) -> None:
    # End-to-end: the raise-in-try arm of SARJ080 fires on this source at any
    # ordinary path, and 314 of its 334 findings over two first-party corpora
    # came from exactly this openapi-python-client shape.
    root = tmp_path / "api-client"
    emitted = root / "api_client" / "models"
    emitted.mkdir(parents=True)
    (root / "codegen.config.yml").write_text("")
    target = emitted / "widget_row.py"
    target.write_text(_UNMARKED_GENERATED_SDK_SOURCE)

    rule = PreferMatchTypeDispatch()
    assert rule.check(Path("app/parsers.py"), _UNMARKED_GENERATED_SDK_SOURCE)
    assert rule.check(target, _UNMARKED_GENERATED_SDK_SOURCE) == []


def test_is_test_path_covers_the_usual_shapes() -> None:
    assert is_test_path(Path("app/conftest.py"))
    assert is_test_path(Path("app/test_service.py"))
    assert is_test_path(Path("app/service_test.py"))
    assert is_test_path(Path("app/tests/helpers.py"))
    assert is_test_path(Path("app/integration_tests/kafka/helpers.py"))
    assert not is_test_path(Path("app/service.py"))


@pytest.mark.parametrize(
    "path",
    ["python/common/testing/builders.py", "python/common/fakes.py", "service/mocks/api.py", "app/user_stub.py"],
)
def test_is_test_support_path_matches_helper_trees_and_stems(path: str) -> None:
    assert is_test_support_path(Path(path))


@pytest.mark.parametrize("path", ["python/common/logging.py", "python/testing_utils_prod.py", "app/service.py"])
def test_is_test_support_path_leaves_production_modules_alone(path: str) -> None:
    assert not is_test_support_path(Path(path))
