from pathlib import Path

from sarj_python_lint.rule_base import Severity
from sarj_python_lint.rules.discourage_nullable_constructor_parameters import DiscourageNullableConstructorParameters


def _check(source: str, path: str = "app/service.py") -> list[int]:
    return [finding.line for finding in DiscourageNullableConstructorParameters().check(Path(path), source)]


def test_warns_for_nullable_defaulted_constructor_parameters() -> None:
    source = (
        "class Service:\n"
        "    def __init__(self, publisher: Publisher | None = None, *, store: Store | None = None) -> None:\n"
        "        self.publisher = publisher\n"
    )
    findings = DiscourageNullableConstructorParameters().check(Path("app/service.py"), source)

    assert [finding.code for finding in findings] == ["SARJ468", "SARJ468"]
    assert all(finding.severity is Severity.WARNING for finding in findings)


def test_required_nullable_dependency_warns() -> None:
    assert _check("class Service:\n    def __init__(self, publisher: Publisher | None) -> None: ...\n") == [2]


def test_non_nullable_defaults_and_regular_methods_are_allowed() -> None:
    assert (
        _check(
            "class Service:\n"
            "    def __init__(self, *, retries: int = 3) -> None: ...\n"
            "    def run(self, publisher: Publisher | None = None) -> None: ...\n"
        )
        == []
    )


def test_nested_union_and_positional_only_parameters_warn_once() -> None:
    source = (
        "class Service:\n"
        "    def __init__(self, publisher: Publisher | OtherPublisher | None, /, *, "
        "store: Store | None) -> None: ...\n"
    )
    assert _check(source) == [2, 2]


def test_nullable_return_type_and_unannotated_parameter_are_allowed() -> None:
    assert _check("class Service:\n    def __init__(self, publisher) -> Publisher | None: ...\n") == []


def test_nested_nullable_value_does_not_make_parameter_nullable() -> None:
    assert (
        _check("class Service:\n    def __init__(self, publishers: list[Publisher | None] | tuple[str]) -> None: ...\n")
        == []
    )


def test_skips_tests_and_generated_code() -> None:
    source = "class Service:\n    def __init__(self, publisher: Publisher | None = None) -> None: ...\n"
    assert _check(source, "tests/test_service.py") == []
    assert _check(f"# Generated by tool\n{source}") == []
