"""Shared file-scope predicates for the file-scope-gated rules."""

from __future__ import annotations

from functools import lru_cache
import re
from typing import TYPE_CHECKING


if TYPE_CHECKING:
    from pathlib import Path


_TEST_DIR_NAMES = frozenset({"tests", "test"})

# `auto-?generated` misses "automatically generated", which is the phrase
# @generated tooling, protoc and OpenAPI generators emit most often.
_GENERATED_RE = re.compile(
    r"auto(?:-|matically )?generated|generated by|do not edit|@generated",
    re.IGNORECASE,
)

_GENERATED_HEADER_LINES = 5

_GENERATED_DIR_NAMES = frozenset({"generated", "vendor", "vendored"})

# Marker files identify generator roots whose banner-less output cannot self-identify as generated.
_CODEGEN_MARKER_NAMES = (
    ".openapi-generator",
    ".openapi-generator-ignore",
    ".swagger-codegen-ignore",
    "openapi-python-client.yml",
    "openapi-python-client.yaml",
    "codegen.yml",
    "codegen.yaml",
    "codegen.config.yml",
    "codegen.config.yaml",
    "buf.gen.yaml",
    "buf.gen.yml",
)

# Ancestor walks stop at the repository root.
_REPO_ROOT_MARKERS = (".git",)

# Bound ancestor scans so pathological paths or symlink loops cannot stall linting.
_MAX_ANCESTOR_DEPTH = 40


def is_generated_source(source: str) -> bool:
    """Report whether `source` self-identifies as generated code."""
    head = source.splitlines()[:_GENERATED_HEADER_LINES]
    return any(_GENERATED_RE.search(line) for line in head)


@lru_cache(maxsize=256)
def _is_codegen_root(directory: Path) -> bool:
    """Report whether `directory` holds a code generator's config or ignore file."""
    return any((directory / name).exists() for name in _CODEGEN_MARKER_NAMES)


@lru_cache(maxsize=256)
def _is_repo_root(directory: Path) -> bool:
    """Report whether `directory` is a repository root."""
    return any((directory / name).exists() for name in _REPO_ROOT_MARKERS)


def is_generated_path(path: Path) -> bool:
    """Report whether `path` sits in a tree of generated or vendored code."""
    if any(part.lower() in _GENERATED_DIR_NAMES for part in path.parts):
        return True
    for depth, ancestor in enumerate(path.parents):
        if depth >= _MAX_ANCESTOR_DEPTH:
            break
        # `depth == 0` is the file's own directory: a generator config sitting
        # next to the file makes the file the generator, not its output.
        if depth and _is_codegen_root(ancestor):
            return True
        if _is_repo_root(ancestor):
            break
    return False


def clear_path_caches() -> None:
    """Start one rule run with fresh, bounded filesystem marker lookups."""
    _is_codegen_root.cache_clear()
    _is_repo_root.cache_clear()


def is_generated(path: Path, source: str) -> bool:
    """Report whether the file is generated, by either header or location."""
    return is_generated_source(source) or is_generated_path(path)


def is_test_path(path: Path) -> bool:
    """Report whether `path` is a test file."""
    name = path.name
    if name == "conftest.py" or name.startswith("test_") or name.endswith("_test.py"):
        return True
    return any(part in _TEST_DIR_NAMES for part in path.parts)
