from __future__ import annotations

from pathlib import Path
import subprocess  # ruff: ignore[suspicious-subprocess-import] -- catches bounded native formatter failures.
from typing import TYPE_CHECKING, Annotated, Final

import typer

from sarj_standards.libs.adoption import transaction
from sarj_standards.libs.diagnostics import (
    Completion,
    Diagnostic,
    ExecutionIssue,
    Location,
    Position,
    Severity,
    ToolReport,
)

from . import textlint
from .devops_tools import TOOLS, NativeToolError, checked_tool
from .external import redact_message, run_process_input


if TYPE_CHECKING:
    from collections.abc import Sequence


FORMAT_ARGS: Final = ("-i", "2", "-ci")
_DIALECTS: Final = {"bash": "bash", "sh": "posix", "dash": "posix", "busybox": "posix", "ksh": "mksh", "zsh": "zsh"}
_GENERATED_MARKERS: Final = ("Gradle start up script for POSIX generated by Gradle.",)


def is_generated(source: str) -> bool:
    return any(marker in source[:8192] for marker in _GENERATED_MARKERS)


def format_source(source: str, *, dialect: str, filename: str, executable: Path, root: Path) -> str:
    output = run_process_input(
        (str(executable), *FORMAT_ARGS, f"-ln={dialect}", f"-filename={filename}"), cwd=root, source=source
    )
    if output.returncode != 0 or output.stderr.strip() or (source.strip() and not output.stdout.strip()):
        message = f"shfmt failed to format {filename}: {output.stderr.strip() or 'incomplete formatter protocol'}"
        raise NativeToolError(message)
    return output.stdout


def _executable(root: Path) -> Path:
    tool = checked_tool("shfmt", root=root)
    if tool.executable is None:
        message = "shfmt did not resolve an attested executable"
        raise NativeToolError(message)
    return tool.executable


def _sources(root: Path, paths: Sequence[str]) -> tuple[tuple[Path, str, str], ...]:
    sources: list[tuple[Path, str, str]] = []
    for raw in sorted(set(paths)):
        path = Path(raw)
        path = path if path.is_absolute() else root / path
        path.resolve().relative_to(root)
        dialect = textlint.shell_dialect(path)
        if dialect is None:
            continue
        source = path.read_bytes().decode("utf-8")
        if not is_generated(source):
            sources.append((path, source, _DIALECTS[dialect]))
    return tuple(sources)


def analyze_sources(*, root: Path, paths: Sequence[str]) -> tuple[ToolReport, ...]:
    root = root.resolve()
    diagnostics: list[Diagnostic] = []
    count = 0
    try:
        sources = _sources(root, paths)
        count = len(sources)
        diagnostics = _format_diagnostics(root, sources)
    except (OSError, UnicodeError, ValueError, NativeToolError, subprocess.SubprocessError) as error:
        issue = ExecutionIssue("shfmt", "formatting-failure", redact_message(str(error), root))
        return (ToolReport("shfmt", Completion.FAILED, issues=(issue,), file_count=count),)
    if not count:
        return ()
    return (
        ToolReport(
            "shfmt",
            Completion.COMPLETE,
            diagnostics=tuple(diagnostics),
            version=TOOLS["shfmt"].version,
            file_count=count,
        ),
    )


def _format_diagnostics(root: Path, sources: tuple[tuple[Path, str, str], ...]) -> list[Diagnostic]:
    if not sources:
        return []
    executable = _executable(root)
    diagnostics: list[Diagnostic] = []
    for path, source, dialect in sources:
        relative = path.relative_to(root).as_posix()
        formatted = format_source(source, dialect=dialect, filename=relative, executable=executable, root=root)
        if formatted != source:
            diagnostics.append(format_diagnostic(path=relative, source=source, formatted=formatted))
    return diagnostics


def format_diagnostic(*, path: str, source: str, formatted: str, line: int = 0) -> Diagnostic:
    original_lines = source.splitlines(keepends=True)
    formatted_lines = formatted.splitlines(keepends=True)
    first = next(
        (i for i, pair in enumerate(zip(original_lines, formatted_lines, strict=False)) if pair[0] != pair[1]), 0
    )
    return Diagnostic(
        "format",
        "Format shell source with shfmt (two spaces and indented case clauses).",
        Severity.WARNING,
        "shfmt",
        Location(
            path, position=Position(line + first, 0, sum(len(item.encode("utf-8")) for item in original_lines[:first]))
        ),
        rule_id="format",
        help="Run `code-standards fix` on this path.",
        help_url="https://github.com/mvdan/sh",
        tags=("formatting",),
    )


def fix_sources(root: Path, paths: Sequence[str]) -> int:
    root = root.resolve()
    pending: list[tuple[Path, str, bytes]] = []
    captured: transaction.FileTransaction | None = None
    try:
        pending = _plan_fixes(root, paths)
        captured = transaction.FileTransaction.capture(
            root, tuple(path for path, _formatted, _before in pending), explicit_only=True
        )
        _apply_fixes(root, pending, captured)
    except (OSError, UnicodeError, ValueError, NativeToolError, subprocess.SubprocessError) as error:
        rollback = None if captured is None else captured.rollback().render()
        typer.echo(f"shfmt: {redact_message(str(error), root)}", err=True)
        if rollback:
            typer.echo(rollback, err=True)
        return 2
    return 0


def _plan_fixes(root: Path, paths: Sequence[str]) -> list[tuple[Path, str, bytes]]:
    sources = _sources(root, paths)
    transaction.validate_targets(root, tuple(path for path, _source, _dialect in sources))
    if not sources:
        return []
    executable = _executable(root)
    pending: list[tuple[Path, str, bytes]] = []
    for path, source, dialect in sources:
        formatted = format_source(
            source, dialect=dialect, filename=path.relative_to(root).as_posix(), executable=executable, root=root
        )
        if source != formatted:
            pending.append((path, formatted, source.encode("utf-8")))
    return pending


def _apply_fixes(root: Path, pending: list[tuple[Path, str, bytes]], captured: transaction.FileTransaction) -> None:
    for path, formatted, before in pending:
        transaction.assert_expected(root, path, before)
        captured.write_text(path, formatted)


def main(
    root: Annotated[Path, typer.Option("--root")],
    paths: Annotated[list[str], typer.Argument()],
) -> None:
    raise typer.Exit(fix_sources(root, paths))


if __name__ == "__main__":
    typer.run(main)
