from __future__ import annotations

from pathlib import PurePosixPath
import re
from typing import TYPE_CHECKING, final, override

from sarj_sql_lint.rule_base import (
    AutofixPolicy,
    Diagnostic,
    ExampleFile,
    ExampleOutcome,
    Rule,
    RuleCategory,
    RuleDocumentation,
    RuleExample,
    declared_dialect,
    dollar_quoted_spans,
    is_dump_file,
    is_migration_source,
    mask_sql,
)


if TYPE_CHECKING:
    from pathlib import Path


_DYNAMIC_VALUE = (
    r"(?:%\([A-Za-z_]\w*\)s(?!\w)|%s(?!\w)|\?(?:\d+(?!\w)|(?!\w))|"
    r"(?<!:):[A-Za-z_]\w*|@[A-Za-z_]\w*|\$\d+(?!\w))"
)
_SCALAR = rf"(?:{_DYNAMIC_VALUE}|\d+)"
_SIMPLE_EXPRESSION = rf"[+-]?\s*{_DYNAMIC_VALUE}(?:\s*[+*/%-]\s*{_SCALAR})*"
_TYPE_NAME = (
    r"[A-Za-z_][A-Za-z0-9_]*(?:\s*\.\s*[A-Za-z_][A-Za-z0-9_]*)*"
    r"(?:\s*\(\s*\d+(?:\s*,\s*\d+)?\s*\))?(?:\s*\[\s*\])*"
)
_PAREN_EXPRESSION = rf"\(\s*(?:{_SIMPLE_EXPRESSION}|\(\s*{_SIMPLE_EXPRESSION}\s*\))\s*\)"
_OFFSET_VALUE = (
    rf"(?:{_SIMPLE_EXPRESSION}|{_PAREN_EXPRESSION}|"
    rf"CAST\s*\(\s*{_DYNAMIC_VALUE}\s+AS\s+{_TYPE_NAME}\s*\)|"
    rf"COALESCE\s*\(\s*{_DYNAMIC_VALUE}\s*,\s*\d+\s*\))"
)
_POSTFIX_CAST = rf"(?:\s*::\s*{_TYPE_NAME})?"
_CLAUSE_END = r"(?=\s*(?:ROWS?\b|FETCH\b|FOR\b|\)|$))"
_OFFSET_PATTERN = re.compile(
    rf"\bOFFSET\b\s+{_OFFSET_VALUE}{_POSTFIX_CAST}{_CLAUSE_END}",
    re.IGNORECASE | re.DOTALL,
)
_MYSQL_LIMIT_PATTERN = re.compile(
    rf"\bLIMIT\b\s+{_DYNAMIC_VALUE}\s*,\s*(?:{_DYNAMIC_VALUE}|\d+){_CLAUSE_END}",
    re.IGNORECASE | re.DOTALL,
)
_QUERY_START = re.compile(r"^\s*(?:SELECT\b|WITH\b)", re.IGNORECASE)
_FROM = re.compile(r"\bFROM\b", re.IGNORECASE)
_GENERATED_HEADER = re.compile(
    r"^\s*--\s*(?:@generated\b|code generated\b|generated by\b)", re.IGNORECASE | re.MULTILINE
)
_NON_PRODUCTION_PARTS = frozenset(
    {
        "__fixtures__",
        "__mocks__",
        "__snapshots__",
        "__tests__",
        "example",
        "examples",
        "fixture",
        "fixtures",
        "generated",
        "migration",
        "migrations",
        "mock",
        "mocks",
        "snapshot",
        "snapshots",
        "test",
        "testdata",
        "tests",
    }
)


@final
class NoOffsetPagination(Rule):
    id = "no-offset-pagination"
    code = "SARJ107"
    documentation = RuleDocumentation(
        summary="Dynamic OFFSET pagination in query SQL should use a stable cursor.",
        rationale=(
            "A parameterized offset grows with the requested page, forcing the database to scan and discard earlier "
            "rows. Concurrent inserts or deletes can also shift page boundaries, repeating or skipping rows."
        ),
        remediation=(
            "Use keyset pagination over a stable, immutable ordering. Match the cursor predicate to the ORDER BY "
            "direction and add a unique tie-breaker. Keep dynamic OFFSET only for an intentional random-access "
            "contract or demonstrably bounded/static data, with an exact SARJ107 suppression."
        ),
        category=RuleCategory.PERFORMANCE,
        autofix=AutofixPolicy.NONE,
        aliases=("no-limit-offset",),
        limitations=(
            "Only dynamic driver markers in credible SELECT statements are reported; fixed ordinal offsets are preserved.",
            "PostgreSQL, SQLite, and common Python driver markers are recognized, together with MySQL LIMIT offset,count syntax.",
            "Dumps, migrations, generated paths or marked files, tests, fixtures, snapshots, ORM calls, bare procedural variables, and ambiguous templates are excluded.",
        ),
        examples=(
            RuleExample(
                example_id="offset-pagination",
                title="Pagination that scans skipped rows",
                outcome=ExampleOutcome.MATCH,
                files=(
                    ExampleFile.sql(
                        "queries/events.sql",
                        "SELECT created_at, id FROM event ORDER BY created_at DESC, id DESC LIMIT $1 OFFSET $2;\n",
                    ),
                ),
                focus_path=PurePosixPath("queries/events.sql"),
                expected_count=1,
                public=True,
            ),
            RuleExample(
                example_id="cursor-pagination",
                title="Pagination bounded by a stable cursor",
                outcome=ExampleOutcome.NO_MATCH,
                files=(
                    ExampleFile.sql(
                        "queries/events.sql",
                        "SELECT created_at, id FROM event\n"
                        "WHERE (created_at, id) < ($1, $2)\n"
                        "ORDER BY created_at DESC, id DESC LIMIT $3;\n",
                    ),
                ),
                focus_path=PurePosixPath("queries/events.sql"),
                expected_count=0,
                public=True,
            ),
        ),
    )
    description = documentation.summary

    @override
    def check(self, path: Path, source: str) -> list[Diagnostic]:
        path_parts = frozenset(part.lower() for part in path.parts)
        if (
            path_parts & _NON_PRODUCTION_PARTS
            or is_dump_file(source, path)
            or is_migration_source(path, source)
            or path.name.lower().endswith(".generated.sql")
            or _GENERATED_HEADER.search(source[:1024]) is not None
        ):
            return []

        diags: list[Diagnostic] = []
        masked = _mask_cross_dialect_noncode(
            _mask_dollar_quoted_values(source, mask_sql(source)),
            preserve_hash_operator=declared_dialect(source) == "postgresql",
        )
        for statement_start, text in _statement_spans(masked):
            if _QUERY_START.search(text) is None or text.count("(") != text.count(")"):
                continue
            matches = sorted(
                (*_OFFSET_PATTERN.finditer(text), *_MYSQL_LIMIT_PATTERN.finditer(text)),
                key=lambda match: match.start(),
            )
            for match in matches:
                if _FROM.search(text, 0, match.start()) is None:
                    continue
                suffix = text[match.end() :].lstrip()
                if suffix.startswith(")") and text[: match.end()].count("(") <= text[: match.end()].count(")"):
                    continue
                offset = statement_start + match.start()
                diags.append(
                    Diagnostic(
                        path=path,
                        line=source.count("\n", 0, offset) + 1,
                        col=offset - source.rfind("\n", 0, offset),
                        code=self.code,
                        message=(
                            "Replace dynamic OFFSET with a direction-matched, stable, unique cursor; suppress "
                            "SARJ107 only for an intentional bounded or random-access contract."
                        ),
                    )
                )
        return diags


def _mask_dollar_quoted_values(source: str, masked: str) -> str:
    chars = list(masked)
    for start, end in dollar_quoted_spans(source):
        for index in range(start, end):
            if chars[index] != "\n":
                chars[index] = " "
    return "".join(chars)


def _statement_spans(masked: str) -> list[tuple[int, str]]:
    spans: list[tuple[int, str]] = []
    start = 0
    for match in re.finditer(r";", masked):
        spans.append((start, masked[start : match.start()]))
        start = match.end()
    if start < len(masked):
        spans.append((start, masked[start:]))
    return spans


def _mask_cross_dialect_noncode(masked: str, *, preserve_hash_operator: bool) -> str:
    chars = list(masked)
    cursor = 0
    while cursor < len(chars):
        char = chars[cursor]
        if (
            char == "#"
            and not preserve_hash_operator
            and (cursor + 1 >= len(chars) or chars[cursor + 1] not in {">", "-"})
        ):
            end = masked.find("\n", cursor)
            end = len(chars) if end < 0 else end
            for index in range(cursor, end):
                chars[index] = " "
            cursor = end
            continue
        if char not in {"`", "["}:
            cursor += 1
            continue
        closer = "`" if char == "`" else "]"
        index = cursor + 1
        while index < len(chars):
            if chars[index] != closer:
                index += 1
                continue
            if index + 1 < len(chars) and chars[index + 1] == closer:
                index += 2
                continue
            index += 1
            break
        for blank_index in range(cursor, index):
            if chars[blank_index] != "\n":
                chars[blank_index] = " "
        cursor = index
    return "".join(chars)
