"""The one file a consumer repo pins, and the versions everything else must match."""

from __future__ import annotations

from dataclasses import dataclass
from importlib.metadata import PackageNotFoundError, version
import json
import tomllib
from typing import TYPE_CHECKING, Final, Literal

from sarj_lint_configs._meta import CONFIGS_DIR, __version__


if TYPE_CHECKING:
    from collections.abc import Mapping
    from pathlib import Path


MANIFEST_NAME: Final = ".sarj-standards.toml"
_CONFIGS_KEY: Final = "configs"
Profile = Literal["standard", "application"]
PROFILES: Final[tuple[Profile, ...]] = ("standard", "application")

PEERS_JSON: Final = CONFIGS_DIR / "eslint.peers.json"

#: Sibling distributions pinned exactly by `sarj-lint-configs`.
LINT_CONFIGS: Final = "sarj-lint-configs"
_PYTHON_LINT: Final = "sarj-python-lint"
SIBLING_PACKAGES: Final = (_PYTHON_LINT, "sarj-sql-lint", "sarj-iac-lint")


def adopted_version() -> str:
    """Report the `sarj-lint-configs` version this environment provides."""
    return __version__


#: Config bundle selected for each detected ecosystem.
PYTHON_CONFIGS: Final = ("ruff", "pyright")
TYPESCRIPT_CONFIGS: Final = ("eslint",)
SHARED_CONFIGS: Final = ("markdownlint", "taplo", "yamllint")


@dataclass(frozen=True)
class Manifest:
    """A consumer repo's declared adoption of this package."""

    version: str
    configs: tuple[str, ...]
    python_dest: str
    typescript_dest: str
    profile: Profile = "standard"
    verify_paths: tuple[str, ...] = (".",)

    def render(self) -> str:
        """Serialise to the TOML text written at the repo root."""
        configs = ", ".join(f'"{name}"' for name in self.configs)
        return (
            "# Generated by `sarj-standards init`; commit this file.\n"
            f'version = "{self.version}"\n'
            f'profile = "{self.profile}"\n'
            "\n"
            f"configs = [{configs}]\n"
            "\n"
            "[artifacts]\n"
            'durable = ["**/README.md", "docs/**", "**/docs/**", "architecture/**", '
            '"**/adr/**", ".github/**", "**/AGENTS.md", "**/CLAUDE.md"]\n'
            "\n"
            "[dest]\n"
            f'python = "{self.python_dest}"\n'
            f'typescript = "{self.typescript_dest}"\n'
        )


def as_table(value: object) -> dict[str, object]:
    """Read an untyped mapping as a string-keyed table of unknown values."""
    if not isinstance(value, dict):
        return {}
    # Centralize untyped-parser narrowing so downstream tables stay typed.
    entries: dict[str, object] = {}
    for key, item in value.items():  # pyright: ignore[reportUnknownVariableType]
        if isinstance(key, str):
            entries[key] = item  # ruff: ignore[manual-dict-comprehension] - pyright needs narrowing
    return entries


def text_field(table: Mapping[str, object], key: str) -> str | None:
    """Read one string out of an untyped table."""
    value = table.get(key)
    return value if isinstance(value, str) else None


def list_field(table: Mapping[str, object], key: str) -> list[object]:
    """Read one list out of an untyped table."""
    value = table.get(key)
    return value if isinstance(value, list) else []  # pyright: ignore[reportUnknownVariableType] — a narrowed `list` from an untyped parser has Unknown leaves


def table_field(table: Mapping[str, object], key: str) -> dict[str, object]:
    """Read one nested table out of an untyped table."""
    return as_table(table.get(key))


def default_configs(*, has_python: bool, has_typescript: bool) -> tuple[str, ...]:
    """Pick the config set for a repo's detected ecosystems."""
    selected: set[str] = set(SHARED_CONFIGS)
    if has_python:
        selected.update(PYTHON_CONFIGS)
    if has_typescript:
        selected.update(TYPESCRIPT_CONFIGS)
    order = (*PYTHON_CONFIGS, *TYPESCRIPT_CONFIGS, *SHARED_CONFIGS)
    return tuple(name for name in order if name in selected)


def manifest_path(root: Path) -> Path:
    """Locate the manifest for a repo root."""
    return root / MANIFEST_NAME


def load(root: Path) -> Manifest | None:
    """Read a repo's manifest."""
    path = manifest_path(root)
    if not path.is_file():
        return None
    try:
        parsed: object = tomllib.loads(path.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError as exc:
        msg = f"{path} is not valid TOML: {exc}"
        raise ValueError(msg) from exc

    data = as_table(parsed)
    declared = text_field(data, "version")
    raw_profile = data.get("profile", "standard")
    names = list_field(data, _CONFIGS_KEY)
    declares_a_list = isinstance(_configs_entry(data), list)
    if declared is None or not declares_a_list:
        msg = f"{path} must set a string `version` and a list `configs`"
        raise TypeError(msg)
    if not all(isinstance(name, str) for name in names):
        msg = f"{path} `configs` must contain only strings"
        raise TypeError(msg)
    if not isinstance(raw_profile, str) or raw_profile not in PROFILES:
        msg = f"{path} `profile` must be one of: {', '.join(PROFILES)}"
        raise ValueError(msg)
    profile: Profile = raw_profile

    dest_table = table_field(data, "dest")
    verify_table = table_field(data, "verify")
    return Manifest(
        version=declared,
        configs=tuple(name for name in names if isinstance(name, str)),
        python_dest=_dest_value(dest_table, "python"),
        typescript_dest=_dest_value(dest_table, "typescript"),
        profile=profile,
        verify_paths=_verify_paths(root, verify_table),
    )


def _configs_entry(table: Mapping[str, object]) -> object:
    """Read the raw `configs` entry so its TYPE can be validated, not just its contents."""
    return table.get(_CONFIGS_KEY)


def _dest_value(table: dict[str, object], key: str) -> str:
    if key not in table:
        return "."
    value = table[key]
    if not isinstance(value, str) or not value:
        msg = f"manifest [dest].{key} must be a non-empty string"
        raise TypeError(msg)
    return value


def _verify_paths(root: Path, table: dict[str, object]) -> tuple[str, ...]:
    if "paths" not in table:
        return (".",)
    values = list_field(table, "paths")
    if not values or not all(isinstance(value, str) and value for value in values):
        msg = "manifest [verify].paths must be a non-empty list of non-empty strings"
        raise TypeError(msg)
    paths = tuple(value for value in values if isinstance(value, str))
    for value in paths:
        try:
            (root / value).resolve().relative_to(root.resolve())
        except ValueError as exc:
            msg = f"manifest [verify].paths entry escapes repository root: {value}"
            raise ValueError(msg) from exc
    return paths


def installed_versions() -> dict[str, str]:
    """Report the versions of every Sarj distribution in the current environment."""
    found = {LINT_CONFIGS: __version__}
    for name in SIBLING_PACKAGES:
        try:
            found[name] = version(name)
        except PackageNotFoundError:
            continue
    return found


def expected_precommit_rev() -> str | None:
    """Derive the `rev:` a repo's pre-commit config must carry."""
    installed = text_field(installed_versions(), _PYTHON_LINT)
    return None if installed is None else f"python-v{installed}"


def eslint_peers() -> dict[str, str]:
    """Read the tested npm version set for the bundled ESLint config."""
    parsed: object = json.loads(  # pyright: ignore[reportAny] — json.loads is an untyped stdlib boundary; the shape is narrowed below
        PEERS_JSON.read_text(encoding="utf-8")
    )
    table = table_field(as_table(parsed), "peers")
    if not table:
        msg = f"{PEERS_JSON} must contain a `peers` object"
        raise TypeError(msg)
    return {name: pin for name, pin in table.items() if isinstance(pin, str)}


def eslint_overrides() -> dict[str, object]:
    """Read the npm `overrides` the peer set needs to install at all."""
    parsed: object = json.loads(  # pyright: ignore[reportAny] — json.loads is an untyped stdlib boundary; the shape is narrowed below
        PEERS_JSON.read_text(encoding="utf-8")
    )
    return table_field(as_table(parsed), "npmOverrides")


def eslint_install_command() -> str:
    """Build the npm command that installs every ESLint peer at a resolvable version."""
    peers = eslint_peers()
    specs = " ".join(f"{name}@{pin}" for name, pin in sorted(peers.items()))
    return f"npm install -D --save-exact {specs}"
