from pathlib import Path

import pytest

from sarj_sql_lint.rules.no_comment_cruft import NoCommentCruft


_DEBT_MARKER = "TO" + "DO"


def _check(source: str, name: str = "migration.sql"):
    return NoCommentCruft().check(Path(name), source)


@pytest.mark.parametrize(
    "source",
    [
        "-- DROP TABLE legacy;\nSELECT 1;",
        "/* CREATE TABLE old (id bigint); */\nSELECT 1;",
        "-- ===== legacy =====\nSELECT 1;",
        f"-- {_DEBT_MARKER} remove old rows\nSELECT 1;",
        "-- SELECT id\n-- FROM legacy\n-- WHERE active;\nSELECT 1;",
        "-- CREATE UNIQUE INDEX old_idx ON legacy (id);\nSELECT 1;",
        "/* DROP TABLE legacy;\n * sarj-noqa: SARJ999\n */\nSELECT 1;",
    ],
)
def test_flags_comment_cruft(source: str) -> None:
    assert len(_check(source)) == 1


@pytest.mark.parametrize(
    "source",
    [
        "SELECT '-- DROP TABLE live';",
        "DO $$ BEGIN RAISE NOTICE '-- DROP TABLE live'; END $$;",
        "{% if enabled %}\nSELECT 1;\n{% endif %}\n{# ---------- section ---------- #}",
        "-- create or replace the table instead of dropping it\nSELECT 1;",
        "-- migrate:up\nSELECT 1;",
        "-- Roll back from snapshot OPS-812.\nSELECT 1;",
        f"-- {_DEBT_MARKER} tracked in DB-812\nSELECT 1;",
        "-- The replica must be updated before this statement.\nSELECT 1;",
        "-- CREATE TABLE statements must use bigint IDs.\nSELECT 1;",
    ],
)
def test_preserves_non_cruft_comments(source: str) -> None:
    assert _check(source) == []


def test_skips_dump_files() -> None:
    assert _check("-- PostgreSQL database dump\n-- DROP TABLE legacy;", "schema.sql") == []


@pytest.mark.parametrize(
    ("source", "name"),
    [
        (
            "-- Generated by Drizzle\n--> statement-breakpoint\n\n-- DROP TABLE legacy;",
            "migrations/001.sql",
        ),
        ("-- DROP TABLE legacy;\nSELECT 1;", "queries/report.sql"),
        ("-- DROP TABLE legacy;\nSELECT 1;", "tests/fixtures/report.sql"),
        ("-- DROP TABLE legacy;\nSELECT 1;", "tests/migrations/001.sql"),
        ("-- DROP TABLE legacy;\nSELECT 1;", "test/V1__legacy.sql"),
        ("-- DROP TABLE legacy;\nSELECT 1;", "scripts/maintenance.sql"),
    ],
    ids=("generated-migration", "query", "fixture", "tests-migration", "test-flyway", "script"),
)
def test_skips_generated_and_nonmigration_sources(source: str, name: str) -> None:
    assert _check(source, name) == []


@pytest.mark.parametrize(
    "source",
    [
        f"-- {_DEBT_MARKER} remove the MD5 fallback\nSELECT 1;",
        f"-- {_DEBT_MARKER} replace SHA256 compatibility mode\nSELECT 1;",
        f"-- {_DEBT_MARKER} finish phase 2\nSELECT 1;",
        "-- ===== PHASE 2 =====\nSELECT 1;",
        "-- ===== See RFC 9110 =====\nSELECT 1;",
    ],
    ids=(
        "md5-is-not-ticket",
        "sha256-is-not-ticket",
        "phase-number-is-not-ticket",
        "banner-phase-number",
        "banner-reference-is-still-cruft",
    ),
)
def test_does_not_treat_incidental_capitalized_numbers_as_issue_references(source: str) -> None:
    assert len(_check(source)) == 1


@pytest.mark.parametrize(
    "source",
    [
        f"-- {_DEBT_MARKER} tracked in DB-812\nSELECT 1;",
        f"-- {_DEBT_MARKER} tracked in https://tracker.example/issues/812\nSELECT 1;",
        "-- Roll back using snapshot OPS-812.\nSELECT 1;",
    ],
    ids=("project-ticket", "issue-url", "rollback-ticket"),
)
def test_preserves_comments_with_durable_references(source: str) -> None:
    assert _check(source) == []


@pytest.mark.parametrize(
    "source",
    [
        "-- Preserve ---- as the import sentinel.\nSELECT 1;",
        "-- The token parser accepts ==== inside quoted input.\nSELECT 1;",
        "-- The wildcard *.example.com remains intentionally narrow.\nSELECT 1;",
    ],
    ids=("hyphens-in-prose", "equals-in-prose", "punctuation-in-prose"),
)
def test_preserves_meaningful_prose_containing_punctuation(source: str) -> None:
    assert _check(source) == []


def test_adjacent_inline_comments_are_not_combined_across_statements() -> None:
    findings = _check(f"SELECT 1; -- {_DEBT_MARKER} remove the fallback\nSELECT 2; -- tracked in DB-812\n")

    assert [finding.line for finding in findings] == [1]


def test_reference_on_one_comment_does_not_hide_adjacent_debt() -> None:
    findings = _check(
        "-- See OPS-812 for the compatibility constraint.\n"
        f"-- {_DEBT_MARKER} remove the unrelated fallback\n"
        "SELECT 1;\n"
    )

    assert [finding.line for finding in findings] == [2]


def test_diagnostic_points_to_offending_comment_after_directive() -> None:
    findings = _check("-- sqlfluff: disable=all\n-- DROP TABLE legacy;\nSELECT 1;\n")

    assert [finding.line for finding in findings] == [2]


def test_directive_prefix_in_prose_does_not_hide_debt() -> None:
    findings = _check(f"-- sqlfluffing is not a directive\n-- {_DEBT_MARKER} remove fallback\nSELECT 1;\n")

    assert [finding.line for finding in findings] == [2]


@pytest.mark.parametrize(
    "source",
    [
        "-- sqlfluff: disable=layout.long_lines\nSELECT 1;",
        "-- noqa: SARJ113\nSELECT 1;",
        "-- dialect: postgresql\nSELECT 1;",
        "-- migrate:up\nSELECT 1;",
        "-- +goose Down\nSELECT 1;",
        "-- liquibase formatted sql\nSELECT 1;",
        "--changeset app:001\nSELECT 1;",
        "--rollback DROP TABLE legacy;\nSELECT 1;",
        "-- pg_dump: emitted metadata\nSELECT 1;",
    ],
    ids=("sqlfluff", "noqa", "dialect", "dbmate", "goose", "liquibase", "changeset", "rollback", "pg-dump"),
)
def test_preserves_tooling_and_migration_directives(source: str) -> None:
    assert _check(source) == []


@pytest.mark.parametrize(
    "commented_statement",
    [
        "CREATE TABLE IF NOT EXISTS legacy (id bigint);",
        "CREATE INDEX CONCURRENTLY legacy_idx ON legacy (id);",
        "SELECT 1;",
        "WITH doomed AS (SELECT id FROM legacy) DELETE FROM legacy USING doomed WHERE legacy.id = doomed.id;",
        "GRANT SELECT ON TABLE legacy TO reader;",
        "REVOKE SELECT ON TABLE legacy FROM reader;",
        "MERGE INTO target USING source ON target.id = source.id WHEN MATCHED THEN DELETE;",
        "COPY legacy TO '/tmp/legacy.csv';",
        "CALL rebuild_legacy();",
        "COMMENT ON TABLE legacy IS 'legacy';",
        "DO $$ BEGIN RAISE NOTICE 'legacy'; END $$;",
        'DROP TABLE IF EXISTS "legacy.schema"."old-table";',
        "CREATE TYPE integration_state AS ENUM ('active', 'disabled');",
        "INSERT INTO legacy (id) VALUES (1);",
        "UPDATE legacy SET active = false WHERE id = 1;",
        "VACUUM (ANALYZE) legacy;",
        "ALTER TABLE legacy ADD COLUMN archived boolean;",
        "CREATE VIEW active_legacy AS SELECT id FROM legacy;",
        "CREATE DOMAIN event_id AS bigint;",
        "CREATE INDEX active_legacy_idx ON legacy USING btree (id) WHERE active;",
        "SET lock_timeout TO '5s';",
        "TRUNCATE TABLE legacy RESTART IDENTITY CASCADE;",
        "INSERT INTO archive SELECT id FROM legacy;",
        "DELETE FROM legacy WHERE archived;",
    ],
    ids=(
        "create-if-not-exists",
        "create-index-concurrently",
        "select-expression",
        "with-delete",
        "grant",
        "revoke",
        "merge",
        "copy",
        "call",
        "comment-on",
        "do-block",
        "quoted-drop-if-exists",
        "create-enum-type",
        "insert-values-row",
        "update-assignment",
        "vacuum-options",
        "alter-add-column",
        "create-view-select",
        "create-domain",
        "create-partial-index",
        "set-scalar",
        "truncate-options",
        "insert-select",
        "delete-where",
    ),
)
def test_flags_complete_commented_out_sql_heads(commented_statement: str) -> None:
    assert len(_check(f"-- {commented_statement}\nSELECT 1;")) == 1


@pytest.mark.parametrize(
    "source",
    [
        "-- CREATE TABLE;\nSELECT 1;",
        "-- CREATE TABLE legacy (\nSELECT 1;",
        "-- ALTER TABLE legacy;\nSELECT 1;",
        "-- INSERT INTO;\nSELECT 1;",
        "-- SELECT FROM legacy;\nSELECT 1;",
        "-- GRANT ON legacy;\nSELECT 1;",
        "-- DROP;\nSELECT 1;",
        "-- SELECT a better name before launch;\nSELECT 1;",
        "-- CALL support before deploying;\nSELECT 1;",
        "-- CREATE TYPE later after review;\nSELECT 1;",
        "-- VACUUM maybe after launch;\nSELECT 1;",
        "-- UPDATE this SET later;\nSELECT 1;",
        "-- INSERT INTO docs VALUES eventually;\nSELECT 1;",
        "-- SELECT a better name FROM the API;\nSELECT 1;",
        "-- CREATE DOMAIN later AS a better type;\nSELECT 1;",
        "-- ALTER TABLE users SET expectations carefully;\nSELECT 1;",
        "-- CREATE VIEW records AS needed for support;\nSELECT 1;",
        "-- GRANT access ON approval TO operators;\nSELECT 1;",
        "-- COPY data TO the archive;\nSELECT 1;",
        "-- SET expectations TO realistic levels;\nSELECT 1;",
        "-- TRUNCATE discussion after the key point;\nSELECT 1;",
        "-- INSERT INTO docs SELECT the right examples;\nSELECT 1;",
        "-- DELETE FROM memory;\nSELECT 1;",
    ],
    ids=(
        "create-missing-name",
        "unclosed-create",
        "alter-missing-action",
        "insert-missing-target",
        "select-missing-list",
        "grant-missing-privilege",
        "drop-missing-kind",
        "select-prose",
        "call-prose",
        "create-type-prose",
        "vacuum-prose",
        "update-prose",
        "insert-prose",
        "select-from-prose",
        "create-domain-prose",
        "alter-prose",
        "create-view-prose",
        "grant-prose",
        "copy-prose",
        "set-prose",
        "truncate-prose",
        "insert-select-prose",
        "delete-prose",
    ),
)
def test_abstains_on_sql_like_but_malformed_comments(source: str) -> None:
    assert _check(source) == []


@pytest.mark.parametrize(
    "source",
    [
        "-- DROP TABLE legacy_a; DROP TABLE legacy_b;\nSELECT 1;",
        "-- DROP TABLE legacy_a;\n-- DROP TABLE legacy_b;\nSELECT 1;",
    ],
    ids=("same-comment", "adjacent-comments"),
)
def test_reports_one_diagnostic_for_a_commented_statement_group(source: str) -> None:
    findings = _check(source)

    assert len(findings) == 1
    assert findings[0].line == 1


def test_adjacent_prose_does_not_hide_a_complete_commented_statement() -> None:
    findings = _check("-- DROP TABLE old;\n-- This note describes the next statement.\nSELECT 1;\n")

    assert len(findings) == 1
    assert findings[0].line == 1


def test_diagnostic_points_to_supported_statement_after_adjacent_prose() -> None:
    findings = _check("-- This prose ends here;\n-- DROP TABLE old;\nSELECT 1;\n")

    assert len(findings) == 1
    assert findings[0].line == 2


def test_issue_reference_does_not_bless_disabled_sql() -> None:
    assert len(_check("-- DROP TABLE legacy; #812\nSELECT 1;")) == 1


@pytest.mark.parametrize(
    ("extra_comment", "expected_line"),
    [
        (f"-- {_DEBT_MARKER} remove fallback\n", 2),
        ("-- ===== legacy =====\n", 2),
    ],
    ids=("debt", "banner"),
)
def test_rollback_context_does_not_hide_debt_or_banner(extra_comment: str, expected_line: int) -> None:
    findings = _check(f"-- Roll back by restoring the snapshot.\n{extra_comment}SELECT 1;\n")

    assert len(findings) == 1
    assert findings[0].line == expected_line


@pytest.mark.parametrize(
    "source",
    [
        "-- Rollback procedure:\n-- DROP TABLE legacy;\nSELECT 1;",
        "-- Roll back by running DROP TABLE legacy after restoring snapshot OPS-812.\nSELECT 1;",
        "--rollback DROP TABLE legacy;\nSELECT 1;",
    ],
    ids=("rollback-block", "rollback-prose", "liquibase-rollback"),
)
def test_preserves_explicit_rollback_instructions(source: str) -> None:
    assert _check(source) == []


def test_public_examples_execute() -> None:
    examples = NoCommentCruft.public_examples()
    assert [len(_check(example.focus_file.source)) for example in examples] == [1, 0]
