"""Typed contracts for designing and evaluating deterministic lint rules."""

from .catalog import DocumentedRule, RuleCatalog, RuleCatalogDocument
from .contracts import (
    AutofixPolicy,
    CatalogRule,
    DefaultLevel,
    EvaluationCase,
    ExampleFile,
    ExpectedOutcome,
    Finding,
    Language,
    MessageId,
    RuleCategory,
    RuleEngine,
    RuleExample,
    RuleId,
    RuleOrigin,
    RuleProblem,
    RuleSelection,
    RuleSelector,
    RuleSpec,
    RuleStatus,
)
from .corpus_runner import (
    CorpusBatchResult,
    CorpusLintError,
    IsolatedCorpusReport,
    run_isolated_corpora,
)
from .evaluation import (
    CaseEvaluation,
    EvaluationEvidence,
    EvaluationReport,
    EvaluationThresholds,
    PromotionDecision,
    RuleEvaluator,
    evaluate,
)


__all__ = [
    "AutofixPolicy",
    "CaseEvaluation",
    "CatalogRule",
    "CorpusBatchResult",
    "CorpusLintError",
    "DefaultLevel",
    "DocumentedRule",
    "EvaluationCase",
    "EvaluationEvidence",
    "EvaluationReport",
    "EvaluationThresholds",
    "ExampleFile",
    "ExpectedOutcome",
    "Finding",
    "IsolatedCorpusReport",
    "Language",
    "MessageId",
    "PromotionDecision",
    "RuleCatalog",
    "RuleCatalogDocument",
    "RuleCategory",
    "RuleEngine",
    "RuleEvaluator",
    "RuleExample",
    "RuleId",
    "RuleOrigin",
    "RuleProblem",
    "RuleSelection",
    "RuleSelector",
    "RuleSpec",
    "RuleStatus",
    "evaluate",
    "run_isolated_corpora",
]
