"""Generate every human-facing README from repository-owned source data."""

from __future__ import annotations

from dataclasses import dataclass
import json
import os
from pathlib import Path
import re
import shlex
import subprocess  # ruff: ignore[suspicious-subprocess-import] -- validates fixed local CLI examples.
import sys
import tomllib
from typing import Final, TypeGuard

from sarj_standards.libs.adoption import transaction


_GENERATED_SENTINEL: Final = "<!-- Generated by `sarj-standards maintain docs sync`; do not edit. -->"
_LOCAL_LINK: Final = re.compile(r"\[[^]]+\]\((?!https?://|mailto:)([^)#]*)(?:#([^)]+))?\)")
_HEADING: Final = re.compile(r"^#{1,6}\s+(.+?)\s*#*\s*$", re.MULTILINE)
_STANDARDS_COMMAND: Final = re.compile(r"^\s*(sarj-standards(?:\s+.+)?)\s*$", re.MULTILINE)
_DOCUMENT_SUFFIXES: Final = frozenset({".md", ".mdx", ".rst"})
_WALK_EXCLUDES: Final = frozenset(
    {".git", ".mypy_cache", ".pytest_cache", ".ruff_cache", ".venv", "build", "coverage", "dist", "node_modules"}
)
_GENERATED_READMES: Final = (
    Path("README.md"),
    Path("packages/standards/README.md"),
    Path("packages/python/README.md"),
    Path("packages/sql/README.md"),
    Path("packages/iac/README.md"),
    Path("packages/typescript/README.md"),
    Path("packages/tsconfig/README.md"),
    Path("plugins/sarj-audit/README.md"),
)
_EXECUTABLE_OR_LEGAL_DOCUMENTS: Final = (Path("CLAUDE.md"),)
_PACKAGE_DEFINITIONS: Final = (
    ("packages/standards/pyproject.toml", "PyPI", "text"),
    ("packages/python/pyproject.toml", "PyPI", "python"),
    ("packages/sql/pyproject.toml", "PyPI", "sql"),
    ("packages/iac/pyproject.toml", "PyPI", "iac"),
    ("packages/typescript/package.json", "npm", "eslint"),
    ("packages/tsconfig/package.json", "npm", None),
)
_CATALOG_PATH: Final = Path("packages/standards/src/sarj_standards/schemas/rule-catalog.v1.json")


@dataclass(frozen=True, slots=True)
class DocumentationResult:
    """Outcome of a deterministic documentation check or synchronization."""

    changed: tuple[Path, ...]
    checked: tuple[Path, ...]

    @property
    def status(self) -> int:
        """Return a process-compatible status: one means generated drift."""
        return int(bool(self.changed))


def check(root: Path) -> DocumentationResult:
    """Report generated README drift and reject non-policy documentation."""
    return _update(root.resolve(), write=False)


def sync(root: Path) -> DocumentationResult:
    """Atomically synchronize every generated README with source data."""
    return _update(root.resolve(), write=True)


def _update(root: Path, *, write: bool) -> DocumentationResult:
    rendered = _render_readmes(root)
    _validate_markdown_allowlist(root)
    changed = tuple(
        path for path, content in rendered.items() if not path.is_file() or path.read_text(encoding="utf-8") != content
    )
    checked = _documentation_paths(root)
    _validate_documents(
        {**{path: path.read_text(encoding="utf-8") for path in checked if path not in rendered}, **rendered}
    )
    if write:
        for path in changed:
            transaction.atomic_write_text(root, path, rendered[path])
    return DocumentationResult(changed=changed, checked=checked)


def _render_readmes(root: Path) -> dict[Path, str]:
    packages = [
        (root / relative, registry, engine, _manifest(root / relative))
        for relative, registry, engine in _PACKAGE_DEFINITIONS
    ]
    rendered = {root / "README.md": _root_readme(root, packages)}
    for manifest_path, registry, engine, metadata in packages:
        rendered[manifest_path.parent / "README.md"] = _package_readme(root, manifest_path, registry, engine, metadata)
    rendered[root / "plugins/sarj-audit/README.md"] = _plugin_readme(root)
    return dict(sorted(rendered.items()))


def _root_readme(
    root: Path,
    packages: list[tuple[Path, str, str | None, dict[str, object]]],
) -> str:
    standards = packages[0][3]
    title = _title(_string(standards, "name"))
    description = _string(standards, "description")
    rows = ["| Package | Version | Registry | Description |", "| --- | --- | --- | --- |"]
    for path, registry, _engine, metadata in packages:
        name = _string(metadata, "name")
        relative = path.parent.relative_to(root).as_posix()
        rows.append(
            f"| [`{name}`]({relative}/) | `{_string(metadata, 'version')}` | {registry} | {_cell(_string(metadata, 'description'))} |"
        )
    sections = [
        _GENERATED_SENTINEL,
        f"# {title}",
        description,
        "## Packages",
        "\n".join(rows),
        "## Command-line reference",
        _cli_reference(packages[0][3], registry="PyPI"),
        "## Rule catalog",
        _catalog(root, engine=None),
        "## Project links",
        _links(standards),
    ]
    return "\n\n".join(sections) + "\n"


def _package_readme(
    root: Path,
    manifest_path: Path,
    registry: str,
    engine: str | None,
    metadata: dict[str, object],
) -> str:
    name = _string(metadata, "name")
    details = [
        "| Field | Value |",
        "| --- | --- |",
        f"| Version | `{_string(metadata, 'version')}` |",
        f"| Registry | {registry} |",
        f"| License | {_license(metadata)} |",
    ]
    runtime = _runtime(metadata)
    if runtime:
        details.append(f"| Runtime | `{runtime}` |")
    sections = [
        _GENERATED_SENTINEL,
        f"# {name}",
        _string(metadata, "description"),
        "## Package metadata",
        "\n".join(details),
    ]
    scripts = _scripts(metadata)
    if scripts:
        sections.extend(("## Command-line reference", _cli_reference(metadata, registry=registry)))
    if engine is not None:
        sections.extend(("## Rule catalog", _catalog(root, engine=engine)))
    links = _links(metadata)
    if links:
        sections.extend(("## Project links", links))
    relative_manifest = manifest_path.relative_to(manifest_path.parent).as_posix()
    sections.append(f"Package metadata is generated from [`{relative_manifest}`]({relative_manifest}).")
    return "\n\n".join(sections) + "\n"


def _plugin_readme(root: Path) -> str:
    manifest_path = root / "plugins/sarj-audit/.claude-plugin/plugin.json"
    metadata = _manifest(manifest_path)
    plugin = manifest_path.parent.parent
    commands = sorted((plugin / "commands").glob("*.md"))
    skills = sorted((plugin / "skills").glob("*/SKILL.md"))
    command_rows = ["| Command | Definition |", "| --- | --- |"]
    command_rows.extend(f"| `{path.stem}` | [`{_markdown_title(path)}`](commands/{path.name}) |" for path in commands)
    skill_rows = ["| Skill | Definition |", "| --- | --- |"]
    skill_rows.extend(
        f"| `{path.parent.name}` | [`{_markdown_title(path)}`](skills/{path.parent.name}/SKILL.md) |" for path in skills
    )
    sections = [
        _GENERATED_SENTINEL,
        f"# {_title(_string(metadata, 'name'))}",
        _string(metadata, "description"),
        "## Plugin metadata",
        "\n".join(
            (
                "| Field | Value |",
                "| --- | --- |",
                f"| Version | `{_string(metadata, 'version')}` |",
                f"| Author | {_author(metadata)} |",
            )
        ),
        "## Commands",
        "\n".join(command_rows),
        "## Skills",
        "\n".join(skill_rows),
        "## Project links",
        _links(metadata),
    ]
    return "\n\n".join(sections) + "\n"


def _catalog(root: Path, *, engine: str | None) -> str:
    catalog_path = root / _CATALOG_PATH
    if catalog_path.is_file():
        raw: object = json.loads(catalog_path.read_text(encoding="utf-8"))  # pyright: ignore[reportAny]
        if not _is_object_table(raw):
            msg = f"{catalog_path} is not an object"
            raise TypeError(msg)
        raw_rules = raw.get("rules")
        if not _is_object_list(raw_rules):
            msg = f"{catalog_path} has no rules array"
            raise ValueError(msg)
        rules = [
            rule for rule in raw_rules if _is_object_table(rule) and (engine is None or rule.get("engine") == engine)
        ]
        rows = ["| Rule | Summary | Default | Autofix |", "| --- | --- | --- | --- |"]
        rows.extend(
            "| `{}` | {} | `{}` | `{}` |".format(
                _string(rule, "key"),
                _cell(_string(rule, "summary")),
                _string(rule, "defaultLevel"),
                _string(rule, "autofix"),
            )
            for rule in sorted(rules, key=lambda item: str(item.get("key", "")))
        )
        return "\n".join(rows) if rules else "This package does not publish lint rules."
    return _ledger_catalog(root, engine=engine)


def _ledger_catalog(root: Path, *, engine: str | None) -> str:
    ledger_path = root / "packages/standards/src/sarj_standards/configs/rule-ledger.json"
    raw: object = json.loads(ledger_path.read_text(encoding="utf-8"))  # pyright: ignore[reportAny]
    if not _is_object_table(raw):
        msg = f"{ledger_path} is not an object"
        raise TypeError(msg)
    groups = raw.get("rules")
    if not _is_object_table(groups):
        msg = f"{ledger_path} has no rules object"
        raise ValueError(msg)
    if engine is not None:
        entries = groups.get(engine)
        if not _is_object_list(entries):
            msg = f"{ledger_path} has an invalid {engine!r} rule list"
            raise TypeError(msg)
        return (
            f"{len(entries)} active rules. Run `sarj-standards show rules` for the generated machine-readable catalog."
        )
    rows = ["| Family | Active rules |", "| --- | ---: |"]
    for key, label in (
        ("eslint", "TypeScript"),
        ("python", "Python"),
        ("sql", "SQL"),
        ("iac", "IaC"),
        ("text", "Text"),
    ):
        entries = groups.get(key)
        if not _is_object_list(entries):
            msg = f"{ledger_path} has an invalid {key!r} rule list"
            raise ValueError(msg)
        rows.append(f"| {label} | {len(entries)} |")
    return "\n".join(rows) + "\n\nRun `sarj-standards show rules` for the generated machine-readable catalog."


def _cli_reference(metadata: dict[str, object], *, registry: str) -> str:
    scripts = _scripts(metadata)
    if registry == "npm":
        rows = ["| Command |", "| --- |"]
        rows.extend(f"| `npm run {command}` |" for command in sorted(scripts))
        return "\n".join(rows)
    rows = ["| Command | Entrypoint | Help |", "| --- | --- | --- |"]
    for command, entrypoint in sorted(scripts.items()):
        rows.append(f"| `{command}` | `{entrypoint}` | `{command} --help` |")
    return "\n".join(rows)


def _scripts(metadata: dict[str, object]) -> dict[str, str]:
    value = metadata.get("scripts")
    if not _is_object_table(value):
        return {}
    scripts: dict[str, str] = {}
    for name, entrypoint in value.items():
        if not isinstance(entrypoint, str):
            msg = "manifest scripts must map command names to entrypoints"
            raise TypeError(msg)
        scripts[name] = entrypoint
    return scripts


def _links(metadata: dict[str, object]) -> str:
    raw = metadata.get("urls")
    if _is_object_table(raw):
        links = {label: value for label, value in raw.items() if isinstance(value, str)}
    else:
        links = {
            label: value
            for label, value in (("Homepage", metadata.get("homepage")), ("Repository", metadata.get("repository")))
            if isinstance(value, str)
        }
    return "\n".join(f"- [{label}]({url})" for label, url in sorted(links.items()))


def _license(metadata: dict[str, object]) -> str:
    value = metadata.get("license")
    if isinstance(value, str):
        return value
    if _is_object_table(value):
        text = value.get("text")
        if isinstance(text, str):
            return text
    return "Not declared"


def _runtime(metadata: dict[str, object]) -> str:
    python = metadata.get("requires-python")
    if isinstance(python, str):
        return f"Python {python}"
    engines = metadata.get("engines")
    if _is_object_table(engines):
        return ", ".join(f"{name} {version}" for name, version in sorted(engines.items()) if isinstance(version, str))
    return ""


def _author(metadata: dict[str, object]) -> str:
    author = metadata.get("author")
    if isinstance(author, str):
        return author
    if _is_object_table(author):
        name = author.get("name")
        if isinstance(name, str):
            return name
    return "Not declared"


def _markdown_title(path: Path) -> str:
    match = _HEADING.search(path.read_text(encoding="utf-8"))
    if match is None:
        msg = f"{path} has no Markdown title"
        raise ValueError(msg)
    return match.group(1)


def _validate_markdown_allowlist(root: Path) -> None:
    rejected: list[Path] = []
    for parent, directories, names in os.walk(root):
        directories[:] = sorted(name for name in directories if name not in _WALK_EXCLUDES)
        for name in sorted(names):
            path = Path(parent) / name
            if path.suffix.lower() in _DOCUMENT_SUFFIXES and not _allowed_document(path.relative_to(root)):
                rejected.append(path.relative_to(root))
    if rejected:
        msg = "documentation is not generated or executable-policy allowlisted: " + ", ".join(map(str, rejected))
        raise ValueError(msg)


def _allowed_document(relative: Path) -> bool:
    if relative in _GENERATED_READMES or relative in _EXECUTABLE_OR_LEGAL_DOCUMENTS:
        return True
    match relative.parts:
        case ("plugins", _plugin, "commands", filename):
            return filename.endswith(".md")
        case ("plugins", _plugin, "skills", _skill, "SKILL.md"):
            return True
        case ("plugins", _plugin, "skills", _skill, "references", filename):
            return filename.endswith(".md")
        case _:
            return False


def _documentation_paths(root: Path) -> tuple[Path, ...]:
    required = {
        *(root / path for path in _GENERATED_READMES),
        *(root / path for path in _EXECUTABLE_OR_LEGAL_DOCUMENTS),
    }
    maintained = {
        *root.glob("plugins/*/commands/*.md"),
        *root.glob("plugins/*/skills/*/SKILL.md"),
        *root.glob("plugins/*/skills/*/references/*.md"),
    }
    missing = [
        path for path in sorted(required) if not path.is_file() and path.relative_to(root) not in _GENERATED_READMES
    ]
    if missing:
        msg = f"required documentation is missing: {', '.join(str(path) for path in missing)}"
        raise ValueError(msg)
    return tuple(sorted(required | maintained))


def _validate_documents(documents: dict[Path, str]) -> None:
    for path, source in documents.items():
        _validate_local_links(path, source, documents)
        _validate_cli_examples(path, source)


def _validate_local_links(path: Path, source: str, documents: dict[Path, str]) -> None:
    for match in _LOCAL_LINK.finditer(source):
        relative, anchor = match.groups()
        target = (path.parent / relative).resolve() if relative else path
        generated_target = documents.get(target)
        if generated_target is None and not target.exists():
            msg = f"{path} links to missing local target {relative!r}"
            raise ValueError(msg)
        if anchor and target.suffix.lower() == ".md":
            target_source = generated_target if generated_target is not None else target.read_text(encoding="utf-8")
            headings = {_heading_slug(heading.group(1)) for heading in _HEADING.finditer(target_source)}
            if anchor not in headings:
                msg = f"{path} links to missing Markdown heading {anchor!r} in {relative or path.name!r}"
                raise ValueError(msg)


def _heading_slug(heading: str) -> str:
    normalized = re.sub(r"[^a-z0-9 -]", "", heading.lower()).replace(" ", "-")
    return re.sub(r"-+", "-", normalized)


def _validate_cli_examples(path: Path, source: str) -> None:
    for match in _STANDARDS_COMMAND.finditer(source):
        command = shlex.split(match.group(1))
        completed = subprocess.run(  # ruff: ignore[subprocess-without-shell-equals-true] -- fixed interpreter and argv.
            [sys.executable, "-m", "sarj_standards", *command[1:], "--help"],
            check=False,
            capture_output=True,
            text=True,
        )
        if completed.returncode != 0:
            msg = f"{path} contains an invalid command example: {match.group(1)!r}"
            raise ValueError(msg)


def _manifest(path: Path) -> dict[str, object]:
    if path.suffix == ".toml":
        document = tomllib.loads(path.read_text(encoding="utf-8"))
        project: object = document.get("project")
        if not _is_object_table(project):
            msg = f"{path} has no project table"
            raise ValueError(msg)
        return project
    document: object = json.loads(path.read_text(encoding="utf-8"))  # pyright: ignore[reportAny]
    if not _is_object_table(document):
        msg = f"{path} is not an object"
        raise TypeError(msg)
    return document


def _string(table: dict[str, object], key: str) -> str:
    value = table.get(key)
    if not isinstance(value, str) or not value:
        msg = f"manifest or catalog entry does not declare {key!r}"
        raise ValueError(msg)
    return value


def _title(name: str) -> str:
    return " ".join(part.capitalize() for part in name.replace("@", "").replace("/", " ").replace("-", " ").split())


def _cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def _is_object_table(value: object) -> TypeGuard[dict[str, object]]:
    return isinstance(value, dict)


def _is_object_list(value: object) -> TypeGuard[list[object]]:
    return isinstance(value, list)
