from __future__ import annotations

from dataclasses import dataclass
import os
from pathlib import Path
import re
import shlex
import subprocess  # ruff: ignore[suspicious-subprocess-import] -- validates fixed local CLI examples.
import sys
import tomllib
from typing import Final, TypeGuard

from sarj_standards.libs.adoption import transaction
from sarj_standards.libs.json_boundary import parse_json


_GENERATED_SENTINEL: Final = "<!-- Generated by `code-standards maintain docs sync`; do not edit. -->"
_LOCAL_LINK: Final = re.compile(r"\[[^]]+\]\((?!https?://|mailto:)([^)#]*)(?:#([^)]+))?\)")
_HEADING: Final = re.compile(r"^#{1,6}\s+(.+?)\s*#*\s*$", re.MULTILINE)
_STANDARDS_COMMAND: Final = re.compile(r"^\s*(code-standards(?:\s+.+)?)\s*$", re.MULTILINE)
_DOCUMENT_SUFFIXES: Final = frozenset({".md", ".mdx", ".rst"})
_WALK_EXCLUDES: Final = frozenset(
    {".git", ".mypy_cache", ".pytest_cache", ".ruff_cache", ".venv", "build", "coverage", "dist", "node_modules"}
)
_GENERATED_READMES: Final = (
    Path("README.md"),
    Path("packages/bootstrap/README.md"),
    Path("packages/contracts/README.md"),
    Path("packages/standards/README.md"),
    Path("packages/standards-compat/README.md"),
    Path("packages/python/README.md"),
    Path("packages/sql/README.md"),
    Path("packages/iac/README.md"),
    Path("packages/typescript/README.md"),
    Path("packages/tsconfig/README.md"),
    Path("plugins/sarj-audit/README.md"),
)
_GENERATED_SECURITY_POLICY: Final = Path(".github/SECURITY.md")
_EXECUTABLE_OR_LEGAL_DOCUMENTS: Final = (Path("AGENTS.md"),)
_PACKAGE_DEFINITIONS: Final = (
    ("packages/standards/pyproject.toml", "PyPI", "text"),
    ("packages/standards-compat/pyproject.toml", "PyPI", None),
    ("packages/bootstrap/pyproject.toml", "PyPI", None),
    ("packages/contracts/pyproject.toml", "PyPI", None),
    ("packages/python/pyproject.toml", "PyPI", "python"),
    ("packages/sql/pyproject.toml", "PyPI", "sql"),
    ("packages/iac/pyproject.toml", "PyPI", "iac"),
    ("packages/typescript/package.json", "npm", "eslint"),
    ("packages/tsconfig/package.json", "npm", None),
)
_DOCUMENTATION_URL: Final = "https://code-standards.sarj.ai/"


@dataclass(frozen=True, slots=True)
class DocumentationResult:
    changed: tuple[Path, ...]
    checked: tuple[Path, ...]

    @property
    def status(self) -> int:
        """Return a process-compatible status: one means generated drift."""
        return int(bool(self.changed))


def check(root: Path) -> DocumentationResult:
    return _update(root.resolve(), write=False)


def sync(root: Path) -> DocumentationResult:
    return _update(root.resolve(), write=True)


def _update(root: Path, *, write: bool) -> DocumentationResult:
    rendered = _render_readmes(root)
    _validate_markdown_allowlist(root)
    changed = tuple(
        path for path, content in rendered.items() if not path.is_file() or path.read_text(encoding="utf-8") != content
    )
    checked = _documentation_paths(root)
    _validate_documents(
        {**{path: path.read_text(encoding="utf-8") for path in checked if path not in rendered}, **rendered}
    )
    if write:
        for path in changed:
            transaction.atomic_write_text(root, path, rendered[path])
    return DocumentationResult(changed=changed, checked=checked)


def _render_readmes(root: Path) -> dict[Path, str]:
    packages = [
        (root / relative, registry, engine, _manifest(root / relative))
        for relative, registry, engine in _PACKAGE_DEFINITIONS
    ]
    rendered = {root / "README.md": _root_readme(root, packages)}
    for manifest_path, registry, engine, metadata in packages:
        rendered[manifest_path.parent / "README.md"] = _package_readme(root, manifest_path, registry, engine, metadata)
    rendered[root / "plugins/sarj-audit/README.md"] = _plugin_readme(root)
    rendered[root / _GENERATED_SECURITY_POLICY] = _security_policy()
    return dict(sorted(rendered.items()))


def _root_readme(
    _root: Path,
    packages: list[tuple[Path, str, str | None, dict[str, object]]],
) -> str:
    standards = packages[0][3]
    title = _title(_string(standards, "name"))
    sections = [
        _GENERATED_SENTINEL,
        f"# {title}",
        _string(standards, "description"),
        (
            "Every repository receives one complete policy, including all 41 library policies. "
            "There is no standard/application selection. Legacy profile fields and preset filenames remain "
            "read-compatible aliases; newly written manifests omit the profile field. "
            "Warning-stage rules retain their reviewed severity. Rules requiring repository-specific "
            "boundaries still require those explicit options."
        ),
        (
            "Adopt the complete policy, local hooks, and CI with one command:\n\n"
            "```bash\n"
            "uvx --no-config --isolated --python 3.15 --from code-standards code-standards setup\n"
            "```\n\n"
            "The canonical staged check includes semantic lint and repository policy; do not install a "
            "second Repo Standards hook."
        ),
        (
            "## Contributing\n\n"
            "Install uv 0.12.24, Python 3.15, Node 24.21, and GNU Make. Then bootstrap a fresh checkout:\n\n"
            "```bash\nmake setup\nmake verify\n```"
            "\n\nRun independent package suites with `make test -j4`, or focus on the fresh Standards wheel "
            "with `make test-standards PYTEST_ARGS='-k release'`. `TEST_JOBS=1` serializes wheel tests "
            "(default: 4, maximum: 16). Wheel tests build local exact sibling versions in a temporary "
            "wheelhouse and leave existing distribution output intact. Use `make release-status COMMIT=origin/main` "
            "to inspect exact-revision checks, publication, tagging, and rollout with queue and job durations. "
            "Preview affected test files with `make test-plan BASE=origin/main`, then run them against fresh "
            "local wheels with `make test-standards-changed BASE=origin/main`. Ordinary PR and main CI select "
            "affected packages and test cohorts; shared code, dependencies, workflows, missing comparisons, "
            "unknown paths, and uncertified comparison bases fall back to full coverage. Manual and weekly CI run every package and test. "
            "Test plans record selected files, fallback reasons, and elapsed time in the job summary."
            "\n\nOn main, CI can reuse successful own-repository PR validation only when the checked Git tree "
            "and comparison base are identical. The verifier requires the latest successful CI run, matching "
            "run attempt, successful job, immutable artifact digest, and checked-tree certificate less than "
            "24 hours old. It preserves the tested wheel bytes and submits reviewed CodeQL results for "
            "the actual main commit. Documentation source checks can be reused, while main builds and "
            "deploys the site afresh. Missing, expired, malformed, forked, changed or uncertified proofs "
            "fall back to fresh checks; PR, weekly and manual runs always perform fresh validation. "
            "The job summary links the source CI and explains reuse or fallback."
            "\n\nPublication reuses the successful exact-main CI artifact after checking its repository, event, "
            "commit, job result, and archive digest; missing/expired artifacts receive a fresh build and full "
            "wheel suite. Consumer portability repeats when shared runtime code can be affected. "
            "CLI smoke tests and a fresh revision-local pre-commit installation run concurrently; "
            "either failure blocks publication, and a second hook run must reuse its environment. "
            "Reproduce both lanes with `make release-portability`; CI retains separate logs and timings. "
            "Release detection uses the exact source-owned bootstrap pins without installing lint engines. "
            "Documentation deployment uses a separate locked Wrangler toolchain; reproduce its dry run "
            "with `make docs-deploy-check` after building the site. "
            "The underlying `maintain release status --commit REV --format json` command provides JSON. "
            "Release builds and portability checks overlap safety checks; publication still requires "
            "every check, exact public sibling version, verified artifact digest, and trusted-publisher attestation."
            "\n\nCreate a rule with `maintain rules new ENGINE:ID --category CATEGORY --summary TEXT --apply`. "
            "Without `--apply`, the command shows its plan. Creation writes the detector and executable test, "
            "registers the rule, and reserves its identifier atomically. New rules default to warning. "
            "Run authoring commands through `uv run --project packages/standards --frozen code-standards` "
            "to use the source and dependencies of the checkout being edited. Implement the detector and "
            "replace the example placeholders, then verify and prepare it:\n\n"
            "```bash\n"
            "code-standards --root . maintain rules verify python:no-string-concat-in-loop\n"
            "code-standards --root . maintain rules prepare python:no-string-concat-in-loop\n"
            "code-standards --root . maintain rules evaluate --rule python:no-string-concat-in-loop --scope corpus\n"
            "make verify\n"
            "```\n\nFor reproducible multi-repository calibration, use an immutable public manifest and an optional "
            "owner-readable private overlay:\n\n"
            "```bash\n"
            "code-standards --root . maintain rules evaluate --rule python:no-string-concat-in-loop "
            "--corpus-manifest corpora.toml --private-overlay private-corpora.toml\n"
            "```\n\nAfter committing the resulting changes, review the complete rule diff:\n\n"
            "```bash\n"
            "code-standards --root . maintain rules changes --before origin/main --after HEAD\n"
            "```\n\n"
            "Rule comparison reads immutable Git blobs and fingerprints explicit local runtime imports "
            "from source and test modules. Type-only imports and data-only registry member edges are excluded; "
            "computed imports and TypeScript path aliases are not resolved. For TypeScript-bearing revisions, "
            "run `make setup` first to prepare the pinned Node and locked compiler in the authoring repository. "
            "Comparison never installs tools or falls back to text matching. Python-only revisions do not require Node.\n\n"
            "Fleet calibration and downstream PR creation run automatically after review and release.\n\n"
            "### Fleet rollout\n\n"
            "Copy `.sarj-standards-rollout.example.toml` to the ignored `.sarj-standards-rollout.toml` "
            "and register authorized consumers. Use an exact published bundle version:\n\n"
            "```bash\n"
            "make rollout-plan VERSION=<published-version>\n"
            "make rollout-check VERSION=<published-version>\n"
            "make rollout VERSION=<published-version>\n"
            "make rollout-status VERSION=<published-version>\n"
            "```\n\n"
            "Add `CONSUMER=owner/repository@branch` to inspect or retry one consumer, `DRY_RUN=1` "
            "to preview an apply, and `JOBS=1` to serialize local work (default: 4). "
            "`make rollout-reconcile` resolves the latest published bundle when VERSION is omitted. "
            "`make rollout-check` verifies the published CLI and immutable source tag without a consumer registry. "
            "Consumer installs refresh only Code Standards metadata and retry a newly published version's "
            "index visibility with up to six 10-second waits; other install errors fail immediately. "
            "The planner briefly waits for a new tag to become visible after PyPI publication. "
            "Canary, early, and stable waves advance only after earlier waves merge; targeted retries "
            "retain that gate. The apply command reports PR creation independently of adoption.\n\n"
            "Hosted reconciliation runs every 15 minutes and starts jobs only for consumers requiring work. "
            "Open verified PRs wait for their existing approvals. Pending adoption appears as pending "
            "in the durable issue; verification and transport failures still fail the workflow. "
            "Status exits 0 for complete adoption, 1 for pending adoption, and 2 for blocked or failed reads. "
            "Progress goes to stderr; stdout stays JSON with elapsedSeconds per consumer. "
            "The controller accepts `--jobs` (1 to 16) and `--command-timeout` "
            "(seconds, default: 900) before its subcommand. "
            "Registry consumers may opt into `partial_clone = true` when verification uses the checkout "
            "and its base. Full clones remain the default for verification that reads arbitrary history.\n\n"
            "On POSIX hosts, preparation and verification check the remote base every 10 seconds with a bounded read. "
            "Confirmed movement cancels the candidate's dependency update, baseline, bootstrap, or verification processes, preserves their log tails, "
            "and leaves that consumer pending for reconciliation from the new base. Unavailable remote "
            "evidence does not cancel consumer work. Stable candidates still run every registered check, "
            "and independent base checks remain required before publication. Other hosts retain the "
            "existing verification runner and base checks. Bounded structured timings from consumer verifiers "
            "appear in progress logs so slow phases can be measured without changing test coverage.\n\n"
            "### Rule implementation\n\n"
            "`sarj-rule-contracts` owns immutable metadata and executable example contracts. Each rule owns its "
            "documentation and positive/negative examples; generated catalogs and docs consume those declarations. "
            "Verification executes all examples, including private and multi-file cases, with the owning engine "
            "and runs the focused test file. A detector that always reports or never reports fails. "
            "TypeScript examples can also verify fixes and a clean second pass. Examples for opt-in rules "
            "declare fixture-specific `ruleOptions`, preserving consumer defaults. External declarations "
            "use `installedDependencies` with exact package names and versions. Run `make setup` first; "
            "the repository verifier supplies the installed TypeScript package root. Standalone "
            "`verifyRuleExamples` callers supply `{ installedDependencyRoot }` for such examples. "
            "Verification installs nothing and fails for missing packages or identity/version drift.\n\n"
            "Python rules implement `check_context(context: PythonFileContext)`. The context shares parsing, "
            "breadth-first node indexing, parent lookup, import resolution, and generated-file detection across rules "
            "for one file. Use `context.parents.get(node)` to find a node's parent without rebuilding a map. "
            "Project discovery belongs to the analysis session; file facts expire after that file. "
            "The existing `check(path, source)` entrypoint delegates through a fresh context. SQL, IaC, "
            "and text retain their own parsers and diagnostics.\n\n"
            "Native Python directory inputs prune dependency and cache trees before scanning them, and return "
            "files in sorted order. Explicit file arguments retain their supplied order.\n\n"
            "Measure native Python analysis and diagnostic stability with:\n\n"
            "```bash\n"
            "code-standards --root . maintain rules bench packages/python/src --repeats 5\n"
            "```\n\n"
            "The JSON report includes file and byte counts, source and diagnostic digests, per-run timings, "
            "and process peak memory. It excludes interpreter startup; peak memory is the process high-water mark. "
            "Use fresh processes for cold-start and independent memory comparisons.\n\n"
            "### Rule artifact provenance\n\n"
            "- Each rule's source-owned `default_level` is lifecycle policy. Severity is a reviewed decision, "
            "not something inferred from current findings.\n"
            "- `rule-inventory.v1.json` and `rule-catalog.v1.json` are committed package/runtime projections "
            "of live registries and source-owned documentation. Check or regenerate them with "
            "`maintain rules check|sync` and `maintain catalog check|sync`.\n"
            "- `rule-ledger.json` combines generated live identifiers with curated rename and retirement "
            "history; synchronize it with `maintain sync-ledger`.\n"
            "- `rule-calibration-campaign.v1.json` is curated review evidence, not generated configuration.\n"
            "- `cli-reference.v1.json` is generated from the parser graph with "
            "`maintain cli-reference check|sync`."
        ),
        f"[Documentation]({_DOCUMENTATION_URL}) · [Source]({_source_url(standards)})",
    ]
    return "\n\n".join(sections) + "\n"


def _package_readme(
    _root: Path,
    _manifest_path: Path,
    registry: str,
    engine: str | None,
    metadata: dict[str, object],
) -> str:
    name = _string(metadata, "name")
    sections = [
        _GENERATED_SENTINEL,
        f"# {name}",
        _string(metadata, "description"),
        f"```bash\n{_install_command(name, registry)}\n```",
        _package_usage(name, engine),
        f"[Documentation]({_homepage(metadata)}) · [Source]({_source_url(metadata)})",
    ]
    return "\n\n".join(sections) + "\n"


def _package_usage(name: str, engine: str | None) -> str:
    if name == "code-standards":
        return (
            "Adopt the repository once with `code-standards setup`. It installs one canonical staged gate "
            "that includes semantic lint and repository policy, plus commit-message and pull-request history "
            "enforcement. Do not install Repo Standards separately.\n\n"
            "```bash\n"
            "code-standards setup\n"
            "code-standards check\n"
            "code-standards check --rule python:no-excessive-cognitive-complexity src/\n"
            "code-standards fix\n"
            "code-standards doctor\n"
            "code-standards update\n"
            "```\n\n"
            "Use repeatable `check --rule ENGINE:ID` selectors to select native rules, ESLint rules, or managed security audits. "
            "Exclusions, baselines, and severities still apply; Ruff selectors are not supported. "
            "Native linters and ESLint execute only selected rules. ESLint retains configured parsers, options, "
            "severities, and suppression directives.\n\n"
            "Terraform, Kubernetes, and GitHub Actions adoption adds isolated Checkov 3.3.20 and zizmor 1.30.1 "
            "runtimes. Setup and generated CI prewarm these tools; checks run offline with packaged policy. "
            "Use `--rule checkov:CKV_GCP_95` or `--rule zizmor:template-injection` to select upstream audits. "
            "Their findings start as warnings, use the canonical diagnostic baseline, and retain upstream IDs. "
            "Checkov honors its inline suppression directives; zizmor ignore comments are disabled. "
            "Explicit zizmor selectors include auditor-persona checks; online-only audits cannot run offline. "
            "Parsing or execution failures leave the analysis incomplete. Image digest evidence for source templates "
            "is deferred to their rendered deployment artifacts.\n\n"
            "The opt-in `jscpd` capability runs the jscpd 5.4.0 copy-paste detector, which setup installs "
            "through mise. Setup and upgrades list it in `[capabilities].disable`; remove it there to enable it. "
            "Each check scans Python, TypeScript, Swift and Kotlin source outside test directories, because a "
            "copy can only be found by comparing it with the whole tree. Every repeated block of at least 50 "
            "tokens is a `jscpd:duplicate-code` warning on its own lines that names the other copies, so the "
            "changed-line baseline reports it when either side is edited. The repository's own jscpd "
            "configuration is ignored.\n\n"
            "`check --jobs 2` overlaps native analysis with the external-tool pipeline. The default is "
            "`--jobs 1`; external tools remain sequential and report ordering is deterministic.\n\n"
            "DevOps execution blocks must contain one invocation. Move interpreter source, command chains, "
            "loops, substitutions and heredocs into independently linted files; Python `-m` and script paths, "
            "and jq/awk `-f` files remain supported. SARJ310 is an error, including short inline programs. "
            "Cloud Build SARJ315 checks unique IDs, ordered step dependencies, script/argv exclusivity and rejects untrusted substitutions in "
            "shell source; pass substitutions as quoted arguments to external scripts.\n\n"
            "The source gate uses pinned actionlint with ShellCheck, offline Zizmor, Hadolint and Skaffold "
            "v4beta7 schema validation. Cloud Deploy validation is a documented partial structural contract. "
            "Terraform validation and TFLint require explicit repository trust and prepared local providers; "
            "analysis never initializes or downloads them. Compose requires an exact consumer "
            "`[devops].compose_version`; its source check does not resolve environment inputs.\n\n"
            "Release gates use `code-standards analyze --prepared-only --prepared-devops prepared.json "
            "--prepared-target TARGET_ID`. Declare exact `prepared_targets` under `[devops]` with an authored "
            "`source` path. Version-one receipts bind target IDs, authored input hashes, staged chart archives, "
            "ordered values, typed set arguments, manifests and a hashed local schema closure. Helm 3.19.0 "
            "strict lint and stage-specific rendering feed kubeconform 0.8.0 and kube-linter 0.8.3. Missing "
            "tools, schemas, targets and invalid receipts fail the gate. Prepared-only findings bypass "
            "source debt baselines; container exceptions require exact target, GVK, namespace, object, "
            "check, container kind, container name and a reason, and stale exceptions fail.\n\n"
            "Source-only checks report prepared validation as deferred. They do not certify generated "
            "manifests or replace Cloud Deploy, Cloud Build or Kubernetes admission validation. "
            "Run `setup --tools-only` in CI after installing the bundle and the pinned mise bootstrap. "
            "It requires an existing manifest, installs and attests the applicable native tools, and preserves "
            "repository wiring. Release analysis consumes prepared bytes without pulling charts."
        )
    if name == "sarj-rule-contracts":
        return (
            "Standard-library-only immutable contracts for rule documentation, metadata, and executable examples. "
            "Native engines and the Standards catalog share these declarations. Language parsers, analysis "
            "contexts, diagnostics, and suppression policies belong to their engines."
        )
    if name == "sarj-standards":
        return (
            "Compatibility bridge for existing exact launchers after the distribution was renamed to "
            "`code-standards`. New installations should use `code-standards` directly."
        )
    if name == "sarj-standards-bootstrap":
        return (
            "Generated CI and hooks use this lightweight bootstrap without repeating a version pin. "
            "It reads the exact Standards bundle version from `.sarj-standards.toml`; ordinary Standards "
            "upgrades change only that manifest. No mise integration or repository-local launcher is needed.\n\n"
            "```bash\n"
            "uvx --no-config --isolated --python 3.15 --from "
            "sarj-standards-bootstrap code-standards check\n"
            "```\n\n"
            "uvx installs and caches the bootstrap on first use, then reuses it without requesting a refresh "
            "on every hook invocation. The bootstrap itself is not version-pinned; the linting bundle is. "
            "Offline execution requires a warmed cache for both the bootstrap and the selected bundle, "
            "including their Python runtime and dependencies.\n\n"
            "The bootstrap deliberately inherits UV/PIP registry, proxy, certificate, cache, and offline environment "
            "policy. `--no-config --isolated` prevents consumer project configuration and installed tools from "
            "changing the selected bootstrap or Standards bundle."
        )
    executable = (
        None
        if engine is None
        else {
            "python": "sarj-python-lint",
            "sql": "sarj-sql-lint",
            "iac": "sarj-iac-lint",
        }.get(engine)
    )
    if executable is None:
        return "Rules and configuration are documented in the generated rule directory."
    return f"```bash\n{executable} --help\n```"


def _plugin_readme(root: Path) -> str:
    manifest_path = root / "plugins/sarj-audit/.claude-plugin/plugin.json"
    metadata = _manifest(manifest_path)
    sections = [
        _GENERATED_SENTINEL,
        f"# {_title(_string(metadata, 'name'))}",
        _string(metadata, "description"),
        f"[Documentation]({_DOCUMENTATION_URL}) · [Source](https://github.com/sarj-ai/code-standards/tree/main/plugins/sarj-audit)",
    ]
    return "\n\n".join(sections) + "\n"


def _security_policy() -> str:
    sections = [
        _GENERATED_SENTINEL,
        "# Security",
        (
            "Report vulnerabilities privately through the "
            "[GitHub security advisory form]"
            "(https://github.com/sarj-ai/code-standards/security/advisories/new). "
            "Do not open a public issue for an undisclosed vulnerability."
        ),
        (
            "The default branch and latest published version of each package receive security fixes. "
            "Maintainers will acknowledge a report within two business days and coordinate disclosure after a fix."
        ),
    ]
    return "\n\n".join(sections) + "\n"


def _install_command(name: str, registry: str) -> str:
    if name == "sarj-rule-contracts":
        return f"uv add {name}"
    if registry == "npm":
        return f"npm install --save-dev {name}"
    python = " --python 3.15" if name == "code-standards" else ""
    return f"uv tool install{python} {name}"


def _homepage(metadata: dict[str, object]) -> str:
    urls = metadata.get("urls")
    value = urls.get("Homepage") if _is_object_table(urls) else metadata.get("homepage")
    return value if isinstance(value, str) and value else _DOCUMENTATION_URL


def _source_url(metadata: dict[str, object]) -> str:
    urls = metadata.get("urls")
    value: object = urls.get("Repository") if _is_object_table(urls) else metadata.get("repository")
    if _is_object_table(value):
        value = value.get("url")
    if not isinstance(value, str) or not value:
        return "https://github.com/sarj-ai/code-standards"
    return value.removeprefix("git+").removesuffix(".git")


def _validate_markdown_allowlist(root: Path) -> None:
    rejected: list[Path] = []
    for parent, directories, names in os.walk(root):
        directories[:] = sorted(name for name in directories if name not in _WALK_EXCLUDES)
        for name in sorted(names):
            path = Path(parent) / name
            if path.suffix.lower() in _DOCUMENT_SUFFIXES and not _allowed_document(path.relative_to(root)):
                rejected.append(path.relative_to(root))
    if rejected:
        msg = "documentation is not generated or executable-policy allowlisted: " + ", ".join(map(str, rejected))
        raise ValueError(msg)


def _allowed_document(relative: Path) -> bool:
    if (
        relative in _GENERATED_READMES
        or relative == _GENERATED_SECURITY_POLICY
        or relative in _EXECUTABLE_OR_LEGAL_DOCUMENTS
    ):
        return True
    match relative.parts:
        case ("plugins", _plugin, "commands", filename):
            return filename.endswith(".md")
        case ("plugins", _plugin, "skills", _skill, "SKILL.md"):
            return True
        case ("plugins", _plugin, "skills", _skill, "references", filename):
            return filename.endswith(".md")
        case _:
            return False


def _documentation_paths(root: Path) -> tuple[Path, ...]:
    required = {
        *(root / path for path in _GENERATED_READMES),
        root / _GENERATED_SECURITY_POLICY,
        *(root / path for path in _EXECUTABLE_OR_LEGAL_DOCUMENTS),
    }
    maintained = {
        *root.glob("plugins/*/commands/*.md"),
        *root.glob("plugins/*/skills/*/SKILL.md"),
        *root.glob("plugins/*/skills/*/references/*.md"),
    }
    missing = [
        path
        for path in sorted(required)
        if not path.is_file()
        and path.relative_to(root) not in _GENERATED_READMES
        and path.relative_to(root) != _GENERATED_SECURITY_POLICY
    ]
    if missing:
        msg = f"required documentation is missing: {', '.join(str(path) for path in missing)}"
        raise ValueError(msg)
    return tuple(sorted(required | maintained))


def _validate_documents(documents: dict[Path, str]) -> None:
    for path, source in documents.items():
        _validate_local_links(path, source, documents)
        _validate_cli_examples(path, source)


def _validate_local_links(path: Path, source: str, documents: dict[Path, str]) -> None:
    for match in _LOCAL_LINK.finditer(source):
        relative, anchor = match.groups()
        target = (path.parent / relative).resolve() if relative else path
        generated_target = documents.get(target)
        if generated_target is None and not target.exists():
            msg = f"{path} links to missing local target {relative!r}"
            raise ValueError(msg)
        if anchor and target.suffix.lower() == ".md":
            target_source = generated_target if generated_target is not None else target.read_text(encoding="utf-8")
            headings = {_heading_slug(heading.group(1)) for heading in _HEADING.finditer(target_source)}
            if anchor not in headings:
                msg = f"{path} links to missing Markdown heading {anchor!r} in {relative or path.name!r}"
                raise ValueError(msg)


def _heading_slug(heading: str) -> str:
    normalized = re.sub(r"[^a-z0-9 -]", "", heading.lower()).replace(" ", "-")
    return re.sub(r"-+", "-", normalized)


def _validate_cli_examples(path: Path, source: str) -> None:
    for match in _STANDARDS_COMMAND.finditer(source):
        command = shlex.split(match.group(1))
        completed = subprocess.run(  # ruff: ignore[subprocess-without-shell-equals-true] -- fixed interpreter and argv.
            [sys.executable, "-m", "sarj_standards", *command[1:], "--help"],
            check=False,
            capture_output=True,
            text=True,
        )
        if completed.returncode != 0:
            msg = f"{path} contains an invalid command example: {match.group(1)!r}"
            raise ValueError(msg)


def _manifest(path: Path) -> dict[str, object]:
    if path.suffix == ".toml":
        document = tomllib.loads(path.read_text(encoding="utf-8"))
        project: object = document.get("project")
        if not _is_object_table(project):
            msg = f"{path} has no project table"
            raise ValueError(msg)
        return project
    document: object = parse_json(path.read_text(encoding="utf-8"))
    if not _is_object_table(document):
        msg = f"{path} is not an object"
        raise TypeError(msg)
    return document


def _string(table: dict[str, object], key: str) -> str:
    value = table.get(key)
    if not isinstance(value, str) or not value:
        msg = f"manifest or catalog entry does not declare {key!r}"
        raise ValueError(msg)
    return value


def _title(name: str) -> str:
    return " ".join(part.capitalize() for part in name.replace("@", "").replace("/", " ").replace("-", " ").split())


def _is_object_table(value: object) -> TypeGuard[dict[str, object]]:
    return isinstance(value, dict)
