from __future__ import annotations

from dataclasses import dataclass
import json
import os
from pathlib import Path
import re
import shlex
import subprocess  # ruff: ignore[suspicious-subprocess-import] -- validates fixed local CLI examples.
import sys
import tomllib
from typing import Final, TypeGuard

from sarj_standards.libs.adoption import transaction


_GENERATED_SENTINEL: Final = "<!-- Generated by `code-standards maintain docs sync`; do not edit. -->"
_LOCAL_LINK: Final = re.compile(r"\[[^]]+\]\((?!https?://|mailto:)([^)#]*)(?:#([^)]+))?\)")
_HEADING: Final = re.compile(r"^#{1,6}\s+(.+?)\s*#*\s*$", re.MULTILINE)
_STANDARDS_COMMAND: Final = re.compile(r"^\s*(code-standards(?:\s+.+)?)\s*$", re.MULTILINE)
_DOCUMENT_SUFFIXES: Final = frozenset({".md", ".mdx", ".rst"})
_WALK_EXCLUDES: Final = frozenset(
    {".git", ".mypy_cache", ".pytest_cache", ".ruff_cache", ".venv", "build", "coverage", "dist", "node_modules"}
)
_GENERATED_READMES: Final = (
    Path("README.md"),
    Path("packages/bootstrap/README.md"),
    Path("packages/standards/README.md"),
    Path("packages/standards-compat/README.md"),
    Path("packages/python/README.md"),
    Path("packages/sql/README.md"),
    Path("packages/iac/README.md"),
    Path("packages/typescript/README.md"),
    Path("packages/tsconfig/README.md"),
    Path("plugins/sarj-audit/README.md"),
)
_GENERATED_SECURITY_POLICY: Final = Path(".github/SECURITY.md")
_EXECUTABLE_OR_LEGAL_DOCUMENTS: Final = (Path("AGENTS.md"), Path("CLAUDE.md"))
_PACKAGE_DEFINITIONS: Final = (
    ("packages/standards/pyproject.toml", "PyPI", "text"),
    ("packages/standards-compat/pyproject.toml", "PyPI", None),
    ("packages/bootstrap/pyproject.toml", "PyPI", None),
    ("packages/python/pyproject.toml", "PyPI", "python"),
    ("packages/sql/pyproject.toml", "PyPI", "sql"),
    ("packages/iac/pyproject.toml", "PyPI", "iac"),
    ("packages/typescript/package.json", "npm", "eslint"),
    ("packages/tsconfig/package.json", "npm", None),
)
_DOCUMENTATION_URL: Final = "https://code-standards.sarj.ai/"


@dataclass(frozen=True, slots=True)
class DocumentationResult:
    changed: tuple[Path, ...]
    checked: tuple[Path, ...]

    @property
    def status(self) -> int:
        """Return a process-compatible status: one means generated drift."""
        return int(bool(self.changed))


def check(root: Path) -> DocumentationResult:
    return _update(root.resolve(), write=False)


def sync(root: Path) -> DocumentationResult:
    return _update(root.resolve(), write=True)


def _update(root: Path, *, write: bool) -> DocumentationResult:
    rendered = _render_readmes(root)
    _validate_markdown_allowlist(root)
    changed = tuple(
        path for path, content in rendered.items() if not path.is_file() or path.read_text(encoding="utf-8") != content
    )
    checked = _documentation_paths(root)
    _validate_documents(
        {**{path: path.read_text(encoding="utf-8") for path in checked if path not in rendered}, **rendered}
    )
    if write:
        for path in changed:
            transaction.atomic_write_text(root, path, rendered[path])
    return DocumentationResult(changed=changed, checked=checked)


def _render_readmes(root: Path) -> dict[Path, str]:
    packages = [
        (root / relative, registry, engine, _manifest(root / relative))
        for relative, registry, engine in _PACKAGE_DEFINITIONS
    ]
    rendered = {root / "README.md": _root_readme(root, packages)}
    for manifest_path, registry, engine, metadata in packages:
        rendered[manifest_path.parent / "README.md"] = _package_readme(root, manifest_path, registry, engine, metadata)
    rendered[root / "plugins/sarj-audit/README.md"] = _plugin_readme(root)
    rendered[root / _GENERATED_SECURITY_POLICY] = _security_policy()
    return dict(sorted(rendered.items()))


def _root_readme(
    root: Path,
    packages: list[tuple[Path, str, str | None, dict[str, object]]],
) -> str:
    del root
    standards = packages[0][3]
    title = _title(_string(standards, "name"))
    sections = [
        _GENERATED_SENTINEL,
        f"# {title}",
        _string(standards, "description"),
        (
            "Every repository receives one complete policy, including all 41 library policies. "
            "There is no standard/application selection. Legacy profile fields and preset filenames remain "
            "read-compatible aliases; newly written manifests omit the profile field. "
            "Warning-stage rules retain their reviewed severity. Rules requiring repository-specific "
            "boundaries still require those explicit options."
        ),
        "```bash\nuv tool install --python 3.14 code-standards\n```",
        (
            "## Contributing\n\n"
            "Install uv 0.12.5, Python 3.14, Node 24.19, and GNU Make. Then bootstrap a fresh checkout:\n\n"
            "```bash\nmake setup\nmake verify\n```"
            "\n\nOnce a new rule and its tests are registered, stage it as a warning and validate it locally:\n\n"
            "```bash\n"
            "code-standards --root . maintain rules stage-warning python:no-string-concat-in-loop\n"
            "code-standards --root . maintain rules evaluate --rule python:no-string-concat-in-loop --scope corpus\n"
            "make verify\n"
            "```\n\nFor reproducible multi-repository calibration, use an immutable public manifest and an optional "
            "owner-readable private overlay:\n\n"
            "```bash\n"
            "code-standards --root . maintain rules evaluate --rule python:no-string-concat-in-loop "
            "--corpus-manifest corpora.toml --private-overlay private-corpora.toml\n"
            "```\n\nAfter committing the resulting changes, review the complete rule diff:\n\n"
            "```bash\n"
            "code-standards --root . maintain rules changes --before origin/main --after HEAD\n"
            "```\n\n"
            "Fleet calibration and downstream PR creation run automatically after review and release.\n\n"
            "### Rule artifact provenance\n\n"
            "- `rule-warning-levels.v1.json` is authored lifecycle policy. Severity is a reviewed decision, "
            "not something inferred from current findings.\n"
            "- `rule-inventory.v1.json` and `rule-catalog.v1.json` are committed package/runtime projections "
            "of live registries and source-owned documentation. Check or regenerate them with "
            "`maintain rules check|sync` and `maintain catalog check|sync`.\n"
            "- `rule-ledger.json` combines generated live identifiers with curated rename and retirement "
            "history; synchronize it with `maintain sync-ledger`.\n"
            "- `rule-calibration-campaign.v1.json` is curated review evidence, not generated configuration.\n"
            "- `cli-reference.v1.json` is generated from the parser graph with "
            "`maintain cli-reference check|sync`."
        ),
        f"[Documentation]({_DOCUMENTATION_URL}) · [Source]({_source_url(standards)})",
    ]
    return "\n\n".join(sections) + "\n"


def _package_readme(
    root: Path,
    manifest_path: Path,
    registry: str,
    engine: str | None,
    metadata: dict[str, object],
) -> str:
    del root, manifest_path
    name = _string(metadata, "name")
    sections = [
        _GENERATED_SENTINEL,
        f"# {name}",
        _string(metadata, "description"),
        f"```bash\n{_install_command(name, registry)}\n```",
        _package_usage(name, engine),
        f"[Documentation]({_homepage(metadata)}) · [Source]({_source_url(metadata)})",
    ]
    return "\n\n".join(sections) + "\n"


def _package_usage(name: str, engine: str | None) -> str:
    if name == "code-standards":
        return (
            "Use it from pre-commit with a coding agent so violations are flagged and fixed before commit.\n\n"
            "```bash\n"
            "code-standards setup\n"
            "code-standards check\n"
            "code-standards fix\n"
            "code-standards doctor\n"
            "code-standards update\n"
            "```"
        )
    if name == "sarj-standards":
        return (
            "Compatibility bridge for existing exact launchers after the distribution was renamed to "
            "`code-standards`. New installations should use `code-standards` directly."
        )
    if name == "sarj-standards-bootstrap":
        return (
            "Generated CI and hooks use this lightweight bootstrap without repeating a version pin. "
            "It reads the exact Standards bundle version from `.sarj-standards.toml`; ordinary Standards "
            "upgrades change only that manifest. No mise integration or repository-local launcher is needed.\n\n"
            "```bash\n"
            "uvx --no-config --isolated --python 3.14 --from "
            "sarj-standards-bootstrap code-standards check\n"
            "```\n\n"
            "uvx installs and caches the bootstrap on first use, then reuses it without requesting a refresh "
            "on every hook invocation. The bootstrap itself is not version-pinned; the linting bundle is. "
            "Offline execution requires a warmed cache for both the bootstrap and the selected bundle, "
            "including their Python runtime and dependencies.\n\n"
            "The bootstrap deliberately inherits UV/PIP registry, proxy, certificate, cache, and offline environment "
            "policy. `--no-config --isolated` prevents consumer project configuration and installed tools from "
            "changing the selected bootstrap or Standards bundle."
        )
    executable = (
        None
        if engine is None
        else {
            "python": "sarj-python-lint",
            "sql": "sarj-sql-lint",
            "iac": "sarj-iac-lint",
        }.get(engine)
    )
    if executable is None:
        return "Rules and configuration are documented in the generated rule directory."
    return f"```bash\n{executable} --help\n```"


def _plugin_readme(root: Path) -> str:
    manifest_path = root / "plugins/sarj-audit/.claude-plugin/plugin.json"
    metadata = _manifest(manifest_path)
    sections = [
        _GENERATED_SENTINEL,
        f"# {_title(_string(metadata, 'name'))}",
        _string(metadata, "description"),
        f"[Documentation]({_DOCUMENTATION_URL}) · [Source](https://github.com/sarj-ai/code-standards/tree/main/plugins/sarj-audit)",
    ]
    return "\n\n".join(sections) + "\n"


def _security_policy() -> str:
    sections = [
        _GENERATED_SENTINEL,
        "# Security",
        (
            "Report vulnerabilities privately through the "
            "[GitHub security advisory form]"
            "(https://github.com/sarj-ai/code-standards/security/advisories/new). "
            "Do not open a public issue for an undisclosed vulnerability."
        ),
        (
            "The default branch and latest published version of each package receive security fixes. "
            "Maintainers will acknowledge a report within two business days and coordinate disclosure after a fix."
        ),
    ]
    return "\n\n".join(sections) + "\n"


def _install_command(name: str, registry: str) -> str:
    if registry == "npm":
        return f"npm install --save-dev {name}"
    python = " --python 3.14" if name == "code-standards" else ""
    return f"uv tool install{python} {name}"


def _homepage(metadata: dict[str, object]) -> str:
    urls = metadata.get("urls")
    value = urls.get("Homepage") if _is_object_table(urls) else metadata.get("homepage")
    return value if isinstance(value, str) and value else _DOCUMENTATION_URL


def _source_url(metadata: dict[str, object]) -> str:
    urls = metadata.get("urls")
    value: object = urls.get("Repository") if _is_object_table(urls) else metadata.get("repository")
    if _is_object_table(value):
        value = value.get("url")
    if not isinstance(value, str) or not value:
        return "https://github.com/sarj-ai/code-standards"
    return value.removeprefix("git+").removesuffix(".git")


def _validate_markdown_allowlist(root: Path) -> None:
    rejected: list[Path] = []
    for parent, directories, names in os.walk(root):
        directories[:] = sorted(name for name in directories if name not in _WALK_EXCLUDES)
        for name in sorted(names):
            path = Path(parent) / name
            if path.suffix.lower() in _DOCUMENT_SUFFIXES and not _allowed_document(path.relative_to(root)):
                rejected.append(path.relative_to(root))
    if rejected:
        msg = "documentation is not generated or executable-policy allowlisted: " + ", ".join(map(str, rejected))
        raise ValueError(msg)


def _allowed_document(relative: Path) -> bool:
    if (
        relative in _GENERATED_READMES
        or relative == _GENERATED_SECURITY_POLICY
        or relative in _EXECUTABLE_OR_LEGAL_DOCUMENTS
    ):
        return True
    match relative.parts:
        case ("plugins", _plugin, "commands", filename):
            return filename.endswith(".md")
        case ("plugins", _plugin, "skills", _skill, "SKILL.md"):
            return True
        case ("plugins", _plugin, "skills", _skill, "references", filename):
            return filename.endswith(".md")
        case _:
            return False


def _documentation_paths(root: Path) -> tuple[Path, ...]:
    required = {
        *(root / path for path in _GENERATED_READMES),
        root / _GENERATED_SECURITY_POLICY,
        *(root / path for path in _EXECUTABLE_OR_LEGAL_DOCUMENTS),
    }
    maintained = {
        *root.glob("plugins/*/commands/*.md"),
        *root.glob("plugins/*/skills/*/SKILL.md"),
        *root.glob("plugins/*/skills/*/references/*.md"),
    }
    missing = [
        path
        for path in sorted(required)
        if not path.is_file()
        and path.relative_to(root) not in _GENERATED_READMES
        and path.relative_to(root) != _GENERATED_SECURITY_POLICY
    ]
    if missing:
        msg = f"required documentation is missing: {', '.join(str(path) for path in missing)}"
        raise ValueError(msg)
    return tuple(sorted(required | maintained))


def _validate_documents(documents: dict[Path, str]) -> None:
    for path, source in documents.items():
        _validate_local_links(path, source, documents)
        _validate_cli_examples(path, source)


def _validate_local_links(path: Path, source: str, documents: dict[Path, str]) -> None:
    for match in _LOCAL_LINK.finditer(source):
        relative, anchor = match.groups()
        target = (path.parent / relative).resolve() if relative else path
        generated_target = documents.get(target)
        if generated_target is None and not target.exists():
            msg = f"{path} links to missing local target {relative!r}"
            raise ValueError(msg)
        if anchor and target.suffix.lower() == ".md":
            target_source = generated_target if generated_target is not None else target.read_text(encoding="utf-8")
            headings = {_heading_slug(heading.group(1)) for heading in _HEADING.finditer(target_source)}
            if anchor not in headings:
                msg = f"{path} links to missing Markdown heading {anchor!r} in {relative or path.name!r}"
                raise ValueError(msg)


def _heading_slug(heading: str) -> str:
    normalized = re.sub(r"[^a-z0-9 -]", "", heading.lower()).replace(" ", "-")
    return re.sub(r"-+", "-", normalized)


def _validate_cli_examples(path: Path, source: str) -> None:
    for match in _STANDARDS_COMMAND.finditer(source):
        command = shlex.split(match.group(1))
        completed = subprocess.run(  # ruff: ignore[subprocess-without-shell-equals-true] -- fixed interpreter and argv.
            [sys.executable, "-m", "sarj_standards", *command[1:], "--help"],
            check=False,
            capture_output=True,
            text=True,
        )
        if completed.returncode != 0:
            msg = f"{path} contains an invalid command example: {match.group(1)!r}"
            raise ValueError(msg)


def _manifest(path: Path) -> dict[str, object]:
    if path.suffix == ".toml":
        document = tomllib.loads(path.read_text(encoding="utf-8"))
        project: object = document.get("project")
        if not _is_object_table(project):
            msg = f"{path} has no project table"
            raise ValueError(msg)
        return project
    document: object = json.loads(path.read_text(encoding="utf-8"))  # pyright: ignore[reportAny]
    if not _is_object_table(document):
        msg = f"{path} is not an object"
        raise TypeError(msg)
    return document


def _string(table: dict[str, object], key: str) -> str:
    value = table.get(key)
    if not isinstance(value, str) or not value:
        msg = f"manifest or catalog entry does not declare {key!r}"
        raise ValueError(msg)
    return value


def _title(name: str) -> str:
    return " ".join(part.capitalize() for part in name.replace("@", "").replace("/", " ").replace("-", " ").split())


def _is_object_table(value: object) -> TypeGuard[dict[str, object]]:
    return isinstance(value, dict)
