import type { OxlintConfig } from "oxlint";

// Preserve pinned upstream preset declarations; importing projects retain their own policy scope.
export const RECOMMENDED_RULES = Object.freeze({
  "sarj-core/no-octal": "error",
  "sarj-core/no-dupe-args": "error",
  "eslint/constructor-super": "error",
  "eslint/for-direction": "error",
  "eslint/getter-return": "error",
  "eslint/no-async-promise-executor": "error",
  "eslint/no-case-declarations": "error",
  "eslint/no-class-assign": "error",
  "eslint/no-compare-neg-zero": "error",
  "eslint/no-cond-assign": "error",
  "eslint/no-const-assign": "error",
  "eslint/no-constant-binary-expression": "error",
  "eslint/no-constant-condition": "error",
  "eslint/no-control-regex": "error",
  "eslint/no-debugger": "error",
  "eslint/no-delete-var": "error",
  "eslint/no-dupe-class-members": "error",
  "eslint/no-dupe-else-if": "error",
  "eslint/no-dupe-keys": "error",
  "eslint/no-duplicate-case": "error",
  "eslint/no-empty": "error",
  "eslint/no-empty-character-class": "error",
  "eslint/no-empty-pattern": "error",
  "eslint/no-empty-static-block": "error",
  "eslint/no-ex-assign": "error",
  "eslint/no-extra-boolean-cast": "error",
  "eslint/no-fallthrough": "error",
  "eslint/no-func-assign": "error",
  "eslint/no-global-assign": "error",
  "eslint/no-import-assign": "error",
  "eslint/no-invalid-regexp": "error",
  "eslint/no-irregular-whitespace": "error",
  "eslint/no-loss-of-precision": "error",
  "eslint/no-misleading-character-class": "error",
  "eslint/no-new-native-nonconstructor": "error",
  "eslint/no-nonoctal-decimal-escape": "error",
  "eslint/no-obj-calls": "error",
  "eslint/no-prototype-builtins": "error",
  "eslint/no-redeclare": "error",
  "eslint/no-regex-spaces": "error",
  "eslint/no-self-assign": "error",
  "eslint/no-setter-return": "error",
  "eslint/no-shadow-restricted-names": "error",
  "eslint/no-sparse-arrays": "error",
  "eslint/no-this-before-super": "error",
  "eslint/no-unassigned-vars": "error",
  "eslint/no-undef": "error",
  "eslint/no-unexpected-multiline": "error",
  "eslint/no-unreachable": "error",
  "eslint/no-unsafe-finally": "error",
  "eslint/no-unsafe-negation": "error",
  "eslint/no-unsafe-optional-chaining": "error",
  "eslint/no-unused-labels": "error",
  "eslint/no-unused-private-class-members": "error",
  "eslint/no-unused-vars": "error",
  "eslint/no-useless-assignment": "error",
  "eslint/no-useless-backreference": "error",
  "eslint/no-useless-catch": "error",
  "eslint/no-useless-escape": "error",
  "eslint/no-with": "error",
  "eslint/preserve-caught-error": "error",
  "eslint/require-yield": "error",
  "eslint/use-isnan": "error",
  "eslint/valid-typeof": "error",
} satisfies NonNullable<OxlintConfig["rules"]>);

export const TYPESCRIPT_STRICT_RULES = Object.freeze({
  "typescript/await-thenable": "error",
  "typescript/ban-ts-comment": [
    "error",
    {
      minimumDescriptionLength: 10,
    },
  ],
  "eslint/no-array-constructor": "error",
  "typescript/no-array-delete": "error",
  "typescript/no-base-to-string": "error",
  "typescript/no-confusing-void-expression": "error",
  "typescript/no-deprecated": "error",
  "typescript/no-duplicate-enum-values": "error",
  "typescript/no-duplicate-type-constituents": "error",
  "typescript/no-dynamic-delete": "error",
  "typescript/no-empty-object-type": "error",
  "typescript/no-explicit-any": "error",
  "typescript/no-extra-non-null-assertion": "error",
  "typescript/no-extraneous-class": "error",
  "typescript/no-floating-promises": "error",
  "typescript/no-for-in-array": "error",
  "typescript/no-generated-empty-object-type": "error",
  "eslint/no-implied-eval": "off",
  "typescript/no-implied-eval": "error",
  "typescript/no-invalid-void-type": "error",
  "typescript/no-meaningless-void-operator": "error",
  "typescript/no-misused-new": "error",
  "typescript/no-misused-promises": "error",
  "typescript/no-misused-spread": "error",
  "typescript/no-mixed-enums": "error",
  "typescript/no-namespace": "error",
  "typescript/no-non-null-asserted-nullish-coalescing": "error",
  "typescript/no-non-null-asserted-optional-chain": "error",
  "typescript/no-non-null-assertion": "error",
  "typescript/no-redundant-type-constituents": "error",
  "typescript/no-require-imports": "error",
  "typescript/no-this-alias": "error",
  "typescript/no-unnecessary-boolean-literal-compare": "error",
  "typescript/no-unnecessary-condition": "error",
  "typescript/no-unnecessary-template-expression": "error",
  "typescript/no-unnecessary-type-arguments": "error",
  "typescript/no-unnecessary-type-assertion": "error",
  "typescript/no-unnecessary-type-constraint": "error",
  "typescript/no-unnecessary-type-conversion": "error",
  "typescript/no-unnecessary-type-parameters": "error",
  "typescript/no-unsafe-argument": "error",
  "typescript/no-unsafe-assignment": "error",
  "typescript/no-unsafe-call": "error",
  "typescript/no-unsafe-declaration-merging": "error",
  "typescript/no-unsafe-enum-comparison": "error",
  "typescript/no-unsafe-function-type": "error",
  "typescript/no-unsafe-member-access": "error",
  "typescript/no-unsafe-return": "error",
  "typescript/no-unsafe-unary-minus": "error",
  "eslint/no-unused-expressions": "error",
  "eslint/no-unused-vars": "error",
  "eslint/no-useless-constructor": "error",
  "typescript/no-useless-default-assignment": "error",
  "typescript/no-wrapper-object-types": "error",
  "eslint/no-throw-literal": "off",
  "typescript/only-throw-error": "error",
  "typescript/prefer-as-const": "error",
  "typescript/prefer-literal-enum-member": "error",
  "typescript/prefer-namespace-keyword": "error",
  "eslint/prefer-promise-reject-errors": "off",
  "typescript/prefer-promise-reject-errors": "error",
  "typescript/prefer-reduce-type-parameter": "error",
  "typescript/prefer-return-this-type": "error",
  "typescript/related-getter-setter-pairs": "error",
  "eslint/require-await": "off",
  "typescript/require-await": "error",
  "typescript/restrict-plus-operands": [
    "error",
    {
      allowAny: false,
      allowBoolean: false,
      allowNullish: false,
      allowNumberAndString: false,
      allowRegExp: false,
    },
  ],
  "typescript/restrict-template-expressions": [
    "error",
    {
      allowAny: false,
      allowBoolean: false,
      allowNever: false,
      allowNullish: false,
      allowNumber: false,
      allowRegExp: false,
    },
  ],
  "typescript/return-await": ["error", "error-handling-correctness-only"],
  "typescript/triple-slash-reference": "error",
  "typescript/unbound-method": "error",
  "typescript/unified-signatures": "error",
  "typescript/use-unknown-in-catch-callback-variable": "error",
} satisfies NonNullable<OxlintConfig["rules"]>);

export const TYPESCRIPT_STYLISTIC_RULES = Object.freeze({
  "typescript/adjacent-overload-signatures": "error",
  "typescript/array-type": "error",
  "typescript/ban-tslint-comment": "error",
  "typescript/class-literal-property-style": "error",
  "typescript/consistent-generic-constructors": "error",
  "typescript/consistent-indexed-object-style": "error",
  "typescript/consistent-type-assertions": "error",
  "typescript/consistent-type-definitions": "error",
  "typescript/dot-notation": "error",
  "typescript/no-confusing-non-null-assertion": "error",
  "eslint/no-empty-function": "error",
  "typescript/no-inferrable-types": "error",
  "typescript/non-nullable-type-assertion-style": "error",
  "typescript/prefer-find": "error",
  "typescript/prefer-for-of": "error",
  "typescript/prefer-function-type": "error",
  "typescript/prefer-includes": "error",
  "typescript/prefer-nullish-coalescing": "error",
  "typescript/prefer-optional-chain": "error",
  "typescript/prefer-regexp-exec": "error",
  "typescript/prefer-string-starts-ends-with": "error",
} satisfies NonNullable<OxlintConfig["rules"]>);

export const TYPESCRIPT_PRESET_RULES = Object.freeze({
  ...TYPESCRIPT_STRICT_RULES,
  ...TYPESCRIPT_STYLISTIC_RULES,
});

export const TYPESCRIPT_COMPATIBILITY_OVERRIDE = Object.freeze({
  files: ["**/*.{ts,tsx,mts,cts}"],
  rules: {
    "eslint/constructor-super": "off",
    "sarj-core/no-dupe-args": "off",
    "eslint/getter-return": "off",
    "eslint/no-class-assign": "off",
    "eslint/no-const-assign": "off",
    "eslint/no-dupe-class-members": "off",
    "eslint/no-dupe-keys": "off",
    "eslint/no-func-assign": "off",
    "eslint/no-import-assign": "off",
    "eslint/no-new-native-nonconstructor": "off",
    "eslint/no-obj-calls": "off",
    "eslint/no-redeclare": "off",
    "eslint/no-setter-return": "off",
    "eslint/no-this-before-super": "off",
    "eslint/no-undef": "off",
    "eslint/no-unreachable": "off",
    "eslint/no-unsafe-negation": "off",
    "eslint/no-var": "error",
    "eslint/no-with": "off",
    "eslint/prefer-const": "error",
    "eslint/prefer-rest-params": "error",
    "eslint/prefer-spread": "error",
  },
} satisfies NonNullable<OxlintConfig["overrides"]>[number]);

export const TYPE_AWARE_RULE_IDS = [
  "typescript/await-thenable",
  "typescript/consistent-return",
  "typescript/consistent-type-exports",
  "typescript/dot-notation",
  "typescript/no-array-delete",
  "typescript/no-base-to-string",
  "typescript/no-confusing-void-expression",
  "typescript/no-deprecated",
  "typescript/no-duplicate-type-constituents",
  "typescript/no-floating-promises",
  "typescript/no-for-in-array",
  "typescript/no-generated-empty-object-type",
  "typescript/no-implied-eval",
  "typescript/no-meaningless-void-operator",
  "typescript/no-misused-promises",
  "typescript/no-misused-spread",
  "typescript/no-mixed-enums",
  "typescript/no-redundant-type-constituents",
  "typescript/no-unnecessary-boolean-literal-compare",
  "typescript/no-unnecessary-condition",
  "typescript/no-unnecessary-qualifier",
  "typescript/no-unnecessary-template-expression",
  "typescript/no-unnecessary-type-arguments",
  "typescript/no-unnecessary-type-assertion",
  "typescript/no-unnecessary-type-conversion",
  "typescript/no-unnecessary-type-parameters",
  "typescript/no-unsafe-argument",
  "typescript/no-unsafe-assignment",
  "typescript/no-unsafe-call",
  "typescript/no-unsafe-enum-comparison",
  "typescript/no-unsafe-member-access",
  "typescript/no-unsafe-return",
  "typescript/no-unsafe-type-assertion",
  "typescript/no-unsafe-unary-minus",
  "typescript/no-useless-default-assignment",
  "typescript/non-nullable-type-assertion-style",
  "typescript/only-throw-error",
  "typescript/prefer-find",
  "typescript/prefer-includes",
  "typescript/prefer-nullish-coalescing",
  "typescript/prefer-optional-chain",
  "typescript/prefer-promise-reject-errors",
  "typescript/prefer-readonly",
  "typescript/prefer-readonly-parameter-types",
  "typescript/prefer-reduce-type-parameter",
  "typescript/prefer-regexp-exec",
  "typescript/prefer-return-this-type",
  "typescript/prefer-string-starts-ends-with",
  "typescript/promise-function-async",
  "typescript/related-getter-setter-pairs",
  "typescript/require-array-sort-compare",
  "typescript/require-await",
  "typescript/restrict-plus-operands",
  "typescript/restrict-template-expressions",
  "typescript/return-await",
  "typescript/strict-boolean-expressions",
  "typescript/strict-void-return",
  "typescript/switch-exhaustiveness-check",
  "typescript/unbound-method",
  "typescript/use-unknown-in-catch-callback-variable",
] as const;

export const TANSTACK_QUERY_RECOMMENDED_RULES = Object.freeze({
  "sarj-query/exhaustive-deps": "error",
  "sarj-query/no-rest-destructuring": "warn",
  "sarj-query/stable-query-client": "error",
  "sarj-query/no-unstable-deps": "error",
  "sarj-query/infinite-query-property-order": "error",
  "sarj-query/no-void-query-fn": "error",
  "sarj-query/mutation-property-order": "error",
} satisfies NonNullable<OxlintConfig["rules"]>);

export const NEXTJS_ADDITIONAL_RECOMMENDED_RULES = Object.freeze({
  "sarj-nextjs/no-location-assign-relative-destination": "error",
} satisfies NonNullable<OxlintConfig["rules"]>);

export const SONARJS_ADDITIONAL_RULES = Object.freeze({
  "sarj-sonarjs/no-all-duplicated-branches": "error",
  "sarj-sonarjs/no-collapsible-if": "error",
  "sarj-sonarjs/no-element-overwrite": "error",
  "sarj-sonarjs/no-identical-expressions": "error",
  "sarj-sonarjs/no-identical-functions": ["error", 3],
  "sarj-sonarjs/no-redundant-jump": "error",
  "sarj-sonarjs/no-use-of-empty-return-value": "error",
  "sarj-sonarjs/prefer-immediate-return": "error",
} satisfies NonNullable<OxlintConfig["rules"]>);

export const TESTING_LIBRARY_REACT_RECOMMENDED_RULES = Object.freeze({
  "sarj-testing-library/await-async-events": [
    "error",
    { eventModule: "userEvent" },
  ],
  "sarj-testing-library/await-async-queries": "error",
  "sarj-testing-library/await-async-utils": "error",
  "sarj-testing-library/no-await-sync-events": [
    "error",
    { eventModules: ["fire-event"] },
  ],
  "sarj-testing-library/no-await-sync-queries": "error",
  "sarj-testing-library/no-container": "error",
  "sarj-testing-library/no-debugging-utils": "warn",
  "sarj-testing-library/no-dom-import": ["error", "react"],
  "sarj-testing-library/no-global-regexp-flag-in-query": "error",
  "sarj-testing-library/no-manual-cleanup": "error",
  "sarj-testing-library/no-node-access": "error",
  "sarj-testing-library/no-promise-in-fire-event": "error",
  "sarj-testing-library/no-render-in-lifecycle": "error",
  "sarj-testing-library/no-unnecessary-act": "error",
  "sarj-testing-library/no-wait-for-multiple-assertions": "error",
  "sarj-testing-library/no-wait-for-side-effects": "error",
  "sarj-testing-library/no-wait-for-snapshot": "error",
  "sarj-testing-library/prefer-find-by": "error",
  "sarj-testing-library/prefer-presence-queries": "error",
  "sarj-testing-library/prefer-query-by-disappearance": "error",
  "sarj-testing-library/prefer-screen-queries": "error",
  "sarj-testing-library/render-result-naming-convention": "error",
} satisfies NonNullable<OxlintConfig["rules"]>);
