import type { OxlintConfig } from "oxlint";

export const UPSTREAM_RULES = Object.freeze({
  "sarj-unicorn/require-module-specifiers": "error",
  "sarj-unicorn/no-useless-spread": "error",
  "sarj-unicorn/no-invalid-fetch-options": "error",
  "sarj-unicorn/prefer-number-properties": "error",
  "sarj-unicorn/prefer-logical-operator-over-ternary": "error",
  "sarj-unicorn/prefer-top-level-await": "error",
  "sarj-node/prefer-promises-fs": "error",
  "sarj-typescript/naming-convention": [
    "error",
    {
      selector: "variable",
      modifiers: ["const", "global"],
      filter: {
        regex:
          "^(Route|action|clientAction|clientLoader|config|csr|dynamic|dynamicParams|entries|fetchCache|handle|headers|instant|links|loader|maxDuration|meta|metadata|partial|prefetch|preferredRegion|prerender|revalidate|runtime|shouldRevalidate|ssr|trailingSlash|viewport)$",
        match: true,
      },
      format: null,
    },
    {
      selector: "variable",
      modifiers: ["const", "global"],
      types: ["function"],
      format: ["camelCase", "PascalCase", "UPPER_CASE"],
      leadingUnderscore: "allow",
    },
    {
      selector: "variable",
      modifiers: ["const", "global"],
      format: ["UPPER_CASE", "PascalCase"],
      leadingUnderscore: "allow",
    },
    {
      selector: [
        "classProperty",
        "objectLiteralProperty",
        "typeProperty",
        "classMethod",
        "objectLiteralMethod",
        "typeMethod",
        "classicAccessor",
        "autoAccessor",
        "enumMember",
      ],
      modifiers: ["requiresQuotes"],
      format: null,
    },
    {
      selector: "default",
      format: ["camelCase"],
      leadingUnderscore: "allow",
      trailingUnderscore: "allow",
      filter: {
        regex: "^(UNSAFE_|__)",
        match: false,
      },
    },
    {
      selector: "variable",
      format: ["camelCase", "UPPER_CASE", "PascalCase"],
      leadingUnderscore: "allow",
    },
    {
      selector: "typeLike",
      format: ["PascalCase"],
    },
    {
      selector: "import",
      format: ["camelCase", "PascalCase", "UPPER_CASE"],
    },
    {
      selector: "objectLiteralProperty",
      format: null,
    },
    {
      selector: "typeProperty",
      format: null,
    },
    {
      selector: "parameter",
      format: ["camelCase"],
      leadingUnderscore: "allow",
    },
  ],
  "sarj-typescript/member-ordering": [
    "error",
    {
      default: "never",
      interfaces: "never",
      typeLiterals: "never",
      classes: {
        memberTypes: [
          [
            "public-constructor",
            "public-accessor",
            "public-get",
            "public-set",
            "public-method",
            "public-static-method",
            "public-instance-method",
            "public-decorated-method",
          ],
          [
            "protected-constructor",
            "protected-accessor",
            "protected-get",
            "protected-set",
            "protected-method",
            "protected-static-method",
            "protected-instance-method",
            "protected-decorated-method",
          ],
          [
            "private-constructor",
            "private-accessor",
            "#private-accessor",
            "private-get",
            "#private-get",
            "private-set",
            "#private-set",
            "private-method",
            "private-static-method",
            "private-instance-method",
            "private-decorated-method",
            "#private-method",
          ],
        ],
        order: "as-written",
      },
      classExpressions: {
        memberTypes: [
          [
            "public-constructor",
            "public-accessor",
            "public-get",
            "public-set",
            "public-method",
            "public-static-method",
            "public-instance-method",
            "public-decorated-method",
          ],
          [
            "protected-constructor",
            "protected-accessor",
            "protected-get",
            "protected-set",
            "protected-method",
            "protected-static-method",
            "protected-instance-method",
            "protected-decorated-method",
          ],
          [
            "private-constructor",
            "private-accessor",
            "#private-accessor",
            "private-get",
            "#private-get",
            "private-set",
            "#private-set",
            "private-method",
            "private-static-method",
            "private-instance-method",
            "private-decorated-method",
            "#private-method",
          ],
        ],
        order: "as-written",
      },
    },
  ],
  "sarj-react/jsx-no-leaked-render": [
    "error",
    {
      validStrategies: ["ternary", "coerce"],
    },
  ],
  "sarj-react-hooks/config": "error",
  "sarj-react-hooks/gating": "error",
  "sarj-react/no-invalid-html-attribute": "error",
  "sarj-unicorn/prefer-switch": "error",
  "sarj-jsdoc/no-implementation-jsdoc": [
    "error",
    {
      allowTypedContracts: false,
    },
  ],
  "shadcn/no-restyle": "warn",
  "shadcn/no-arbitrary-values": "warn",
  "shadcn/no-inline-styles": "warn",
  "shadcn/no-unknown-classes": "warn",
  "shadcn/require-static-classes": "warn",
  "sarj-unicorn/class-reference-in-static-methods": "error",
  "sarj-unicorn/consistent-json-file-read": "error",
  "sarj-unicorn/no-accidental-bitwise-operator": "error",
  "sarj-unicorn/no-array-concat-in-loop": "error",
  "sarj-unicorn/no-array-from-fill": "error",
  "sarj-unicorn/no-array-sort-for-min-max": "error",
  "sarj-unicorn/no-async-promise-finally": "error",
  "sarj-unicorn/no-blob-to-file": "error",
  "sarj-unicorn/no-boolean-sort-comparator": "error",
  "sarj-unicorn/no-canvas-to-image": "error",
  "sarj-unicorn/no-chained-comparison": "error",
  "sarj-unicorn/no-collection-bracket-access": "error",
  "sarj-unicorn/no-confusing-array-splice": "error",
  "sarj-unicorn/no-constant-zero-expression": "error",
  "sarj-unicorn/no-double-comparison": "error",
  "sarj-unicorn/no-duplicate-if-branches": "error",
  "sarj-unicorn/no-duplicate-logical-operands": "error",
  "sarj-unicorn/no-duplicate-loops": "error",
  "sarj-unicorn/no-duplicate-set-values": "error",
  "sarj-unicorn/no-error-property-assignment": "error",
  "sarj-unicorn/no-exports-in-scripts": "error",
  "sarj-unicorn/no-global-object-property-assignment": "error",
  "sarj-unicorn/no-impossible-length-comparison": "error",
  "sarj-unicorn/no-incorrect-query-selector": "error",
  "sarj-unicorn/no-incorrect-template-string-interpolation": "error",
  "sarj-unicorn/no-invalid-argument-count": "error",
  "sarj-unicorn/no-invalid-character-comparison": "error",
  "sarj-unicorn/no-invalid-file-input-accept": "error",
  "sarj-unicorn/no-invalid-well-known-symbol-methods": "error",
  "sarj-unicorn/no-late-current-target-access": "error",
  "sarj-unicorn/no-late-event-control": "error",
  "sarj-unicorn/no-loop-iterable-mutation": "error",
  "sarj-unicorn/no-mismatched-map-key": "error",
  "sarj-unicorn/no-misrefactored-assignment": "error",
  "sarj-unicorn/no-multiple-promise-resolver-calls": "error",
  "sarj-unicorn/no-nonstandard-builtin-properties": "error",
  "sarj-unicorn/no-object-methods-with-collections": "error",
  "sarj-unicorn/no-optional-chaining-on-undeclared-variable": "error",
  "sarj-unicorn/no-redundant-comparison": "error",
  "sarj-unicorn/no-return-array-push": "error",
  "sarj-unicorn/no-selector-as-dom-name": "error",
  "sarj-unicorn/no-subtraction-comparison": "error",
  "sarj-unicorn/no-this-outside-of-class": "error",
  "sarj-unicorn/no-uncalled-method": "error",
  "sarj-unicorn/no-undeclared-class-members": "error",
  "sarj-unicorn/no-unnecessary-array-flat-map": "error",
  "sarj-unicorn/no-unnecessary-boolean-comparison": "error",
  "sarj-unicorn/no-unnecessary-fetch-options": "error",
  "sarj-unicorn/no-unnecessary-global-this": "error",
  "sarj-unicorn/no-unnecessary-nested-ternary": "error",
  "sarj-unicorn/no-unnecessary-polyfills": "error",
  "sarj-unicorn/no-unnecessary-splice": "error",
  "sarj-unicorn/no-unnecessary-string-trim": "error",
  "sarj-unicorn/no-unsafe-buffer-conversion": "error",
  "sarj-unicorn/no-unsafe-dom-html": "error",
  "sarj-unicorn/no-unsafe-promise-all-settled-values": "error",
  "sarj-unicorn/no-unsafe-property-key": "error",
  "sarj-unicorn/no-unsafe-sqlite-interpolation": "error",
  "sarj-unicorn/no-unsafe-string-replacement": "error",
  "sarj-unicorn/no-unused-builtin-method-return": "error",
  "sarj-unicorn/no-unused-iterator-helper": "error",
  "sarj-unicorn/no-useless-boolean-cast": "error",
  "sarj-unicorn/no-useless-coercion": "error",
  "sarj-unicorn/no-useless-compound-assignment": "error",
  "sarj-unicorn/no-useless-concat": "error",
  "sarj-unicorn/no-useless-continue": "error",
  "sarj-unicorn/no-useless-delete-check": "error",
  "sarj-unicorn/no-useless-else": "error",
  "sarj-unicorn/no-useless-logical-operand": "error",
  "sarj-unicorn/no-useless-override": "error",
  "sarj-unicorn/no-useless-re-export": "error",
  "sarj-unicorn/no-useless-recursion": "error",
  "sarj-unicorn/no-useless-set-construction": "error",
  "sarj-unicorn/no-async-iterator-callback": "error",
  "sarj-unicorn/no-xor-as-exponentiation": "error",
  "sarj-unicorn/prefer-add-event-listener-options": "error",
  "sarj-unicorn/require-css-escape": "error",
  "sarj-unicorn/require-passive-events": "error",
  "sarj-unicorn/require-proxy-trap-boolean-return": "error",
  "sarj-unicorn/no-for-loop": "error",
  "sarj-unicorn/prefer-abort-signal-any": "error",
  "sarj-unicorn/prefer-abort-signal-timeout": "error",
  "sarj-unicorn/prefer-aggregate-error": "error",
  "sarj-unicorn/prefer-array-from-async": "error",
  "sarj-unicorn/prefer-array-from-map": "error",
  "sarj-unicorn/prefer-array-from-range": "error",
  "sarj-unicorn/prefer-array-iterable-methods": "error",
  "sarj-unicorn/prefer-array-last-methods": "error",
  "sarj-unicorn/prefer-array-slice": "error",
  "sarj-unicorn/prefer-direct-iteration": "error",
  "sarj-unicorn/prefer-flat-math-min-max": "error",
  "sarj-unicorn/prefer-global-number-constants": "error",
  "sarj-unicorn/prefer-group-by": "error",
  "sarj-unicorn/prefer-has-check": "error",
  "sarj-unicorn/prefer-https": "error",
  "sarj-unicorn/prefer-identifier-import-export-specifiers": "error",
  "sarj-unicorn/prefer-iterable-in-constructor": "error",
  "sarj-unicorn/prefer-iterator-concat": "error",
  "sarj-unicorn/prefer-iterator-helpers": "error",
  "sarj-unicorn/prefer-iterator-to-array": "error",
  "sarj-unicorn/prefer-iterator-to-array-at-end": "error",
  "sarj-unicorn/prefer-map-from-entries": "error",
  "sarj-unicorn/prefer-math-abs": "error",
  "sarj-unicorn/prefer-math-constants": "error",
  "sarj-unicorn/prefer-number-is-safe-integer": "error",
  "sarj-unicorn/prefer-object-define-properties": "error",
  "sarj-unicorn/prefer-object-destructuring-defaults": "error",
  "sarj-unicorn/prefer-object-iterable-methods": "error",
  "sarj-unicorn/prefer-promise-with-resolvers": "error",
  "sarj-unicorn/prefer-queue-microtask": "error",
  "sarj-unicorn/prefer-set-methods": "error",
  "sarj-unicorn/prefer-simple-sort-comparator": "error",
  "sarj-unicorn/prefer-simplified-conditions": "error",
  "sarj-unicorn/prefer-single-array-predicate": "error",
  "sarj-unicorn/prefer-single-replace": "error",
  "sarj-unicorn/prefer-split-limit": "error",
  "sarj-unicorn/prefer-string-match-all": "error",
  "sarj-unicorn/prefer-string-pad-start-end": "error",
  "sarj-unicorn/prefer-string-repeat": "error",
  "sarj-unicorn/prefer-then-catch": "error",
  "sarj-unicorn/prefer-unary-minus": "error",
  "sarj-unicorn/prefer-unicode-code-point-escapes": "error",
  "sarj-unicorn/prefer-url-can-parse": "error",
  "sarj-unicorn/prefer-url-search-parameters": "error",
  "sarj-unicorn/prefer-while-loop-condition": "error",
  "sarj-unicorn/single-line-block-comment-style": ["warn", "single-line"],
  "sarj-unicorn/prefer-single-object-destructuring": "warn",
  "sarj-unicorn/iteration-fallback-style": ["warn", "guard"],
  "sarj-unicorn/prefer-combined-guards": "warn",
  "sarj-unicorn/no-computed-property-existence-check": "warn",
  "zod/prefer-enum-over-literal-union": "error",
  "zod/prefer-nullish": "error",
  "zod/no-any-schema": "error",
  "zod/no-conflicting-checks": "error",
  "zod/no-duplicate-schema-methods": "error",
  "zod/no-coerce-boolean": "error",
  "zod/no-throw-in-refine": "error",
  "zod/no-transform-in-record-key": "error",
  "perfectionist/sort-interfaces": "error",
  "perfectionist/sort-jsx-props": "error",
  "perfectionist/sort-union-types": "error",
  "simple-import-sort/imports": "error",
  "simple-import-sort/exports": "error",
  "sarj-core/no-restricted-syntax": [
    "error",
    {
      selector:
        "UnaryExpression[operator='typeof']:not([parent.type='BinaryExpression'][parent.operator=/^(===|!==|==|!=)$/][parent.right.type='Literal'][parent.right.value='undefined']):not([parent.type='BinaryExpression'][parent.operator=/^(===|!==|==|!=)$/][parent.left.type='Literal'][parent.left.value='undefined'])",
      message:
        'Avoid runtime typeof representation checks. Preserve a known domain type or validate external input with the existing schema. Existence checks against "undefined" and TypeScript type queries remain allowed.',
    },
    {
      selector: "CallExpression[callee.property.name='forEach']",
      message: "Prefer a for-of loop over forEach.",
    },
    {
      selector: "TSModuleDeclaration[kind='namespace']",
      message: "Use ES modules instead of namespaces.",
    },
  ],
  "sarj-core/no-undef-init": "error",
} satisfies NonNullable<OxlintConfig["rules"]>);

export const UPSTREAM_OVERRIDES = Object.freeze([
  {
    files: ["**/*.{js,jsx,mjs,cjs}"],
    rules: {
      "sarj-jsdoc/no-implementation-jsdoc": [
        "error",
        {
          allowTypedContracts: true,
        },
      ],
    },
  },
  {
    files: [
      "**/*.{test,spec,e2e}.{js,jsx,mjs,cjs,ts,tsx,mts,cts}",
      "**/test/**/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts}",
      "**/tests/**/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts}",
      "**/__tests__/**/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts}",
    ],
    rules: {
      "node-test/no-assert-throws-multiple-statements": "error",
      "node-test/no-assert-throws-async": "error",
      "node-test/no-unneeded-async-rejects-callback": "error",
      "node-test/no-useless-assertion": "error",
    },
  },
  {
    files: ["**/*.{js,jsx,ts,tsx}"],
    rules: {
      "better-tailwindcss/no-conflicting-classes": "error",
      "better-tailwindcss/no-duplicate-classes": "error",
      "better-tailwindcss/no-deprecated-classes": "error",
      "better-tailwindcss/no-unnecessary-whitespace": "error",
      "better-tailwindcss/enforce-shorthand-classes": "error",
      "better-tailwindcss/enforce-consistent-variable-syntax": [
        "warn",
        {
          syntax: "shorthand",
        },
      ],
    },
  },
  {
    files: ["**/*.tsx"],
    rules: {
      "sarj-typescript/naming-convention": [
        "error",
        {
          selector: "variable",
          modifiers: ["const", "global"],
          filter: {
            regex:
              "^(Route|action|clientAction|clientLoader|config|csr|dynamic|dynamicParams|entries|fetchCache|handle|headers|instant|links|loader|maxDuration|meta|metadata|partial|prefetch|preferredRegion|prerender|revalidate|runtime|shouldRevalidate|ssr|trailingSlash|viewport)$",
            match: true,
          },
          format: null,
        },
        {
          selector: "variable",
          modifiers: ["const", "global"],
          types: ["function"],
          format: ["camelCase", "PascalCase", "UPPER_CASE"],
          leadingUnderscore: "allow",
        },
        {
          selector: "variable",
          modifiers: ["const", "global"],
          format: ["UPPER_CASE", "PascalCase"],
          leadingUnderscore: "allow",
        },
        {
          selector: [
            "classProperty",
            "objectLiteralProperty",
            "typeProperty",
            "classMethod",
            "objectLiteralMethod",
            "typeMethod",
            "classicAccessor",
            "autoAccessor",
            "enumMember",
          ],
          modifiers: ["requiresQuotes"],
          format: null,
        },
        {
          selector: "default",
          format: ["camelCase", "PascalCase"],
          leadingUnderscore: "allow",
          trailingUnderscore: "allow",
          filter: {
            regex: "^(UNSAFE_|__)",
            match: false,
          },
        },
        {
          selector: "variable",
          format: ["camelCase", "UPPER_CASE", "PascalCase"],
          leadingUnderscore: "allow",
        },
        {
          selector: "typeLike",
          format: ["PascalCase"],
        },
        {
          selector: "import",
          format: ["camelCase", "PascalCase", "UPPER_CASE"],
        },
        {
          selector: "objectLiteralProperty",
          format: null,
        },
        {
          selector: "typeProperty",
          format: null,
        },
        {
          selector: "parameter",
          format: ["camelCase"],
          leadingUnderscore: "allow",
        },
      ],
    },
  },
] satisfies NonNullable<OxlintConfig["overrides"]>);
