import { describe, expect, it } from "vitest";

import { isGeneratedFile } from "../../src/rules/_paths.js";

const HAND_WRITTEN = "/repo/src/thing.ts";

describe("isGeneratedFile — banner markers", () => {
  it.each([
    ["oazapfts", " * DO NOT MODIFY - This file has been generated using oazapfts.\n"],
    ["payload", "/* THIS FILE WAS GENERATED AUTOMATICALLY BY PAYLOAD. */\n"],
    ["nest graphql", " * THIS FILE WAS AUTOMATICALLY GENERATED (DO NOT MODIFY)\n"],
    ["medusa", "/** This file is auto-generated. Do not modify it manually. */\n"],
    ["twenty barrel", " * | | | Auto-generated file\n * | | | Any edits to this will be overridden\n"],
    ["storybook", " * This file has been automatically generated,\n"],
    ["legacy @generated", "// @generated by protoc\n"],
    ["legacy do-not-edit", "// DO NOT EDIT\n"],
  ])("recognises the %s banner", (_name, banner) => {
    expect(isGeneratedFile(HAND_WRITTEN, banner)).toBe(true);
  });

  // The obvious widening — bare `auto-?generated`, bare `generated from`, bare
  // `do not (modify|change)` — matched 175 extra files over 105,551, and most
  // were hand-written source using the phrase as PROSE or as an identifier.
  // Every string below is copied verbatim from one of them. Exempting these
  // files would silently disable twenty rules on ordinary code.
  it.each([
    ["identifier", "export type AutoGeneratedFields = 'createdAt' | 'updatedAt';\n"],
    ["prose adjective", "/** The verify token is auto-generated at integration creation. */\n"],
    ["behavioural warning", "// Note: do not change to 'threads', it will cause the failure\n"],
    ["angular router", " * Do not change this unless you are the Angular router.\n"],
    ["rule description", "description: 'Disallow type assertions that do not change the type',\n"],
    ["derivation prose", "/** If not provided, one is generated from the store ID. */\n"],
  ])("does not treat %s as a generator banner", (_name, text) => {
    expect(isGeneratedFile(HAND_WRITTEN, text)).toBe(false);
  });

  it("only reads the head of the file", () => {
    expect(isGeneratedFile(HAND_WRITTEN, "x\n".repeat(2000) + "@generated\n")).toBe(false);
  });
});
