// vitest: shared-module-graph
import * as parser from "@typescript-eslint/parser";
import { RuleTester } from "@typescript-eslint/rule-tester";
import { afterAll, describe, it } from "vitest";

import rule, { NO_DUPLICATE_TEST_CASE_DOCUMENTATION } from "../../src/rules/no-duplicate-test-case.js";
import { verifyRuleExamples } from "../../src/verify-rule-examples.js";

RuleTester.afterAll = afterAll;
RuleTester.describe = describe;
RuleTester.it = it;
RuleTester.itOnly = it.only;

const TESTER = new RuleTester({languageOptions: {parser}});
const FILENAME = "/repo/src/format.test.ts";
const CALLBACK = "('%s', (value) => { expect(format(value)).toBeDefined(); });";

TESTER.run("no-duplicate-test-case", rule, {
  valid: [
    ...([
      ["distinct scalar inputs", "it.each([0, 1])"],
      ["distinct expected values", "it.each([[1, true], [1, false]])"],
      ["distinct case identity", "it.each([{id: 'one', value: 1}, {id: 'two', value: 1}])"],
      ["property order is a contract", "it.each([{a: 1, b: 2}, {b: 2, a: 1}])"],
      ["runtime rows", "it.each([makeCase(), makeCase()])"],
      ["computed keys", "it.each([{[key]: 1}, {[key]: 1}])"],
      ["spreads", "it.each([{...base}, {...base}])"],
      ["custom runner", "const it = runner; it.each([1, 1])"],
      ["mutable table", "let cases = [1, 1]; it.each(cases)"],
      ["escaped table", "const cases = [1, 1]; transform(cases); it.each(cases)"],
      ["mutated table", "const cases = [1, 1]; cases.pop(); it.each(cases)"],
      ["getter rows", "it.each([{get value() {return 1;}}, {get value() {return 1;}}])"],
    ] as const).map(([name, code]) => ({name, filename: FILENAME, code: `${code}${CALLBACK}`})),
    {filename: "/repo/src/format.ts", code: `it.each([1, 1])${CALLBACK}`},
    {filename: FILENAME, code: `// Code generated by fixture-generator. DO NOT EDIT.\nit.each([1, 1])${CALLBACK}`},
    {filename: FILENAME, code: `// eslint-disable-next-line @rule-tester/no-duplicate-test-case -- repeated execution tests shared state\nit.each([1, 1])${CALLBACK}`},
  ],
  invalid: [
    ...([
      ["scalar row", "it.each([1, 1])"],
      ["tuple row", "it.each([[1, true], [1, true]])"],
      ["object row", "it.each([{input: 1, expected: true}, {input: 1, expected: true}])"],
      ["const table", "const cases = [[1, true], [1, true]] as const; it.each(cases)"],
      ["erased call", "(it.each([1, 1]) as typeof it)"],
      ["erased table reference", "const cases = [1, 1]; it.each(cases as readonly number[])"],
      ["import alias", "import {test as check} from 'vitest'; check.each([1, 1])"],
      ["concurrent cases", "test.concurrent.each([1, 1])"],
      ["bigint row", "it.each([1n, 1n])"],
    ] as const).map(([name, code]) => ({name, filename: FILENAME, code: `${code}${CALLBACK}`, errors: [{messageId: "duplicateCase" as const}]})),
    {filename: FILENAME, code: `it.each([1, 1, 1])${CALLBACK}`, errors: [{messageId: "duplicateCase"}, {messageId: "duplicateCase"}]},
    {name: "shared tables report each row once", filename: FILENAME, code: `const cases = [1, 1]; it.each(cases)${CALLBACK} test.each(cases)${CALLBACK}`, errors: [{messageId: "duplicateCase"}]},
  ],
});
await verifyRuleExamples(rule, NO_DUPLICATE_TEST_CASE_DOCUMENTATION);
