import * as tsParser from "@typescript-eslint/parser";
import { RuleTester } from "@typescript-eslint/rule-tester";
import { afterAll, describe, it } from "vitest";

import rule from "../../src/rules/no-enum.js";

RuleTester.afterAll = afterAll;
RuleTester.describe = describe;
RuleTester.it = it;
RuleTester.itOnly = it.only;

const ruleTester = new RuleTester({
  languageOptions: {
    parser: tsParser,
  },
});

ruleTester.run("no-enum", rule, {
  valid: [
    // String-literal union — the prescribed pattern.
    { code: 'type Status = "active" | "inactive";' },
    // `as const` object — also prescribed.
    {
      code: "const Status = { Active: 'active', Inactive: 'inactive' } as const;",
    },
    // A file with `@generated` near the top opts out.
    {
      code: "// @generated by openapi-typescript\nenum Status { A, B }",
    },
    // Files under a `generated/` segment opt out by default.
    {
      code: "enum Status { A, B }",
      filename: "/repo/src/generated/api.ts",
    },
    // `.gen.ts` suffix opts out by default.
    {
      code: "enum Status { A, B }",
      filename: "/repo/src/api.gen.ts",
    },
    // Common generated-code conventions from GraphQL/OpenAPI toolchains.
    {
      code: "enum Status { A, B }",
      filename: "/repo/src/openapi-gen/types.ts",
    },
    {
      code: "// Generated GraphQL types, do not edit manually.\nenum Status { A, B }",
      filename: "/repo/src/workspace/types/GraphRoot.types.ts",
    },
    // A custom `ignoreFiles` glob suppresses. The invalid list holds the same
    // option against a NON-matching path, so between them the glob is the only
    // difference and the option cannot be deleted unnoticed. Both halves are
    // needed: only the non-matching case existed, and it passes just as well
    // with the option ignored entirely.
    {
      code: "enum Status { Active }",
      filename: "/repo/src/codegen/api.ts",
      options: [{ ignoreFiles: ["**/codegen/**"] }],
    },
    // `**` spans directory separators and `*` does not — the two halves of the
    // glob translation, neither of which any test exercised.
    {
      code: "enum Status { Active }",
      filename: "/repo/src/a/b/c/api.ts",
      options: [{ ignoreFiles: ["**/a/**/*.ts"] }],
    },
  ],
  invalid: [
    {
      code: "enum Status { Active, Inactive }",
      errors: [{ messageId: "noEnum" }],
    },
    {
      code: 'enum Color { Red = "red", Blue = "blue" }',
      errors: [{ messageId: "noEnum" }],
    },
    {
      code: "const enum Direction { Up, Down, Left, Right }",
      errors: [{ messageId: "noEnum" }],
    },
    // Honors a custom ignoreFiles glob. This is the NEGATIVE half — a file the
    // glob does not match still reports. Its positive twin is in the valid
    // list; without both, no test proves a glob suppresses anything, and the
    // whole option could be deleted with the suite green.
    {
      code: "enum Status { Active }",
      filename: "/repo/src/normal.ts",
      options: [{ ignoreFiles: ["**/codegen/**"] }],
      errors: [{ messageId: "noEnum" }],
    },
    // A single `*` must NOT cross a directory separator. Without this the glob
    // translation collapses to "everything is `.*`" and any pattern naming the
    // right directory suppresses its whole subtree.
    {
      code: "enum Status { Active }",
      filename: "/repo/src/codegen/deep/api.ts",
      options: [{ ignoreFiles: ["**/codegen/*.ts"] }],
      errors: [{ messageId: "noEnum" }],
    },
  ],
});
