import * as tsParser from "@typescript-eslint/parser";
import { RuleTester } from "@typescript-eslint/rule-tester";
import { afterAll, describe, it } from "vitest";

import rule, { NO_ENUM_DOCUMENTATION } from "../../src/rules/no-enum.js";

RuleTester.afterAll = afterAll;
RuleTester.describe = describe;
RuleTester.it = it;
RuleTester.itOnly = it.only;

const RULE_TESTER = new RuleTester({
  languageOptions: {
    parser: tsParser,
  },
});

RULE_TESTER.run("no-enum", rule, {
  valid: [
    {
      name: "accepts a string-literal union",
      code: NO_ENUM_DOCUMENTATION.examples[0].files[0].source,
    },
    {
      name: "accepts an as-const object",
      code: "const Status = { Active: 'active', Inactive: 'inactive' } as const;",
    },
    {
      name: "ignores a generated header marker",
      code: "// @generated by openapi-typescript\nenum Status { A, B }",
    },
    {
      name: "ignores the shared generated directory convention",
      code: "enum Status { A, B }",
      filename: "/repo/src/generated/api.ts",
    },
    {
      name: "ignores the shared gen suffix convention",
      code: "enum Status { A, B }",
      filename: "/repo/src/api.gen.ts",
    },
    {
      name: "ignores the shared generated suffix convention",
      code: "enum Status { A, B }",
      filename: "/repo/src/api.generated.ts",
    },
    {
      name: "ignores the shared OpenAPI directory convention",
      code: "enum Status { A, B }",
      filename: "/repo/src/openapi-gen/types.ts",
    },
    {
      name: "ignores a generated GraphQL header marker",
      code: "// Generated GraphQL types, do not edit manually.\nenum Status { A, B }",
      filename: "/repo/src/workspace/types/GraphRoot.types.ts",
    },
    {
      name: "ignores a path matching a custom generated-file glob",
      code: "enum Status { Active }",
      filename: "/repo/src/codegen/api.ts",
      options: [{ ignoreFiles: ["**/codegen/**"] }],
    },
    {
      name: "allows a double-star glob to span directories",
      code: "enum Status { Active }",
      filename: "/repo/src/a/b/c/api.ts",
      options: [{ ignoreFiles: ["**/a/**/*.ts"] }],
    },
  ],
  invalid: [
    {
      name: "reports a numeric enum",
      code: NO_ENUM_DOCUMENTATION.examples[1].files[0].source,
      errors: [{ messageId: "noEnum" }],
    },
    {
      name: "reports a string enum",
      code: 'enum Color { Red = "red", Blue = "blue" }',
      errors: [{ messageId: "noEnum" }],
    },
    {
      name: "reports a const enum",
      code: "const enum Direction { Up, Down, Left, Right }",
      errors: [{ messageId: "noEnum" }],
    },
    {
      name: "reports a path outside a custom generated-file glob",
      code: "enum Status { Active }",
      filename: "/repo/src/normal.ts",
      options: [{ ignoreFiles: ["**/codegen/**"] }],
      errors: [{ messageId: "noEnum" }],
    },
    {
      name: "does not let a single-star glob cross a directory separator",
      code: "enum Status { Active }",
      filename: "/repo/src/codegen/deep/api.ts",
      options: [{ ignoreFiles: ["**/codegen/*.ts"] }],
      errors: [{ messageId: "noEnum" }],
    },
  ],
});
