import { RuleTester } from "@typescript-eslint/rule-tester";
import { afterAll, describe, it } from "vitest";

import rule, { noRestatedCommentDocumentation } from "../../src/rules/no-restated-comment.js";

RuleTester.afterAll = afterAll;
RuleTester.describe = describe;
RuleTester.it = it;
RuleTester.itOnly = it.only;

const ruleTester = new RuleTester();

ruleTester.run("no-restated-comment", rule, {
  valid: [
    { name: "accepts the documented reason comment", code: noRestatedCommentDocumentation.examples[0].files[0].source },
    { name: "accepts the result of the deletion suggestion", code: "const key = serialize(input);" },
    // One unmatched word means the comment carries something the code does not.
    {
      name: "keeps a comment when one content word is absent from the code",
      code: "// serialize the vault key\nconst [key] = serialize(bankKey);\nreturn null;",
    },
    // No prefix matching — `valid` is not `validate`, `config` is not `configure`.
    { code: "// valid config\nvalidate(configureAll());\nreturn null;" },
    // A single content word labels a thing; it does not restate a statement.
    { code: "// Hashing\nhash(b);\nreturn null;" },
    {
      name: "keeps a question even when its words appear in the statement",
      code: "// cached page data?\nconst pageData = getCachedPageData();\nreturn null;",
    },
    // The protected class is an exemption floor.
    { code: "// serialize key (PLT-812)\nconst key = serialize(k);\nreturn null;" },
    { code: "// serialize key — see https://example.com/keys\nconst key = serialize(k);\nreturn null;" },
    { code: "// serialize key every 30 seconds\nconst key = serialize(k);\nreturn null;" },
    { code: "// serialize key because the cache is keyed on it\nconst key = serialize(k);\nreturn null;" },
    // Modality, a colon lead-in, inline emphasis, a bare negation.
    { code: "// can also serialize key\nconst key = serialize(k);\nreturn null;" },
    { code: "// serialize key:\nconst key = serialize(k);\nreturn null;" },
    { code: "// serialize *key*\nconst key = serialize(k);\nreturn null;" },
    // zod/packages/zod/src/v4/classic/tests/refine.test.ts:546 — a NEGATIVE
    // property that the positive spelling below cannot state.
    { code: "// no issues with confirmPassword\nreturn payload.issues.every(hasNoConfirmPassword);" },
    // A run of `//` lines is a paragraph, not a label for the next statement.
    { code: "// why we do this at all\n// serialize key\nconst key = serialize(k);\nreturn null;" },
    // A comment above a block labels a region.
    { code: "// serialize key\nfunction serializeKey() { return 1; }" },
    { code: "// serialize key\nif (serializeKey()) { doIt(); }" },
    {
      name: "keeps a label above a multi-line statement",
      code: "// cached page data\nconst pageData = getCachedPageData(\n  pageKey,\n);\nreturn null;",
    },
    {
      name: "keeps a block comment because only one-line labels are in scope",
      code: "/* cached page data */\nconst pageData = getCachedPageData();\nreturn null;",
    },
    // A label heading a run of siblings of the same kind provides the grouping.
    // zod/packages/zod/src/v4/classic/tests/assignability.test.ts is a whole
    // table of these; it alone produced 89 hits before the sibling test worked.
    {
      code: "// $ZodString\nz.string() satisfies z.core.$ZodString;\nz.number() satisfies z.core.$ZodNumber;",
    },
    // A data declaration is labelled, not narrated.
    {
      name: "keeps a label above a plain data declaration",
      code: "// profile status\nconst profileStatus = STATUS;\nreturn null;",
    },
    // Commented-out code and banners belong to `no-comment-cruft`.
    { code: "// const key = serialize(k);\nconst key = serialize(k);\nreturn null;" },
    { code: "// ==== serialize ====\nconst key = serialize(k);\nreturn null;" },
    // A directive.
    { code: "// sarj-noqa: deliberate\nconst key = serialize(k);\nreturn null;" },
    // Non-ASCII prose the tokenizer cannot read.
    { code: "// تحديث المفتاح\nconst key = serialize(k);\nreturn null;" },
    // `no-comment-cruft` already owns the verb-led statement-head shape, so this
    // rule stays quiet on it rather than reporting the same comment twice.
    { code: "// increment the counter\ncounter += 1;\nreturn null;" },
    // A generated file mirrors its generator.
    {
      code: "// @generated by openapi\n// serialize key\nconst key = serialize(k);\nreturn null;",
      filename: "api.ts",
    },
    {
      name: "keeps prose one word beyond the eight-word budget",
      code: "// cached page data result output value item record entry\nconst cachedPageDataResultOutputValueItemRecordEntry = getCachedPageDataResultOutputValueItemRecordEntry();\nreturn null;",
    },
  ],
  invalid: [
    {
      name: "offers whole-line deletion without applying an autofix",
      code: noRestatedCommentDocumentation.examples[1].files[0].source,
      output: null,
      errors: [
        {
          messageId: "restatesLineBelow",
          suggestions: [
            {
              messageId: "deleteComment",
              output: "const key = serialize(input);",
            },
          ],
        },
      ],
    },
    {
      code: "// Serialize key\nconst [key] = serialize(_k);\nreturn null;",
      errors: [{ messageId: "restatesLineBelow", suggestions: 1 }],
    },
    {
      code: "// issue path length\nconst issues = sortByPathLength(error.issues);\nreturn null;",
      errors: [{ messageId: "restatesLineBelow", suggestions: 1 }],
    },
    {
      name: "preserves CRLF while deleting an indented comment line",
      code: "function collect() {\r\n\t// issue path length\r\n\treturn sortByPathLength(error.issues);\r\n}",
      output: null,
      errors: [
        {
          messageId: "restatesLineBelow",
          suggestions: [
            {
              messageId: "deleteComment",
              output: "function collect() {\r\n\treturn sortByPathLength(error.issues);\r\n}",
            },
          ],
        },
      ],
    },
    {
      code: "// Get the cached page data\nconst pageData = pageKey ? getCache().data : undefined;\nreturn null;",
      errors: [{ messageId: "restatesLineBelow", suggestions: 1 }],
    },
    // The trailing-`e` strip makes the inflection fold symmetric, so
    // `serialized` and `serialize` land on the same stem.
    {
      code: "// serialized values\nconst out = serializeValues(input);\nreturn null;",
      errors: [{ messageId: "restatesLineBelow", suggestions: 1 }],
    },
    {
      name: "reports a restatement at the eight-word budget",
      code: "// cached page data result output value item record\nconst cachedPageDataResultOutputValueItemRecord = getCachedPageDataResultOutputValueItemRecord();\nreturn null;",
      errors: [{ messageId: "restatesLineBelow", suggestions: 1 }],
    },
  ],
});
