import { RuleTester } from "@typescript-eslint/rule-tester";
import { afterAll, describe, it } from "vitest";

import rule from "../../src/rules/no-restated-comment.js";

RuleTester.afterAll = afterAll;
RuleTester.describe = describe;
RuleTester.it = it;
RuleTester.itOnly = it.only;

const ruleTester = new RuleTester();

ruleTester.run("no-restated-comment", rule, {
  valid: [
    // One unmatched word means the comment carries something the code does not.
    { code: "// serialize the vault key\nconst [key] = serialize(bankKey);\nreturn null;" },
    // No prefix matching — `valid` is not `validate`, `config` is not `configure`.
    { code: "// valid config\nvalidate(configureAll());\nreturn null;" },
    // A single content word labels a thing; it does not restate a statement.
    { code: "// Hashing\nhash(b);\nreturn null;" },
    // The protected class is an exemption floor.
    { code: "// serialize key (PLT-812)\nconst key = serialize(k);\nreturn null;" },
    { code: "// serialize key — see https://example.com/keys\nconst key = serialize(k);\nreturn null;" },
    { code: "// serialize key every 30 seconds\nconst key = serialize(k);\nreturn null;" },
    { code: "// serialize key because the cache is keyed on it\nconst key = serialize(k);\nreturn null;" },
    // Modality, a colon lead-in, inline emphasis, a bare negation.
    { code: "// can also serialize key\nconst key = serialize(k);\nreturn null;" },
    { code: "// serialize key:\nconst key = serialize(k);\nreturn null;" },
    { code: "// serialize *key*\nconst key = serialize(k);\nreturn null;" },
    // zod/packages/zod/src/v4/classic/tests/refine.test.ts:546 — a NEGATIVE
    // property that the positive spelling below cannot state.
    { code: "// no issues with confirmPassword\nreturn payload.issues.every(hasNoConfirmPassword);" },
    // A run of `//` lines is a paragraph, not a label for the next statement.
    { code: "// why we do this at all\n// serialize key\nconst key = serialize(k);\nreturn null;" },
    // A comment above a block labels a region.
    { code: "// serialize key\nfunction serializeKey() { return 1; }" },
    { code: "// serialize key\nif (serializeKey()) { doIt(); }" },
    // A label heading a run of siblings of the same kind provides the grouping.
    // zod/packages/zod/src/v4/classic/tests/assignability.test.ts is a whole
    // table of these; it alone produced 89 hits before the sibling test worked.
    {
      code: "// $ZodString\nz.string() satisfies z.core.$ZodString;\nz.number() satisfies z.core.$ZodNumber;",
    },
    // A data declaration is labelled, not narrated.
    { code: "// profile not found\nconst PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';\nreturn null;" },
    // Commented-out code and banners belong to `no-comment-cruft`.
    { code: "// const key = serialize(k);\nconst key = serialize(k);\nreturn null;" },
    { code: "// ==== serialize ====\nconst key = serialize(k);\nreturn null;" },
    // A directive.
    { code: "// sarj-noqa: deliberate\nconst key = serialize(k);\nreturn null;" },
    // Non-ASCII prose the tokenizer cannot read.
    { code: "// تحديث المفتاح\nconst key = serialize(k);\nreturn null;" },
    // `no-comment-cruft` already owns the verb-led statement-head shape, so this
    // rule stays quiet on it rather than reporting the same comment twice.
    { code: "// increment the counter\ncounter += 1;\nreturn null;" },
    // A generated file mirrors its generator.
    {
      code: "// @generated by openapi\n// serialize key\nconst key = serialize(k);\nreturn null;",
      filename: "api.ts",
    },
  ],
  invalid: [
    {
      code: "// Serialize key\nconst [key] = serialize(_k);\nreturn null;",
      errors: [{ messageId: "restatesLineBelow" }],
    },
    {
      code: "// issue path length\nconst issues = sortByPathLength(error.issues);\nreturn null;",
      errors: [{ messageId: "restatesLineBelow" }],
    },
    {
      code: "// Get the cached page data\nconst pageData = pageKey ? getCache().data : undefined;\nreturn null;",
      errors: [{ messageId: "restatesLineBelow" }],
    },
    // The trailing-`e` strip makes the inflection fold symmetric, so
    // `serialized` and `serialize` land on the same stem.
    {
      code: "// serialized values\nconst out = serializeValues(input);\nreturn null;",
      errors: [{ messageId: "restatesLineBelow" }],
    },
  ],
});
