import { RuleTester } from "@typescript-eslint/rule-tester";
import { afterAll, describe, it } from "vitest";

import rule, {
  NO_TRAILING_VALUE_NARRATION_DOCUMENTATION,
} from "../../src/rules/no-trailing-value-narration.js";

RuleTester.afterAll = afterAll;
RuleTester.describe = describe;
RuleTester.it = it;
RuleTester.itOnly = it.only;

const RULE_TESTER = new RuleTester();

RULE_TESTER.run("no-trailing-value-narration", rule, {
  valid: [
    { name: "accepts the result of the deletion suggestion", code: "const DEFAULT_TTL_MS = 5 * 60 * 1000;" },
    // A conversion the reader cannot do in their head is the comment worth having.
    { code: "const timeout = 300000; // ~3.5 days" },
    { code: "const window = 60 * 60 * 24 * 5; // about a working week" },
    // A why, not a restatement.
    { code: "const backoff = 2 * 60; // doubles per attempt, capped by the gateway" },
    {
      name: "allows a unit annotation that also explains a domain constraint",
      code: NO_TRAILING_VALUE_NARRATION_DOCUMENTATION.examples[0].files[0].source,
    },
    {
      name: "allows a comment when any stated number is absent from the code",
      code: "const timeout = 5 * 60; // 5 minutes with a 30-second cap",
    },
    // Owned by a ticket or a URL (protected-class signal S1).
    { code: "const retries = 3; // 3 retries (PLT-812)" },
    { code: "const retries = 3; // 3 retries — see https://example.com/limits" },
    // No literal on the line at all.
    { code: "const timeout = compute(); // 5 minutes" },
    // No number in the comment.
    { code: "const staleTime = 5 * 60 * 1000; // minutes" },
    // A directive.
    { code: "const staleTime = 5 * 60 * 1000; // TODO@example-owner: 5 minutes" },
    // Without a unit, the comment can state a domain fact or value mapping.
    { code: "const ounceToG = poundToG / 16; // 16 ounces to a pound" },
    { code: "for (let serviceNum = 0; serviceNum < 10; serviceNum++) {} // 10 services" },
    { code: "const map = { 0: off, 100: on }; // 0-Off 100-On" },
    // Positional bracketed values have no declaration name that can carry the unit.
    { code: "await setCook(\n  60, // 60 seconds\n);" },
    { code: "const cases = [\n  [0, 0], // 0 seconds -> 0\n];" },
    // An own-line comment is `no-comment-cruft`'s / `no-restated-comment`'s business.
    { code: "// 5 minutes\nconst staleTime = 5 * 60 * 1000;" },
    // A generated file mirrors its generator.
    {
      code: "// @generated by codegen\nconst staleTime = 5 * 60 * 1000; // 5 minutes",
      filename: "gen.ts",
    },
  ],
  invalid: [
    {
      name: "unit-bearing constant advice only asks to delete the narration",
      code: "const DEFAULT_TTL_MS = 5 * 60 * 1000; // 5 minutes",
      output: null,
      errors: [
        {
          messageId: "deleteNarration",
          suggestions: [
            {
              messageId: "removeNarration",
              output: "const DEFAULT_TTL_MS = 5 * 60 * 1000;",
            },
          ],
        },
      ],
    },
    {
      name: "short unit-bearing constant advice only asks to delete the narration",
      code: "const POLL_MS = 3 * 60 * 1000; // 3 min",
      errors: [{ messageId: "deleteNarration", suggestions: 1 }],
    },
    {
      name: "preserves CRLF after deleting trailing block narration",
      code: "const POLL_MS = 3 * 60 * 1000;\t/* 3 min */  \r\nnext();",
      output: null,
      errors: [
        {
          messageId: "deleteNarration",
          suggestions: [
            {
              messageId: "removeNarration",
              output: "const POLL_MS = 3 * 60 * 1000;\r\nnext();",
            },
          ],
        },
      ],
    },
    {
      name: "does not suggest deleting a block comment followed by code",
      code: "const POLL_MS = 3 * 60 * 1000; /* 3 min */ next();",
      output: null,
      errors: [{ messageId: "deleteNarration", suggestions: 0 }],
    },
    {
      code: "const payload = {\n  value: 60, // 60 seconds\n};",
      output: null,
      errors: [{ messageId: "narratesValue", suggestions: 0 }],
    },
    {
      code: NO_TRAILING_VALUE_NARRATION_DOCUMENTATION.examples[1].files[0].source,
      errors: [{ messageId: "narratesValue" }],
    },
    {
      code: "export const COOKIE_MAX_AGE_SECONDS = 60 * 60 * 24 * 90; // 90 days",
      errors: [{ messageId: "deleteNarration", suggestions: 1 }],
    },
    {
      code: "const options = { gcTime: 1000 * 60 * 60 * 24 }; // 24 hours",
      errors: [{ messageId: "narratesValue" }],
    },
    {
      code: "const poll = 30 * 1000; // 30 seconds",
      errors: [{ messageId: "narratesValue" }],
    },
    {
      code: "const announcementTimeoutSec = 5 * 60; // 5 minutes",
      errors: [{ messageId: "deleteNarration", suggestions: 1 }],
    },
    {
      code: "function configure() {\n  const timeout = 5 * 60; // 5 minutes\n}",
      errors: [{ messageId: "narratesValue" }],
    },
    // Identifier words on the line do not rescue the comment.
    {
      code: "const staleTime = 5 * 60 * 1000; // stale time 5 minutes",
      errors: [{ messageId: "narratesValue" }],
    },
  ],
});
