import * as tsParser from "@typescript-eslint/parser";
import { RuleTester } from "@typescript-eslint/rule-tester";
import { afterAll, describe, it } from "vitest";

import rule from "../../src/rules/no-unsafe-mock-casting.js";

RuleTester.afterAll = afterAll;
RuleTester.describe = describe;
RuleTester.it = it;
RuleTester.itOnly = it.only;

const ruleTester = new RuleTester({
  languageOptions: {
    parser: tsParser,
  },
});

ruleTester.run("no-unsafe-mock-casting", rule, {
  valid: [
    {
      name: "accepts the Vitest typed helper",
      code: "const m = vi.mocked(myFn);",
    },
    { name: "accepts the Jest typed helper", code: "const m = jest.mocked(myFn);" },
    {
      name: "ignores project-specific mock types",
      code: "const m = myFn as MyCustomMock;",
    },
    {
      name: "ignores project-specific types in angle-bracket assertions",
      code: "const m = <MyCustomMock>myFn;",
    },
    { name: "ignores unrelated type assertions", code: "const m = myFn as string;" },
    {
      name: "ignores generated file paths",
      code: "const m = myFn as jest.Mock;",
      filename: "test.generated.ts",
    },
    {
      name: "ignores generated file markers",
      code: "// @generated by test-codegen\nconst m = myFn as jest.Mock;",
    },
  ],
  invalid: [
    {
      name: "reports bare Mock assertions",
      code: "const m = myFn as Mock;",
      errors: [{ messageId: "unsafeMockCast" }],
      output: null,
    },
    {
      name: "reports vi.Mock assertions",
      code: "const m = myFn as vi.Mock;",
      errors: [{ messageId: "unsafeMockCast" }],
    },
    {
      name: "reports jest.Mock assertions",
      code: "const m = myFn as jest.Mock;",
      errors: [{ messageId: "unsafeMockCast" }],
    },
    {
      name: "reports bare MockInstance assertions",
      code: "const m = myFn as MockInstance;",
      errors: [{ messageId: "unsafeMockCast" }],
    },
    {
      name: "reports bare SpyInstance assertions",
      code: "const m = myFn as SpyInstance;",
      errors: [{ messageId: "unsafeMockCast" }],
    },
    {
      name: "reports angle-bracket Mock assertions",
      code: "const m = <Mock>myFn;",
      errors: [{ messageId: "unsafeMockCast" }],
    },
    {
      name: "reports qualified angle-bracket assertions",
      code: "const m = <jest.Mock>myFn;",
      errors: [{ messageId: "unsafeMockCast" }],
    },
    {
      name: "reports qualified MockInstance assertions",
      code: "const m = myFn as vitest.MockInstance;",
      errors: [{ messageId: "unsafeMockCast" }],
    },
    {
      name: "reports qualified SpyInstance assertions",
      code: "const m = myFn as jest.SpyInstance;",
      errors: [{ messageId: "unsafeMockCast" }],
    },
  ],
});
