import * as tsParser from "@typescript-eslint/parser";
import { RuleTester } from "@typescript-eslint/rule-tester";
import { afterAll, describe, it } from "vitest";

import rule, {
  NO_UNSAFE_MOCK_CASTING_DOCUMENTATION,
} from "../../src/rules/no-unsafe-mock-casting.js";

RuleTester.afterAll = afterAll;
RuleTester.describe = describe;
RuleTester.it = it;
RuleTester.itOnly = it.only;

const RULE_TESTER = new RuleTester({
  languageOptions: {
    parser: tsParser,
  },
});

RULE_TESTER.run("no-unsafe-mock-casting", rule, {
  valid: [
    {
      name: "accepts the Vitest typed helper",
      code: NO_UNSAFE_MOCK_CASTING_DOCUMENTATION.examples[0].files[0].source,
    },
    { name: "accepts the Jest typed helper", code: "const m = jest.mocked(myFn);" },
    {
      name: "ignores project-specific mock types",
      code: "const m = myFn as MyCustomMock;",
    },
    {
      name: "ignores project-specific types in angle-bracket assertions",
      code: "const m = <MyCustomMock>myFn;",
    },
    { name: "ignores unrelated type assertions", code: "const m = myFn as string;" },
    {
      name: "ignores an unrelated domain type named Mock",
      code: "interface Mock { id: string } const m = value as Mock;",
    },
    {
      name: "ignores an unrelated namespace member named Mock",
      code: 'import type * as domain from "./domain.js"; const m = value as domain.Mock;',
    },
    {
      name: "ignores generated file paths",
      code: "const m = myFn as jest.Mock;",
      filename: "test.generated.ts",
    },
    {
      name: "ignores generated file markers",
      code: "// @generated by test-codegen\nconst m = myFn as jest.Mock;",
    },
  ],
  invalid: [
    {
      name: "reports bare Mock assertions",
      code: 'import type { Mock } from "vitest"; const m = myFn as Mock;',
      errors: [{ messageId: "unsafeMockCast" }],
      output: null,
    },
    {
      name: "reports vi.Mock assertions",
      code: NO_UNSAFE_MOCK_CASTING_DOCUMENTATION.examples[1].files[0].source,
      errors: [{ messageId: "unsafeMockCast" }],
    },
    {
      name: "reports jest.Mock assertions",
      code: 'import type * as jest from "@jest/globals"; const m = myFn as jest.Mock;',
      errors: [{ messageId: "unsafeMockCast" }],
    },
    {
      name: "reports bare MockInstance assertions",
      code: 'import type { MockInstance } from "vitest"; const m = myFn as MockInstance;',
      errors: [{ messageId: "unsafeMockCast" }],
    },
    {
      name: "reports bare SpyInstance assertions",
      code: 'import type { SpyInstance } from "jest-mock"; const m = myFn as SpyInstance;',
      errors: [{ messageId: "unsafeMockCast" }],
    },
    {
      name: "reports bare Mocked assertions",
      code: 'import type { Mocked } from "vitest"; const m = service as Mocked<typeof service>;',
      errors: [{ messageId: "unsafeMockCast" }],
    },
    {
      name: "reports bare MockedFunction assertions",
      code: 'import type { MockedFunction } from "vitest"; const m = fn as MockedFunction<typeof fn>;',
      errors: [{ messageId: "unsafeMockCast" }],
    },
    {
      name: "reports bare MockedClass assertions",
      code: 'import type { MockedClass } from "@jest/globals"; const m = Service as MockedClass<typeof Service>;',
      errors: [{ messageId: "unsafeMockCast" }],
    },
    {
      name: "reports qualified MockedObject assertions",
      code: 'import type * as vitest from "vitest"; const m = service as vitest.MockedObject<typeof service>;',
      errors: [{ messageId: "unsafeMockCast" }],
    },
    {
      name: "reports angle-bracket Mock assertions",
      code: 'import type { Mock } from "vitest"; const m = <Mock>myFn;',
      errors: [{ messageId: "unsafeMockCast" }],
    },
    {
      name: "reports qualified angle-bracket assertions",
      code: 'import type * as jest from "@jest/globals"; const m = <jest.Mock>myFn;',
      errors: [{ messageId: "unsafeMockCast" }],
    },
    {
      name: "reports qualified MockInstance assertions",
      code: 'import type * as vitest from "vitest"; const m = myFn as vitest.MockInstance;',
      errors: [{ messageId: "unsafeMockCast" }],
    },
    {
      name: "reports qualified SpyInstance assertions",
      code: 'import type * as jest from "jest-mock"; const m = myFn as jest.SpyInstance;',
      errors: [{ messageId: "unsafeMockCast" }],
    },
  ],
});
