import { RuleTester } from "@typescript-eslint/rule-tester";
import { afterAll, describe, it } from "vitest";

import rule, {
  noUnionInCommentDocumentation,
} from "../../src/rules/no-union-in-comment.js";

RuleTester.afterAll = afterAll;
RuleTester.describe = describe;
RuleTester.it = it;
RuleTester.itOnly = it.only;

const ruleTester = new RuleTester();

ruleTester.run("no-union-in-comment", rule, {
  valid: [
    {
      name: "allows unquoted value lists because they are indistinguishable from prose",
      code: "interface R { kind: string; // one of: draft, sent, paid\n}",
    },
    {
      name: "allows numeric ranges because they describe units rather than unions",
      code: "interface R { percentage: number; // 0-100\n}",
    },
    {
      name: "allows decimal numeric ranges",
      code: "interface R { confidence: number; // 0..1\n}",
    },
    // Already a union: the type holds the set, so there is nothing to move.
    { code: noUnionInCommentDocumentation.examples[0].files[0].source },
    // The comment restates a union the declaration already spells. That is a
    // restatement, which `no-restated-comment` owns — not a missing type.
    { code: "interface R { kind: 'aa' | 'bb'; // 'aa' | 'bb'\n}" },
    // One literal is an EXAMPLE, not a closed set. Kills MIN_UNION_MEMBERS.
    { code: "interface R { kind: string; // 'aa'\n}" },
    // A list inside a sentence is prose that quotes values; the sentence is what
    // carries the meaning. Kills the `^...$` anchoring of UNION_BODY_RE.
    {
      code: "interface R { kind: string; // set to 'aa' unless the caller passed 'bb' already\n}",
    },
    { code: "interface R { kind: string; // 'aa' and 'bb' are legacy spellings we still accept\n}" },
    // A separator between two quoted values does NOT make a sentence a list.
    // Kills the `^...$` anchoring on its own.
    {
      code: "interface R { kind: string; // prefer 'aa', 'bb' is what the legacy importer still writes\n}",
    },
    // Quoted sentences are messages, not enum members. Kills MAX_LITERAL_LENGTH.
    {
      code: "interface R { kind: string; // 'the requested resource was not found' | 'the upstream call timed out'\n}",
    },
    // Not a string: the set cannot become a string-literal union.
    { code: "interface R { kind: number; // 'aa' | 'bb'\n}" },
    { code: "interface R { kind: Kind; // 'aa' | 'bb'\n}" },
    // No annotation and no column builder to read a type off.
    { code: "const row = { kind: pick(), // 'aa' | 'bb'\n};" },
    // A number column is not a string column either.
    { code: "const t = { kind: integer('kind'), // 'aa' | 'bb'\n};" },
    // A directive prefix and a ticket id both stop the body being a bare list,
    // so the anchor rejects them without a guard of their own.
    { code: "interface R { kind: string; // biome-ignore lint: 'aa' | 'bb'\n}" },
    { code: "interface R { kind: string; // PLT-812: 'aa' | 'bb'\n}" },
    // The column already carries the union; the comment beside it restates it.
    {
      code: "const t = pgTable('t', {\n  kind: text('kind').$type<'aa' | 'bb'>(), // 'aa' | 'bb'\n});",
    },
    // A leading comment must own its line and sit directly above the member.
    { code: "interface R {\n  // 'aa' | 'bb'\n\n  kind: string;\n}" },
    // A trailing comment must FOLLOW the member it is read against; this one
    // opens the line that the member below it starts on.
    { code: "interface R {\n  /* 'aa' | 'bb' */ kind: string;\n}" },
    // Generated output mirrors its generator.
    {
      code: "// @generated by codegen\ninterface R { kind: string; // 'aa' | 'bb'\n}",
      filename: "gen.ts",
    },
  ],
  invalid: [
    // The shape as first-party schema code writes it.
    {
      code: noUnionInCommentDocumentation.examples[1].files[0].source,
      errors: [{ messageId: "unionInComment" }],
    },
    // Above the member rather than beside it.
    {
      code: "interface R {\n  // 'aa' | 'bb'\n  kind: string;\n}",
      errors: [{ messageId: "unionInComment" }],
    },
    // Commas and slashes separate a set as readily as pipes do.
    {
      code: "interface R {\n  kind: string; // 'aa', 'bb', 'cc'\n}",
      errors: [{ messageId: "unionInComment" }],
    },
    {
      code: 'interface R {\n  kind: string; // "aa" / "bb"\n}',
      errors: [{ messageId: "unionInComment" }],
    },
    // A lead-in only announces the list.
    {
      code: "interface R {\n  kind: string; // one of: 'aa' | 'bb'\n}",
      errors: [{ messageId: "unionInComment" }],
    },
    // `string | null` is still an unconstrained string.
    {
      code: "interface R {\n  kind: string | null; // 'aa' | 'bb'\n}",
      errors: [{ messageId: "unionInComment" }],
    },
    // `string[]` holds members of the same closed set, one element at a time.
    {
      code: "interface R {\n  kinds: string[]; // 'aa' | 'bb'\n}",
      errors: [{ messageId: "unionInComment" }],
    },
    // A class field is a declaration like any other.
    {
      code: "class R {\n  kind: string = ''; // 'aa' | 'bb'\n}",
      errors: [{ messageId: "unionInComment" }],
    },
    // A `const` with an explicit annotation.
    {
      code: "const kind: string = load(); // 'aa' | 'bb'\n",
      errors: [{ messageId: "unionInComment" }],
    },
    // A schema row, where the type lives in the column builder. The separator
    // the row ends on belongs to the object, so resolving it must step back.
    {
      code: "const t = pgTable('t', {\n  kind: text('kind').notNull(), // 'aa' | 'bb'\n});",
      errors: [{ messageId: "unionInComment" }],
    },
    // A default spells ONE of the values; the other two are still nowhere.
    {
      code: "const t = pgTable('t', {\n  kind: varchar('kind').default('aa'), // 'aa' | 'bb' | 'cc'\n});",
      errors: [{ messageId: "unionInComment" }],
    },
    // A block comment says it the same way.
    {
      code: "interface R {\n  kind: string; /* 'aa' | 'bb' */\n}",
      errors: [{ messageId: "unionInComment" }],
    },
  ],
});
