import { join } from "node:path";

import * as tsParser from "@typescript-eslint/parser";
import { RuleTester } from "@typescript-eslint/rule-tester";
import { afterAll, describe, it } from "vitest";

import rule from "../../src/rules/no-zod-native-enum.js";

RuleTester.afterAll = afterAll;
RuleTester.describe = describe;
RuleTester.it = it;
RuleTester.itOnly = it.only;

const ruleTester = new RuleTester({
  languageOptions: {
    parser: tsParser,
    parserOptions: {
      projectService: {
        allowDefaultProject: ["*.ts*", "*/*.ts*", "*/*/*.ts*"],
      },
      tsconfigRootDir: join(import.meta.dirname, "..", "fixtures"),
    },
  },
});

ruleTester.run("no-zod-native-enum", rule, {
  valid: [
    {
      name: "allows nativeEnum coverage in test files",
      code: 'import { z } from "zod"; const fruitEnum = z.nativeEnum(Fruits);',
      filename: "tests/nativeEnum.test.ts",
    },
    {
      name: "allows z.enum with inline string literals",
      code: 'const S = z.enum(["active", "inactive"]);',
    },
    {
      name: "allows z.enum with an as-const string array",
      code: 'const STATUSES = ["active", "inactive"] as const; const S = z.enum(STATUSES);',
    },
    {
      name: "allows z.enum with a readonly string tuple",
      code: 'const STATUSES: readonly ["a", "b"] = ["a", "b"]; const S = z.enum(STATUSES);',
    },
    {
      name: "allows a same-named local helper",
      code: "function nativeEnum(x: unknown) { return x; }\nconst S = nativeEnum({ A: 'a' });",
    },
    {
      name: "allows nativeEnum imported from a non-zod module",
      code: "import { nativeEnum } from './my-utils';\nconst S = nativeEnum({ A: 'a' });",
    },
    {
      name: "ignores generated directories",
      code: "const S = z.nativeEnum(Status);",
      filename: "src/generated/api.ts",
    },
    {
      name: "ignores gen filename suffixes",
      code: "const S = z.nativeEnum(Status);",
      filename: "api.gen.ts",
    },
    {
      name: "ignores generated filename suffixes",
      code: "const S = z.nativeEnum(Status);",
      filename: "api.generated.ts",
    },
    {
      name: "ignores declaration files",
      code: "const S = z.nativeEnum(Status);",
      filename: "api.d.ts",
    },
    {
      name: "ignores generated header markers",
      code: "// @generated by openapi-typescript\nconst S = z.nativeEnum(Status);",
    },
    {
      name: "allows z.enum with a non-identifier argument",
      code: 'const S = z.enum(["a", "b"] as const);',
    },
    {
      name: "allows the enum accessor on a schema",
      code: "const values = MySchema.enum;",
    },
  ],
  invalid: [
    {
      name: "reports nativeEnum in production schemas",
      code: 'import { z } from "zod"; const ZFruit = z.nativeEnum(Fruits);',
      filename: "schemas/fruit.ts",
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "fixes an inline string-valued object",
      code: 'const S = z.nativeEnum({ Active: "active", Inactive: "inactive" });',
      output: 'const S = z.enum(["active", "inactive"]);',
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "fixes an as-const object",
      code: "const S = z.nativeEnum({ A: 'a', B: 'b' } as const);",
      output: "const S = z.enum(['a', 'b']);",
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "fixes an object wrapped by satisfies",
      code: "const S = z.nativeEnum({ A: 'a', B: 'b' } satisfies Record<string, string>);",
      output: "const S = z.enum(['a', 'b']);",
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "deduplicates values in the fix",
      code: 'const S = z.nativeEnum({ A: "x", B: "x", C: "y" });',
      output: 'const S = z.enum(["x", "y"]);',
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports numeric members without fixing",
      code: "const S = z.nativeEnum({ Low: 0, High: 1 });",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports mixed string and numeric members without fixing",
      code: 'const S = z.nativeEnum({ A: "a", B: 2 });',
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports spread properties without fixing",
      code: 'const S = z.nativeEnum({ ...BASE, A: "a" });',
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports computed properties without fixing",
      code: 'const S = z.nativeEnum({ [k]: "a" });',
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports shorthand object properties without fixing",
      code: "const A = 'a'; const S = z.nativeEnum({ A });",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports object methods without fixing",
      code: "const S = z.nativeEnum({ A() { return 'a'; } });",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports an empty object without producing z.enum([])",
      code: "const S = z.nativeEnum({});",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports identifier arguments without duplicating their values",
      code: "const S = z.nativeEnum(Fruits);",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports a local TypeScript enum passed to nativeEnum",
      code: "enum Status { Active = 'active' }\nconst S = z.nativeEnum(Status);",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports nativeEnum on a zod namespace import",
      code: "import * as zod from 'zod';\nconst S = zod.nativeEnum(Fruits);",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports a bare zod import without an invalid callee fix",
      code: "import { nativeEnum } from 'zod';\nconst S = nativeEnum({ A: 'a' });",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "recognizes zod subpath imports",
      code: "import { nativeEnum } from 'zod/v4';\nconst S = nativeEnum(Fruits);",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "recognizes aliased zod imports",
      code: "import { nativeEnum as zEnum } from 'zod';\nconst S = zEnum(Fruits);",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "fixes nativeEnum inside a chained schema",
      code: 'const S = z.object({ s: z.nativeEnum({ A: "a" }).optional() });',
      output: 'const S = z.object({ s: z.enum(["a"]).optional() });',
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports z.enum with a local TypeScript enum",
      code: "enum Status { Active = 'active', Done = 'done' }\nconst S = z.enum(Status);",
      output: null,
      errors: [{ messageId: "enumOfTsEnum", data: { name: "Status" } }],
    },
    {
      name: "reports z.enum with a local const enum",
      code: "const enum Dir { Up = 'up' }\nconst S = z.enum(Dir);",
      output: null,
      errors: [{ messageId: "enumOfTsEnum" }],
    },
    {
      name: "reports z.enum with an imported TypeScript enum",
      code: "import { ImportedStatus } from './zod-enum.js';\nconst S = z.enum(ImportedStatus);",
      filename: "schema.ts",
      output: null,
      errors: [
        { messageId: "enumOfTsEnum", data: { name: "ImportedStatus" } },
      ],
    },
  ],
});
