import { join } from "node:path";

import * as tsParser from "@typescript-eslint/parser";
import { RuleTester } from "@typescript-eslint/rule-tester";
import { afterAll, describe, it } from "vitest";

import rule, {
  NO_ZOD_NATIVE_ENUM_DOCUMENTATION,
} from "../../src/rules/no-zod-native-enum.js";

RuleTester.afterAll = afterAll;
RuleTester.describe = describe;
RuleTester.it = it;
RuleTester.itOnly = it.only;

const RULE_TESTER = new RuleTester({
  languageOptions: {
    parser: tsParser,
    parserOptions: {
      projectService: {
        allowDefaultProject: ["*.ts*", "*/*.ts*", "*/*/*.ts*"],
      },
      tsconfigRootDir: join(import.meta.dirname, "..", "fixtures"),
    },
  },
});
const withZod = (code: string): string => `import { z } from "zod"; ${code}`;

RULE_TESTER.run("no-zod-native-enum", rule, {
  valid: [
    {
      name: "allows nativeEnum coverage in test files",
      code: 'import { z } from "zod"; const fruitEnum = z.nativeEnum(Fruits);',
      filename: "tests/nativeEnum.test.ts",
    },
    {
      name: "allows z.enum with inline string literals",
      code: NO_ZOD_NATIVE_ENUM_DOCUMENTATION.examples[0].files[0].source,
    },
    {
      name: "allows z.enum with an as-const string array",
      code: 'const STATUSES = ["active", "inactive"] as const; const S = z.enum(STATUSES);',
    },
    {
      name: "allows z.enum with a readonly string tuple",
      code: 'const STATUSES: readonly ["a", "b"] = ["a", "b"]; const S = z.enum(STATUSES);',
    },
    {
      name: "allows a same-named local helper",
      code: "function nativeEnum(x: unknown) { return x; }\nconst S = nativeEnum({ A: 'a' });",
    },
    {
      name: "allows nativeEnum imported from a non-zod module",
      code: "import { nativeEnum } from './my-utils';\nconst S = nativeEnum({ A: 'a' });",
    },
    {
      name: "ignores generated directories",
      code: "const S = z.nativeEnum(Status);",
      filename: "src/generated/api.ts",
    },
    {
      name: "ignores gen filename suffixes",
      code: "const S = z.nativeEnum(Status);",
      filename: "api.gen.ts",
    },
    {
      name: "ignores generated filename suffixes",
      code: "const S = z.nativeEnum(Status);",
      filename: "api.generated.ts",
    },
    {
      name: "ignores declaration files",
      code: "const S = z.nativeEnum(Status);",
      filename: "api.d.ts",
    },
    {
      name: "ignores generated header markers",
      code: "// @generated by openapi-typescript\nconst S = z.nativeEnum(Status);",
    },
    {
      name: "allows z.enum with a non-identifier argument",
      code: 'const S = z.enum(["a", "b"] as const);',
    },
    {
      name: "allows the enum accessor on a schema",
      code: "const values = MySchema.enum;",
    },
    {
      name: "allows a block-scoped namespace shadow",
      code: `
        import { z } from "zod";
        function f() {
          const z = { nativeEnum: (value: unknown) => value };
          return z.nativeEnum({ A: "a" });
        }
      `,
    },
    {
      name: "allows a parameter shadow of a named import",
      code: `
        import { nativeEnum } from "zod";
        function f(nativeEnum: (value: unknown) => unknown) {
          return nativeEnum({ A: "a" });
        }
      `,
    },
  ],
  invalid: [
    {
      name: "reports a string-literal computed nativeEnum member",
      code: 'import { z } from "zod"; const ZFruit = z["nativeEnum"](Fruits);',
      filename: "schemas/fruit.ts",
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports nativeEnum in production schemas",
      code: 'import { z } from "zod"; const ZFruit = z.nativeEnum(Fruits);',
      filename: "schemas/fruit.ts",
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "fixes an inline string-valued object",
      code: NO_ZOD_NATIVE_ENUM_DOCUMENTATION.examples[1].files[0].source,
      output: NO_ZOD_NATIVE_ENUM_DOCUMENTATION.examples[1].fixedFiles[0].source,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "fixes an as-const object",
      code: withZod("const S = z.nativeEnum({ A: 'a', B: 'b' } as const);"),
      output: withZod("const S = z.enum(['a', 'b']);"),
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "fixes an object wrapped by satisfies",
      code: withZod("const S = z.nativeEnum({ A: 'a', B: 'b' } satisfies Record<string, string>);"),
      output: withZod("const S = z.enum(['a', 'b']);"),
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "deduplicates values in the fix",
      code: withZod('const S = z.nativeEnum({ A: "x", B: "x", C: "y" });'),
      output: withZod('const S = z.enum(["x", "y"]);'),
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports numeric members without fixing",
      code: withZod("const S = z.nativeEnum({ Low: 0, High: 1 });"),
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports mixed string and numeric members without fixing",
      code: withZod('const S = z.nativeEnum({ A: "a", B: 2 });'),
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports spread properties without fixing",
      code: withZod('const S = z.nativeEnum({ ...BASE, A: "a" });'),
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports computed properties without fixing",
      code: withZod('const S = z.nativeEnum({ [k]: "a" });'),
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports shorthand object properties without fixing",
      code: withZod("const A = 'a'; const S = z.nativeEnum({ A });"),
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports object methods without fixing",
      code: withZod("const S = z.nativeEnum({ A() { return 'a'; } });"),
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports an empty object without producing z.enum([])",
      code: withZod("const S = z.nativeEnum({});"),
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports identifier arguments without duplicating their values",
      code: withZod("const S = z.nativeEnum(Fruits);"),
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports a local TypeScript enum passed to nativeEnum",
      code: withZod("enum Status { Active = 'active' }\nconst S = z.nativeEnum(Status);"),
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports nativeEnum on a zod namespace import",
      code: "import * as zod from 'zod';\nconst S = zod.nativeEnum(Fruits);",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports a bare zod import without an invalid callee fix",
      code: "import { nativeEnum } from 'zod';\nconst S = nativeEnum({ A: 'a' });",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "recognizes zod subpath imports",
      code: "import { nativeEnum } from 'zod/v4';\nconst S = nativeEnum(Fruits);",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "recognizes aliased zod imports",
      code: "import { nativeEnum as zEnum } from 'zod';\nconst S = zEnum(Fruits);",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "fixes nativeEnum inside a chained schema",
      code: withZod('const S = z.object({ s: z.nativeEnum({ A: "a" }).optional() });'),
      output: withZod('const S = z.object({ s: z.enum(["a"]).optional() });'),
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      name: "reports z.enum with a local TypeScript enum",
      code: withZod("enum Status { Active = 'active', Done = 'done' }\nconst S = z.enum(Status);"),
      output: null,
      errors: [{ messageId: "enumOfTsEnum", data: { name: "Status" } }],
    },
    {
      name: "reports z.enum with a local const enum",
      code: withZod("const enum Dir { Up = 'up' }\nconst S = z.enum(Dir);"),
      output: null,
      errors: [{ messageId: "enumOfTsEnum" }],
    },
    {
      name: "reports z.enum with a type-asserted local enum",
      code: withZod("enum Status { Active = 'active' }\nconst S = z.enum(Status as any);"),
      output: null,
      errors: [{ messageId: "enumOfTsEnum" }],
    },
    {
      name: "reports z.enum with a satisfies-wrapped local enum",
      code: withZod("enum Status { Active = 'active' }\nconst S = z.enum(Status satisfies object);"),
      output: null,
      errors: [{ messageId: "enumOfTsEnum" }],
    },
    {
      name: "reports z.enum with an imported TypeScript enum",
      code: "import { z } from 'zod';\nimport { ImportedStatus } from './zod-enum.js';\nconst S = z.enum(ImportedStatus);",
      filename: "schema.ts",
      output: null,
      errors: [
        { messageId: "enumOfTsEnum", data: { name: "ImportedStatus" } },
      ],
    },
  ],
});
