import { join } from "node:path";

import * as tsParser from "@typescript-eslint/parser";
import { RuleTester } from "@typescript-eslint/rule-tester";
import { afterAll, describe, it } from "vitest";

import rule from "../../src/rules/no-zod-native-enum.js";

RuleTester.afterAll = afterAll;
RuleTester.describe = describe;
RuleTester.it = it;
RuleTester.itOnly = it.only;

const ruleTester = new RuleTester({
  languageOptions: {
    parser: tsParser,
    parserOptions: {
      projectService: {
        allowDefaultProject: ["*.ts*", "*/*.ts*", "*/*/*.ts*"],
      },
      tsconfigRootDir: join(import.meta.dirname, "..", "fixtures"),
    },
  },
});

ruleTester.run("no-zod-native-enum", rule, {
  valid: [
    // FP guard, corpus: zod/packages/zod/src/v3/tests/nativeEnum.test.ts:12 —
    // a test that covers `z.nativeEnum` has to call `z.nativeEnum`.
    {
      code: 'import { z } from "zod"; const fruitEnum = z.nativeEnum(Fruits);',
      filename: "tests/nativeEnum.test.ts",
    },
    // The prescribed pattern.
    { code: 'const S = z.enum(["active", "inactive"]);' },
    // `z.enum` over an `as const` array of literals — also prescribed.
    {
      code: 'const STATUSES = ["active", "inactive"] as const; const S = z.enum(STATUSES);',
    },
    // `z.enum` over a plain `readonly string[]` binding — not an enum.
    {
      code: 'const STATUSES: readonly ["a", "b"] = ["a", "b"]; const S = z.enum(STATUSES);',
    },
    // A same-named local helper that is not zod's `nativeEnum`.
    {
      code: "function nativeEnum(x: unknown) { return x; }\nconst S = nativeEnum({ A: 'a' });",
    },
    // Imported from somewhere that is not zod.
    {
      code: "import { nativeEnum } from './my-utils';\nconst S = nativeEnum({ A: 'a' });",
    },
    // Generated files opt out, matching `no-enum`.
    {
      code: "const S = z.nativeEnum(Status);",
      filename: "src/generated/api.ts",
    },
    {
      code: "const S = z.nativeEnum(Status);",
      filename: "api.gen.ts",
    },
    {
      code: "// @generated by openapi-typescript\nconst S = z.nativeEnum(Status);",
    },
    // `z.enum` with a non-identifier argument is never the TS-enum shape.
    { code: 'const S = z.enum(["a", "b"] as const);' },
    // Unrelated `.enum` accessor on a schema (zod exposes `Schema.enum`).
    { code: "const values = MySchema.enum;" },
  ],
  invalid: [
    // Production schemas still fire.
    {
      code: 'import { z } from "zod"; const ZFruit = z.nativeEnum(Fruits);',
      filename: "schemas/fruit.ts",
      errors: [{ messageId: "nativeEnum" }],
    },
    // Inline object literal of string values — autofixed.
    {
      code: 'const S = z.nativeEnum({ Active: "active", Inactive: "inactive" });',
      output: 'const S = z.enum(["active", "inactive"]);',
      errors: [{ messageId: "nativeEnum" }],
    },
    // `as const` wrapper is unwrapped before the fix.
    {
      code: "const S = z.nativeEnum({ A: 'a', B: 'b' } as const);",
      output: "const S = z.enum(['a', 'b']);",
      errors: [{ messageId: "nativeEnum" }],
    },
    // Duplicate values collapse — `z.enum` requires a unique member list.
    {
      code: 'const S = z.nativeEnum({ A: "x", B: "x", C: "y" });',
      output: 'const S = z.enum(["x", "y"]);',
      errors: [{ messageId: "nativeEnum" }],
    },
    // Numeric members are NOT fixed: `z.enum` takes strings only, so rewriting
    // would silently change the accepted input.
    {
      code: "const S = z.nativeEnum({ Low: 0, High: 1 });",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    // Mixed string/number members are likewise not fixed.
    {
      code: 'const S = z.nativeEnum({ A: "a", B: 2 });',
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    // A spread makes the member set non-static — report only.
    {
      code: 'const S = z.nativeEnum({ ...BASE, A: "a" });',
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    // A computed key is not statically rewritable.
    {
      code: 'const S = z.nativeEnum({ [k]: "a" });',
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    // An empty object would fix to the invalid `z.enum([])` — report only.
    {
      code: "const S = z.nativeEnum({});",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    // Identifier argument: inlining would duplicate the set the object owns.
    {
      code: "const S = z.nativeEnum(Fruits);",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      code: "enum Status { Active = 'active' }\nconst S = z.nativeEnum(Status);",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    // Namespace-style import.
    {
      code: "import * as zod from 'zod';\nconst S = zod.nativeEnum(Fruits);",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    // Bare named import from zod — reported, never fixed (`enum` is reserved).
    {
      code: "import { nativeEnum } from 'zod';\nconst S = nativeEnum({ A: 'a' });",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    {
      code: "import { nativeEnum } from 'zod/v4';\nconst S = nativeEnum(Fruits);",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    // Aliased named import from zod.
    {
      code: "import { nativeEnum as zEnum } from 'zod';\nconst S = zEnum(Fruits);",
      output: null,
      errors: [{ messageId: "nativeEnum" }],
    },
    // Chained schema call.
    {
      code: 'const S = z.object({ s: z.nativeEnum({ A: "a" }).optional() });',
      output: 'const S = z.object({ s: z.enum(["a"]).optional() });',
      errors: [{ messageId: "nativeEnum" }],
    },
    // zod v4's `z.enum(TsEnum)` — the same hole under a friendlier name.
    // Resolved lexically to a `TSEnumDeclaration` in this file.
    {
      code: "enum Status { Active = 'active', Done = 'done' }\nconst S = z.enum(Status);",
      output: null,
      errors: [{ messageId: "enumOfTsEnum", data: { name: "Status" } }],
    },
    // A `const enum` resolves the same way.
    {
      code: "const enum Dir { Up = 'up' }\nconst S = z.enum(Dir);",
      output: null,
      errors: [{ messageId: "enumOfTsEnum" }],
    },
  ],
});
