// vitest: shared-module-graph
import * as tsParser from "@typescript-eslint/parser";
import { RuleTester } from "@typescript-eslint/rule-tester";
import { afterAll, describe, it } from "vitest";

import rule, {
  PREFER_IMMUTABLE_MODULE_CONSTANT_DOCUMENTATION,
} from "../../src/rules/prefer-immutable-module-constant.js";

RuleTester.afterAll = afterAll;
RuleTester.describe = describe;
RuleTester.it = it;
RuleTester.itOnly = it.only;

const RULE_TESTER = new RuleTester({
  languageOptions: {
    parser: tsParser,
    parserOptions: { ecmaVersion: "latest", sourceType: "module" },
  },
});

RULE_TESTER.run("prefer-immutable-module-constant", rule, {
  valid: [
    "const VALUES = [1, 2, 3]; let alias = VALUES; alias.push(4);",
    "const VALUES = [1, 2, 3]; var alias = VALUES; alias[0] = 4;",
    PREFER_IMMUTABLE_MODULE_CONSTANT_DOCUMENTATION.examples[0].files[0].source,
    "const VALUES = [1, 2, 3] as const satisfies readonly number[];",
    "const VALUES: readonly number[] = [1, 2, 3];",
    "const VALUES: ReadonlyArray<number> = [1, 2, 3];",
    "const VALUES = [1, 2, 3] as readonly number[];",
    "const LABELS: Readonly<Record<string, string>> = { a: 'A' };",
    "const LABELS = { a: 'A' } as Readonly<Record<string, string>>;",
    "const LABELS = Object.freeze({ a: 'A' });",
    "const LABELS = Object.freeze({ a: 'A' }) satisfies Readonly<Record<string, string>>;",
    "const KINDS: ReadonlySet<string> = new Set(['a']);",
    "const LOOKUP: ReadonlyMap<string, number> = new Map([['a', 1]]);",
    "const value = { a: 1 };",
    "const routes = ['home', 'settings'];",
    "const routes = ['local']; export { routes } from './upstream';",
    "const routes = ['local']; export type { routes };",
    "const VALUES = ([1, 2] as const)!;",
    "type Routes = readonly string[]; export const routes: Routes = [];",
    "type Routes = ReadonlyArray<string>; export const routes: Routes = [];",
    "type Readonly = readonly string[]; export const VALUES: Readonly = ['a'];",
    "type Readonly = { readonly a: string }; export const LABELS: Readonly = { a: 'A' };",
    "type Readonly = {}; export const LABELS: Readonly = { a: 'A' };",
    "type Labels = { readonly [key: string]: string }; export const LABELS: Labels = { a: 'A' };",
    "type Readonly<T> = readonly T[]; export const VALUES: Readonly<string> = ['a'];",
    "type Surface<T> = Readonly<T>; export const LABELS: Surface<{ a: string }> = { a: 'A' };",
    "type Readonly<T> = T; export const LABELS: Readonly<{ readonly a: string }> = { a: 'A' };",
    "type Identity<T> = T; export const VALUES: Identity<Identity<readonly string[]>> = ['a'];",
    "type Surface<T = readonly string[]> = T; export const VALUES: Surface = ['a'];",
    "const Readonly = 1; export const LABELS: Readonly<{ a: string }> = { a: 'A' };",
    "function unrelated<Readonly>() {} export const LABELS: Readonly<{ a: string }> = { a: 'A' };",
    "import type { Readonly } from './types'; export const LABELS: Readonly = { a: 'A' };",
    "import type { Readonly } from './types'; export const LABELS = { a: 'A' } as Readonly;",
    "import type { Surface } from './types'; type Readonly = Surface; export const LABELS: Readonly = { a: 'A' };",
    "import type * as Types from './types'; type Readonly = Types.Surface; export const LABELS: Readonly = { a: 'A' };",
    "type Readonly = Other; type Other = Readonly; export const LABELS: Readonly = { a: 'A' };",
    "interface Readonly { readonly a: string } export const LABELS: Readonly = { a: 'A' };",
    { code: "export const routes = ['home'];", filename: "src/routes.js" },
    { code: "export const routes = ['home'];", filename: "src/routes.mjs" },
    "function build() { const VALUES = [1, 2, 3]; return VALUES; }",
    "let VALUES = [1, 2, 3];",
    "const VALUES = createValues();",
    "const VALUES = [1, 2, 3]; VALUES.push(4);",
    "const LABELS = { a: 'A' }; LABELS.a = 'B';",
    "const LABELS = { nested: { value: 'A' } }; LABELS.nested.value = 'B';",
    "const LABELS = { nested: [] as string[] }; LABELS.nested.push('A');",
    "const VALUES = [1, 2, 3]; const alias = VALUES; alias.push(4);",
    "const LABELS = { nested: [] as string[] }; const alias = LABELS; alias.nested.push('A');",
    "const LABELS = { a: 'A' }; Object.assign(LABELS, { a: 'B' });",
    "const VALUES = [1, 2]; VALUES['push'](3);",
    { code: "const VALUES = [1, 2, 3];", filename: "src/value.test.ts" },
    { code: "// generated by schema\nconst VALUES = [1, 2, 3];", filename: "src/value.ts" },
    { code: "const VALUES = [1, 2, 3];", filename: "src/openapi-gen/value.ts" },
    { code: "const VALUES = [1, 2, 3] as const;", filename: "src/value.types.ts" },
    "class Set<T> { constructor(_values: T[]) {} } const KINDS = new Set(['a']);",
    "class Map<K, V> { constructor(_values: [K, V][]) {} } const LOOKUP = new Map([['a', 1]]);",
    "const Object = { freeze: <T>(value: T): T => value }; const VALUES = Object.freeze([1, 2, 3]);",
  ],
  invalid: [
    {
      code: "type Readonly<T> = readonly T[]; type Surface<Readonly> = Readonly; export const LABELS: Surface<{ a: string }> = { a: 'A' };",
      errors: [{ messageId: "preferAsConst", data: { name: "LABELS" } }],
    },
    {
      code: "type Readonly = { a: string }; export const LABELS: Readonly = { a: 'A' };",
      errors: [{ messageId: "preferAsConst", data: { name: "LABELS" } }],
    },
    {
      code: "type Readonly<T> = T; export const LABELS: Readonly<{ a: string }> = { a: 'A' };",
      errors: [{ messageId: "preferAsConst", data: { name: "LABELS" } }],
    },
    {
      code: "type Readonly = { a: string }; type Surface = Readonly; export const LABELS: Surface = { a: 'A' };",
      errors: [{ messageId: "preferAsConst", data: { name: "LABELS" } }],
    },
    {
      code: "export const LABELS = { a: 'A' } as Readonly; type Readonly = { a: string };",
      errors: [{ messageId: "preferAsConst", data: { name: "LABELS" } }],
    },
    {
      code: "type ReadonlyArray<T> = T[]; export const VALUES: ReadonlyArray<string> = ['a'];",
      errors: [{ messageId: "preferAsConst", data: { name: "VALUES" } }],
    },
    {
      code: "type ReadonlySet<T> = Set<T>; export const KINDS: ReadonlySet<string> = new Set(['a']);",
      errors: [{ messageId: "preferReadonlyCollection", data: { name: "KINDS", kind: "Set" } }],
    },
    {
      code: "type ReadonlyMap<K, V> = Map<K, V>; export const LOOKUP: ReadonlyMap<string, number> = new Map([['a', 1]]);",
      errors: [{ messageId: "preferReadonlyCollection", data: { name: "LOOKUP", kind: "Map" } }],
    },
    {
      code: PREFER_IMMUTABLE_MODULE_CONSTANT_DOCUMENTATION.examples[1].files[0].source,
      errors: [{ messageId: "preferAsConst", data: { name: "VALUES" } }],
    },
    {
      code: "const _VALUES = [1, 2, 3];",
      errors: [{ messageId: "preferAsConst", data: { name: "_VALUES" } }],
    },
    {
      code: "const X = [1, 2, 3];",
      errors: [{ messageId: "preferAsConst", data: { name: "X" } }],
    },
    {
      code: "const VALUES = [1, 2, 3] as number[];",
      errors: [{ messageId: "preferAsConst", data: { name: "VALUES" } }],
    },
    {
      code: "const VALUES = [1, 2, 3] satisfies number[];",
      errors: [{ messageId: "preferAsConst", data: { name: "VALUES" } }],
    },
    {
      code: "export const LABELS = { a: 'A' };",
      errors: [{ messageId: "preferAsConst", data: { name: "LABELS" } }],
    },
    {
      code: "export const routes = ['home', 'settings'];",
      errors: [{ messageId: "preferAsConst", data: { name: "routes" } }],
    },
    {
      code: "const routes = ['home', 'settings']; export { routes };",
      errors: [{ messageId: "preferAsConst", data: { name: "routes" } }],
    },
    {
      code: "const routes = ['home', 'settings']; export { routes as appRoutes };",
      errors: [{ messageId: "preferAsConst", data: { name: "routes" } }],
    },
    {
      code: "const lookup = new Map([['home', '/']]); export default lookup;",
      errors: [{ messageId: "preferReadonlyCollection", data: { name: "lookup", kind: "Map" } }],
    },
    {
      code: "const routes = ['home']; export default routes!;",
      errors: [{ messageId: "preferAsConst", data: { name: "routes" } }],
    },
    {
      code: "const routes = ['home']; export default (routes satisfies string[]);",
      errors: [{ messageId: "preferAsConst", data: { name: "routes" } }],
    },
    {
      code: "export const routes = ['home']; routes.push('settings');",
      errors: [{ messageId: "preferAsConst", data: { name: "routes" } }],
    },
    {
      code: "type Routes = string[]; export const routes: Routes = [];",
      errors: [{ messageId: "preferAsConst", data: { name: "routes" } }],
    },
    {
      code: "const VALUES = ([1, 2] as const) as unknown as number[];",
      errors: [{ messageId: "preferAsConst", data: { name: "VALUES" } }],
    },
    {
      code: "const KINDS = new Set(['a', 'b']);",
      errors: [{ messageId: "preferReadonlyCollection", data: { name: "KINDS", kind: "Set" } }],
    },
    {
      code: "const LOOKUP = new Map([['a', 1]]);",
      errors: [{ messageId: "preferReadonlyCollection", data: { name: "LOOKUP", kind: "Map" } }],
    },
    {
      code: "const KINDS: Readonly<Set<string>> = new Set(['a']);",
      errors: [{ messageId: "preferReadonlyCollection", data: { name: "KINDS", kind: "Set" } }],
    },
    {
      code: "const LOOKUP = new Map([['a', 1]]) as Readonly<Map<string, number>>;",
      errors: [{ messageId: "preferReadonlyCollection", data: { name: "LOOKUP", kind: "Map" } }],
    },
    {
      code: "const KINDS = Object.freeze(new Set(['a']));",
      errors: [{ messageId: "preferReadonlyCollection", data: { name: "KINDS", kind: "Set" } }],
    },
    {
      code: "const LOOKUP = Object.freeze(new Map([['a', 1]]));",
      errors: [{ messageId: "preferReadonlyCollection", data: { name: "LOOKUP", kind: "Map" } }],
    },
  ],
});
