import * as tsParser from "@typescript-eslint/parser";
import { RuleTester } from "@typescript-eslint/rule-tester";
import { afterAll, describe, it } from "vitest";

import rule from "../../src/rules/prefer-immutable-module-constant.js";

RuleTester.afterAll = afterAll;
RuleTester.describe = describe;
RuleTester.it = it;
RuleTester.itOnly = it.only;

const ruleTester = new RuleTester({
  languageOptions: {
    parser: tsParser,
    parserOptions: { ecmaVersion: "latest", sourceType: "module" },
  },
});

ruleTester.run("prefer-immutable-module-constant", rule, {
  valid: [
    "const VALUES = [1, 2, 3] as const;",
    "const VALUES = [1, 2, 3] as const satisfies readonly number[];",
    "const VALUES: readonly number[] = [1, 2, 3];",
    "const VALUES: ReadonlyArray<number> = [1, 2, 3];",
    "const VALUES = [1, 2, 3] as readonly number[];",
    "const LABELS: Readonly<Record<string, string>> = { a: 'A' };",
    "const LABELS = { a: 'A' } as Readonly<Record<string, string>>;",
    "const LABELS = Object.freeze({ a: 'A' });",
    "const LABELS = Object.freeze({ a: 'A' }) satisfies Readonly<Record<string, string>>;",
    "const KINDS: ReadonlySet<string> = new Set(['a']);",
    "const LOOKUP: ReadonlyMap<string, number> = new Map([['a', 1]]);",
    "const value = { a: 1 };",
    "function build() { const VALUES = [1, 2, 3]; return VALUES; }",
    "let VALUES = [1, 2, 3];",
    "const VALUES = createValues();",
    "const VALUES = [1, 2, 3]; VALUES.push(4);",
    "const LABELS = { a: 'A' }; LABELS.a = 'B';",
    "const LABELS = { nested: { value: 'A' } }; LABELS.nested.value = 'B';",
    "const LABELS = { nested: [] as string[] }; LABELS.nested.push('A');",
    "const LABELS = { a: 'A' }; Object.assign(LABELS, { a: 'B' });",
    { code: "const VALUES = [1, 2, 3];", filename: "src/value.test.ts" },
    { code: "// generated by schema\nconst VALUES = [1, 2, 3];", filename: "src/value.ts" },
    { code: "const VALUES = [1, 2, 3];", filename: "src/openapi-gen/value.ts" },
    { code: "const VALUES = [1, 2, 3];", filename: "src/value.types.ts" },
  ],
  invalid: [
    {
      code: "const VALUES = [1, 2, 3];",
      errors: [{ messageId: "preferAsConst", data: { name: "VALUES" } }],
    },
    {
      code: "const _VALUES = [1, 2, 3];",
      errors: [{ messageId: "preferAsConst", data: { name: "_VALUES" } }],
    },
    {
      code: "const X = [1, 2, 3];",
      errors: [{ messageId: "preferAsConst", data: { name: "X" } }],
    },
    {
      code: "const VALUES = [1, 2, 3] as number[];",
      errors: [{ messageId: "preferAsConst", data: { name: "VALUES" } }],
    },
    {
      code: "const VALUES = [1, 2, 3] satisfies number[];",
      errors: [{ messageId: "preferAsConst", data: { name: "VALUES" } }],
    },
    {
      code: "export const LABELS = { a: 'A' };",
      errors: [{ messageId: "preferAsConst", data: { name: "LABELS" } }],
    },
    {
      code: "const KINDS = new Set(['a', 'b']);",
      errors: [{ messageId: "preferReadonlyCollection", data: { name: "KINDS", kind: "Set" } }],
    },
    {
      code: "const LOOKUP = new Map([['a', 1]]);",
      errors: [{ messageId: "preferReadonlyCollection", data: { name: "LOOKUP", kind: "Map" } }],
    },
  ],
});
