import { RuleTester } from "@typescript-eslint/rule-tester";
import { afterAll, describe, it } from "vitest";

import rule from "../../src/rules/trailing-value-narration.js";

RuleTester.afterAll = afterAll;
RuleTester.describe = describe;
RuleTester.it = it;
RuleTester.itOnly = it.only;

const ruleTester = new RuleTester();

ruleTester.run("trailing-value-narration", rule, {
  valid: [
    // A conversion the reader cannot do in their head is the comment worth having.
    { code: "const timeout = 300000; // ~3.5 days" },
    { code: "const window = 60 * 60 * 24 * 5; // about a working week" },
    // A why, not a restatement.
    { code: "const backoff = 2 * 60; // doubles per attempt, capped by the gateway" },
    // Owned by a ticket or a URL (protected-class signal S1).
    { code: "const retries = 3; // 3 retries (PLT-812)" },
    { code: "const retries = 3; // 3 retries — see https://example.com/limits" },
    // No literal on the line at all.
    { code: "const timeout = compute(); // 5 minutes" },
    // No number in the comment.
    { code: "const staleTime = 5 * 60 * 1000; // minutes" },
    // A directive.
    { code: "const staleTime = 5 * 60 * 1000; // TODO@nmaswood: 5 minutes" },
    // An own-line comment is `no-comment-cruft`'s / `no-restated-comment`'s business.
    { code: "// 5 minutes\nconst staleTime = 5 * 60 * 1000;" },
    // A generated file mirrors its generator.
    {
      code: "// @generated by codegen\nconst staleTime = 5 * 60 * 1000; // 5 minutes",
      filename: "gen.ts",
    },
  ],
  invalid: [
    {
      code: "const staleTime = 5 * 60 * 1000; // 5 minutes",
      errors: [{ messageId: "narratesValue" }],
    },
    {
      code: "export const COOKIE_MAX_AGE_SECONDS = 60 * 60 * 24 * 90; // 90 days",
      errors: [{ messageId: "narratesValue" }],
    },
    {
      code: "const options = { gcTime: 1000 * 60 * 60 * 24 }; // 24 hours",
      errors: [{ messageId: "narratesValue" }],
    },
    {
      code: "const poll = 30 * 1000; // 30 seconds",
      errors: [{ messageId: "narratesValue" }],
    },
    // Identifier words on the line do not rescue the comment.
    {
      code: "const staleTime = 5 * 60 * 1000; // stale time 5 minutes",
      errors: [{ messageId: "narratesValue" }],
    },
  ],
});
