import { RuleTester } from "@typescript-eslint/rule-tester";
import { afterAll, describe, it } from "vitest";

import rule, { ZOD_NAMING_CONVENTION_DOCUMENTATION } from "../../src/rules/zod-naming-convention.js";

// Bind vitest to RuleTester for proper test reporting
RuleTester.afterAll = afterAll;
RuleTester.describe = describe;
RuleTester.it = it;
RuleTester.itOnly = it.only;

const RULE_TESTER = new RuleTester();
const zod = (code: string): string => `import { z } from "zod"; ${code}`;

RULE_TESTER.run("zod-naming-convention", rule, {
  valid: [
    { name: "accepts the documented recognizable schema name", code: ZOD_NAMING_CONVENTION_DOCUMENTATION.examples[0].files[0].source },
    {
      name: "ignores test-local schemas",
      code: 'const a = z.lazy(() => z.string());',
      filename: "/repo/src/v4/classic/tests/index.test.ts",
    },
    {
      name: "ignores schemas in a benchmarks directory",
      code: "const short = z.object({ string: z.string() });",
      filename: "/repo/packages/zod/src/v3/benchmarks/object.ts",
    },
    {
      name: "ignores schemas in a bench directory",
      code: "const long = z.object({ a: z.string() });",
      filename: "/repo/packages/bench/index.ts",
    },
    // Generated clients choose names from upstream specs/codegen templates.
    {
      code: 'export const userResponse = z.object({ id: z.string() });',
      filename: "/repo/packages/contracts/generated/api/zod.gen.ts",
    },
    {
      code: "// @generated by openapi-zod-client\nexport const userResponse = z.object({ id: z.string() });",
      filename: "/repo/src/api.ts",
    },
    {
      name: "ignores parsed values and result envelopes",
      code: `const parsed = z.string().parse(value);
             const parsedAsync = z.string().parseAsync(value);
             const result = z.string().safeParse(value);
             const asyncResult = z.string().safeParseAsync(value);`,
    },
    {
      name: "ignores encoded and decoded codec values",
      code: `const encoded = z.codec(z.string(), z.string(), handlers).encode(value);
             const decoded = z.codec(z.string(), z.string(), handlers).decode(value);
             const encodedAsync = z.codec(z.string(), z.string(), handlers).encodeAsync(value);
             const decodedAsync = z.codec(z.string(), z.string(), handlers).decodeAsync(value);`,
    },
    {
      name: "ignores safe codec result envelopes",
      code: `const encoded = z.codec(z.string(), z.string(), handlers).safeEncode(value);
             const decoded = z.codec(z.string(), z.string(), handlers).safeDecode(value);
             const encodedAsync = z.codec(z.string(), z.string(), handlers).safeEncodeAsync(value);
             const decodedAsync = z.codec(z.string(), z.string(), handlers).safeDecodeAsync(value);`,
    },
    {
      name: "ignores JSON Schema objects, registries, and implemented functions",
      code: `const json = z.toJSONSchema(HelloSchema);
             const registry = z.registry<Meta>();
             const fn = z.function().implement(handler);`,
    },
    {
      name: "ignores Zod diagnostic formatting and schema inspection values",
      code: `const pretty = z.prettifyError(error);
             const tree = z.treeifyError(error);
             const flat = z.flattenError(error);
             const optional = z.string().isOptional();
             const nullable = z.string().isNullable();`,
    },
    {
      name: "accepts names containing schema under the default convention",
      code: `const schema = z.object({ a: z.string() });
             const schema1 = z.string().min(5);
             const numberSchemaOptional = z.number().optional();`,
    },
    {
      name: "accepts a schema-containing name under the suffix convention",
      code: "const schema1 = z.string();",
      options: [{ convention: "suffix" }],
    },
    // Direct z.object() with Z prefix
    { code: "const ZUser = z.object({ name: z.string() });" },
    // Chained z.object().extend() with Z prefix
    { code: "const ZUser = z.object({ name: z.string() }).extend({ age: z.number() });" },
    // Long chains with Z prefix
    {
      code: "const ZUser = z.object({ name: z.string() }).extend({ age: z.number() }).refine((d) => d.age > 0);",
    },
    // Non-Zod call expressions are ignored
    { code: "const user = createUser({ name: 'Alice' });" },
    {
      name: "does not confuse a resolved non-Zod z binding for Zod",
      code: 'import z from "zero-lib"; const user = z.object({ name: z.string() });',
    },
    {
      name: "does not confuse a local z binding for Zod",
      code: "const z = localSchemaBuilder; const user = z.object({ name: z.string() });",
    },
    {
      name: "does not guess that an unresolved ambient z is Zod",
      code: "const user = z.object({ name: z.string() });",
    },
    // Non-CallExpression initializers are ignored
    { code: "const greeting = 'hello';" },
    // No initializer at all
    { code: "let unset;" },
    // z.literal — also Zod, with Z prefix
    { code: "const ZRole = z.literal('admin');" },
    // Member expression initializer that does not start with z
    { code: "const config = settings.values;" },
    { code: "const userSchema = z.object({ name: z.string() });" },
    { code: "const SubmitFormDataSchema = z.object({ t: z.string() });" },
    { code: "const RoleSchema = z.enum(['admin', 'user']);" },
    {
      code: "const userSchema = z.object({ name: z.string() }).extend({ age: z.number() });",
    },
    // Explicit prefix-only convention: `ZUser` conforms.
    {
      code: "const ZUser = z.object({ name: z.string() });",
      options: [{ convention: "prefix" }],
    },
    // Explicit suffix-only convention: `userSchema` conforms.
    {
      code: "const userSchema = z.object({ name: z.string() });",
      options: [{ convention: "suffix" }],
    },
  ],
  invalid: [
    { name: "reports the documented unmarked schema name", code: ZOD_NAMING_CONVENTION_DOCUMENTATION.examples[1].files[0].source, errors: [{ messageId: "zodSchemaName" }] },
    {
      name: "does not treat a benchmarking filename as a benchmark directory",
      code: zod("const user = z.object({ a: z.string() });"),
      filename: "/repo/src/benchmarking-report.ts",
      errors: [{ messageId: "zodSchemaName" }],
    },
    {
      name: "does not treat workbench as a bench directory",
      code: zod("const user = z.object({ a: z.string() });"),
      filename: "/repo/src/lib/workbench/schemas.ts",
      errors: [{ messageId: "zodSchemaName" }],
    },
    {
      name: "reports a name with no schema marker",
      code: zod('const user = z.object({ a: z.string() });'),
      errors: [{ messageId: "zodSchemaName" }],
    },
    {
      name: "reports a schema builder chain",
      code: 'import { z as schema } from "zod"; const user = schema.object({ a: schema.string() }).strict();',
      errors: [{ messageId: "zodSchemaName" }],
    },
    {
      name: "reports schemas rooted in the Zod coerce namespace",
      code: 'import { z } from "zod"; const user = z.coerce.string();',
      errors: [{ messageId: "zodSchemaName" }],
    },
    {
      name: "requires the prefix even when a prefix-only name contains schema",
      code: zod('const userschema = z.object({ a: z.string() });'),
      options: [{ convention: "prefix" }],
      errors: [{ messageId: "zPrefix" }],
    },
    // Direct z.object() matching neither convention.
    {
      code: zod("const User = z.object({ name: z.string() });"),
      errors: [{ messageId: "zodSchemaName" }],
    },
    // Chained z.object().extend() matching neither convention.
    {
      code: zod("const User = z.object({ name: z.string() }).extend({ age: z.number() });"),
      errors: [{ messageId: "zodSchemaName" }],
    },
    // Lowercase `z` prefix is not the prefix convention (needs `Z<Capital>`).
    {
      code: zod("const zUser = z.object({ name: z.string() });"),
      errors: [{ messageId: "zodSchemaName" }],
    },
    // Even deeper chains still get flagged
    {
      code: zod("const User = z.object({}).extend({}).refine(() => true);"),
      errors: [{ messageId: "zodSchemaName" }],
    },
    // z.enum() — schema, but wrong name
    {
      code: zod("const Role = z.enum(['admin', 'user']);"),
      errors: [{ messageId: "zodSchemaName" }],
    },
    {
      name: "does not silently add role suffixes to the default convention",
      code: zod("const UserInput = z.object({ name: z.string() });"),
      errors: [{ messageId: "zodSchemaName" }],
    },
    // A team pinned to the prefix convention still rejects the suffix form.
    {
      code: zod("const userSchema = z.object({ name: z.string() });"),
      options: [{ convention: "prefix" }],
      errors: [{ messageId: "zPrefix" }],
    },
    // ...and vice versa.
    {
      code: zod("const ZUser = z.object({ name: z.string() });"),
      options: [{ convention: "suffix" }],
      errors: [{ messageId: "schemaSuffix" }],
    },
  ],
});
